// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAction = `-- name: CreateAction :one
INSERT INTO pfas.actions (
    id, workspace_id, decision_package_id, position, code, category, title, detail,
    timing, source_id, execution_mode, status, approval_required, channel,
    recipient, subject, message, attachments, revision, payload_hash, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20, $21, $21
)
ON CONFLICT (decision_package_id, code) DO NOTHING
RETURNING id, workspace_id, decision_package_id, position, code, category, title, detail, timing, source_id, execution_mode, status, approval_required, channel, recipient, subject, message, attachments, revision, payload_hash, created_at, updated_at
`

type CreateActionParams struct {
	ID                uuid.UUID          `json:"id"`
	WorkspaceID       uuid.UUID          `json:"workspace_id"`
	DecisionPackageID uuid.UUID          `json:"decision_package_id"`
	Position          int32              `json:"position"`
	Code              string             `json:"code"`
	Category          string             `json:"category"`
	Title             string             `json:"title"`
	Detail            string             `json:"detail"`
	Timing            string             `json:"timing"`
	SourceID          string             `json:"source_id"`
	ExecutionMode     string             `json:"execution_mode"`
	Status            string             `json:"status"`
	ApprovalRequired  bool               `json:"approval_required"`
	Channel           string             `json:"channel"`
	Recipient         string             `json:"recipient"`
	Subject           string             `json:"subject"`
	Message           string             `json:"message"`
	Attachments       []byte             `json:"attachments"`
	Revision          int32              `json:"revision"`
	PayloadHash       string             `json:"payload_hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAction(ctx context.Context, arg CreateActionParams) (PfasAction, error) {
	row := q.db.QueryRow(ctx, createAction,
		arg.ID,
		arg.WorkspaceID,
		arg.DecisionPackageID,
		arg.Position,
		arg.Code,
		arg.Category,
		arg.Title,
		arg.Detail,
		arg.Timing,
		arg.SourceID,
		arg.ExecutionMode,
		arg.Status,
		arg.ApprovalRequired,
		arg.Channel,
		arg.Recipient,
		arg.Subject,
		arg.Message,
		arg.Attachments,
		arg.Revision,
		arg.PayloadHash,
		arg.CreatedAt,
	)
	var i PfasAction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionPackageID,
		&i.Position,
		&i.Code,
		&i.Category,
		&i.Title,
		&i.Detail,
		&i.Timing,
		&i.SourceID,
		&i.ExecutionMode,
		&i.Status,
		&i.ApprovalRequired,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Message,
		&i.Attachments,
		&i.Revision,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createActionDecision = `-- name: CreateActionDecision :one
INSERT INTO pfas.action_decisions (
    id, workspace_id, action_id, decision_package_id, kind, action_revision,
    payload_hash, actor_name, actor_role, note, acknowledged_gap_codes, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, workspace_id, action_id, decision_package_id, kind, action_revision, payload_hash, actor_name, actor_role, note, acknowledged_gap_codes, created_at
`

type CreateActionDecisionParams struct {
	ID                   uuid.UUID          `json:"id"`
	WorkspaceID          uuid.UUID          `json:"workspace_id"`
	ActionID             uuid.UUID          `json:"action_id"`
	DecisionPackageID    uuid.UUID          `json:"decision_package_id"`
	Kind                 string             `json:"kind"`
	ActionRevision       int32              `json:"action_revision"`
	PayloadHash          string             `json:"payload_hash"`
	ActorName            string             `json:"actor_name"`
	ActorRole            string             `json:"actor_role"`
	Note                 string             `json:"note"`
	AcknowledgedGapCodes []byte             `json:"acknowledged_gap_codes"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateActionDecision(ctx context.Context, arg CreateActionDecisionParams) (PfasActionDecision, error) {
	row := q.db.QueryRow(ctx, createActionDecision,
		arg.ID,
		arg.WorkspaceID,
		arg.ActionID,
		arg.DecisionPackageID,
		arg.Kind,
		arg.ActionRevision,
		arg.PayloadHash,
		arg.ActorName,
		arg.ActorRole,
		arg.Note,
		arg.AcknowledgedGapCodes,
		arg.CreatedAt,
	)
	var i PfasActionDecision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActionID,
		&i.DecisionPackageID,
		&i.Kind,
		&i.ActionRevision,
		&i.PayloadHash,
		&i.ActorName,
		&i.ActorRole,
		&i.Note,
		&i.AcknowledgedGapCodes,
		&i.CreatedAt,
	)
	return i, err
}

const createExecutionAttempt = `-- name: CreateExecutionAttempt :one
INSERT INTO pfas.execution_attempts (
    id, workspace_id, action_id, approval_id, idempotency_key, outcome,
    receipt, handoff_artifact, handoff_sha256, completed_at, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10)
ON CONFLICT (action_id, idempotency_key) DO NOTHING
RETURNING id, workspace_id, action_id, approval_id, idempotency_key, outcome, receipt, handoff_artifact, handoff_sha256, completed_at, created_at
`

type CreateExecutionAttemptParams struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	ActionID        uuid.UUID          `json:"action_id"`
	ApprovalID      uuid.UUID          `json:"approval_id"`
	IdempotencyKey  string             `json:"idempotency_key"`
	Outcome         string             `json:"outcome"`
	Receipt         []byte             `json:"receipt"`
	HandoffArtifact []byte             `json:"handoff_artifact"`
	HandoffSha256   *string            `json:"handoff_sha256"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateExecutionAttempt(ctx context.Context, arg CreateExecutionAttemptParams) (PfasExecutionAttempt, error) {
	row := q.db.QueryRow(ctx, createExecutionAttempt,
		arg.ID,
		arg.WorkspaceID,
		arg.ActionID,
		arg.ApprovalID,
		arg.IdempotencyKey,
		arg.Outcome,
		arg.Receipt,
		arg.HandoffArtifact,
		arg.HandoffSha256,
		arg.CompletedAt,
	)
	var i PfasExecutionAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActionID,
		&i.ApprovalID,
		&i.IdempotencyKey,
		&i.Outcome,
		&i.Receipt,
		&i.HandoffArtifact,
		&i.HandoffSha256,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPlacementRelease = `-- name: CreatePlacementRelease :one
INSERT INTO pfas.placement_releases (
    id, workspace_id, decision_package_id, placement_evaluation_id,
    action_id, approval_id, execution_attempt_id, released_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (placement_evaluation_id) DO NOTHING
RETURNING id, workspace_id, decision_package_id, placement_evaluation_id, action_id, approval_id, execution_attempt_id, released_at
`

type CreatePlacementReleaseParams struct {
	ID                    uuid.UUID          `json:"id"`
	WorkspaceID           uuid.UUID          `json:"workspace_id"`
	DecisionPackageID     uuid.UUID          `json:"decision_package_id"`
	PlacementEvaluationID uuid.UUID          `json:"placement_evaluation_id"`
	ActionID              uuid.UUID          `json:"action_id"`
	ApprovalID            uuid.UUID          `json:"approval_id"`
	ExecutionAttemptID    uuid.UUID          `json:"execution_attempt_id"`
	ReleasedAt            pgtype.Timestamptz `json:"released_at"`
}

func (q *Queries) CreatePlacementRelease(ctx context.Context, arg CreatePlacementReleaseParams) (PfasPlacementRelease, error) {
	row := q.db.QueryRow(ctx, createPlacementRelease,
		arg.ID,
		arg.WorkspaceID,
		arg.DecisionPackageID,
		arg.PlacementEvaluationID,
		arg.ActionID,
		arg.ApprovalID,
		arg.ExecutionAttemptID,
		arg.ReleasedAt,
	)
	var i PfasPlacementRelease
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionPackageID,
		&i.PlacementEvaluationID,
		&i.ActionID,
		&i.ApprovalID,
		&i.ExecutionAttemptID,
		&i.ReleasedAt,
	)
	return i, err
}

const getActionByPackageCode = `-- name: GetActionByPackageCode :one
SELECT id, workspace_id, decision_package_id, position, code, category, title, detail, timing, source_id, execution_mode, status, approval_required, channel, recipient, subject, message, attachments, revision, payload_hash, created_at, updated_at FROM pfas.actions
WHERE decision_package_id = $1 AND code = $2
`

type GetActionByPackageCodeParams struct {
	DecisionPackageID uuid.UUID `json:"decision_package_id"`
	Code              string    `json:"code"`
}

func (q *Queries) GetActionByPackageCode(ctx context.Context, arg GetActionByPackageCodeParams) (PfasAction, error) {
	row := q.db.QueryRow(ctx, getActionByPackageCode, arg.DecisionPackageID, arg.Code)
	var i PfasAction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionPackageID,
		&i.Position,
		&i.Code,
		&i.Category,
		&i.Title,
		&i.Detail,
		&i.Timing,
		&i.SourceID,
		&i.ExecutionMode,
		&i.Status,
		&i.ApprovalRequired,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Message,
		&i.Attachments,
		&i.Revision,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActionForUpdate = `-- name: GetActionForUpdate :one
SELECT id, workspace_id, decision_package_id, position, code, category, title, detail, timing, source_id, execution_mode, status, approval_required, channel, recipient, subject, message, attachments, revision, payload_hash, created_at, updated_at FROM pfas.actions
WHERE id = $1 AND workspace_id = $2
FOR UPDATE
`

type GetActionForUpdateParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetActionForUpdate(ctx context.Context, arg GetActionForUpdateParams) (PfasAction, error) {
	row := q.db.QueryRow(ctx, getActionForUpdate, arg.ID, arg.WorkspaceID)
	var i PfasAction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionPackageID,
		&i.Position,
		&i.Code,
		&i.Category,
		&i.Title,
		&i.Detail,
		&i.Timing,
		&i.SourceID,
		&i.ExecutionMode,
		&i.Status,
		&i.ApprovalRequired,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Message,
		&i.Attachments,
		&i.Revision,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentApproval = `-- name: GetCurrentApproval :one
SELECT id, workspace_id, action_id, decision_package_id, kind, action_revision, payload_hash, actor_name, actor_role, note, acknowledged_gap_codes, created_at FROM pfas.action_decisions
WHERE action_id = $1
  AND workspace_id = $2
  AND kind = 'APPROVED'
  AND action_revision = $3
  AND payload_hash = $4
`

type GetCurrentApprovalParams struct {
	ActionID       uuid.UUID `json:"action_id"`
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	ActionRevision int32     `json:"action_revision"`
	PayloadHash    string    `json:"payload_hash"`
}

func (q *Queries) GetCurrentApproval(ctx context.Context, arg GetCurrentApprovalParams) (PfasActionDecision, error) {
	row := q.db.QueryRow(ctx, getCurrentApproval,
		arg.ActionID,
		arg.WorkspaceID,
		arg.ActionRevision,
		arg.PayloadHash,
	)
	var i PfasActionDecision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActionID,
		&i.DecisionPackageID,
		&i.Kind,
		&i.ActionRevision,
		&i.PayloadHash,
		&i.ActorName,
		&i.ActorRole,
		&i.Note,
		&i.AcknowledgedGapCodes,
		&i.CreatedAt,
	)
	return i, err
}

const getExecutionAttempt = `-- name: GetExecutionAttempt :one
SELECT id, workspace_id, action_id, approval_id, idempotency_key, outcome, receipt, handoff_artifact, handoff_sha256, completed_at, created_at FROM pfas.execution_attempts
WHERE id = $1 AND workspace_id = $2
`

type GetExecutionAttemptParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetExecutionAttempt(ctx context.Context, arg GetExecutionAttemptParams) (PfasExecutionAttempt, error) {
	row := q.db.QueryRow(ctx, getExecutionAttempt, arg.ID, arg.WorkspaceID)
	var i PfasExecutionAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActionID,
		&i.ApprovalID,
		&i.IdempotencyKey,
		&i.Outcome,
		&i.Receipt,
		&i.HandoffArtifact,
		&i.HandoffSha256,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExecutionByIdempotencyKey = `-- name: GetExecutionByIdempotencyKey :one
SELECT id, workspace_id, action_id, approval_id, idempotency_key, outcome, receipt, handoff_artifact, handoff_sha256, completed_at, created_at FROM pfas.execution_attempts
WHERE action_id = $1 AND idempotency_key = $2
`

type GetExecutionByIdempotencyKeyParams struct {
	ActionID       uuid.UUID `json:"action_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetExecutionByIdempotencyKey(ctx context.Context, arg GetExecutionByIdempotencyKeyParams) (PfasExecutionAttempt, error) {
	row := q.db.QueryRow(ctx, getExecutionByIdempotencyKey, arg.ActionID, arg.IdempotencyKey)
	var i PfasExecutionAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActionID,
		&i.ApprovalID,
		&i.IdempotencyKey,
		&i.Outcome,
		&i.Receipt,
		&i.HandoffArtifact,
		&i.HandoffSha256,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlacementRelease = `-- name: GetPlacementRelease :one
SELECT id, workspace_id, decision_package_id, placement_evaluation_id, action_id, approval_id, execution_attempt_id, released_at FROM pfas.placement_releases
WHERE placement_evaluation_id = $1 AND workspace_id = $2
`

type GetPlacementReleaseParams struct {
	PlacementEvaluationID uuid.UUID `json:"placement_evaluation_id"`
	WorkspaceID           uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetPlacementRelease(ctx context.Context, arg GetPlacementReleaseParams) (PfasPlacementRelease, error) {
	row := q.db.QueryRow(ctx, getPlacementRelease, arg.PlacementEvaluationID, arg.WorkspaceID)
	var i PfasPlacementRelease
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionPackageID,
		&i.PlacementEvaluationID,
		&i.ActionID,
		&i.ApprovalID,
		&i.ExecutionAttemptID,
		&i.ReleasedAt,
	)
	return i, err
}

const listActionDecisionsForPackage = `-- name: ListActionDecisionsForPackage :many
SELECT id, workspace_id, action_id, decision_package_id, kind, action_revision, payload_hash, actor_name, actor_role, note, acknowledged_gap_codes, created_at FROM pfas.action_decisions
WHERE decision_package_id = $1 AND workspace_id = $2
ORDER BY created_at, id
`

type ListActionDecisionsForPackageParams struct {
	DecisionPackageID uuid.UUID `json:"decision_package_id"`
	WorkspaceID       uuid.UUID `json:"workspace_id"`
}

func (q *Queries) ListActionDecisionsForPackage(ctx context.Context, arg ListActionDecisionsForPackageParams) ([]PfasActionDecision, error) {
	rows, err := q.db.Query(ctx, listActionDecisionsForPackage, arg.DecisionPackageID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasActionDecision{}
	for rows.Next() {
		var i PfasActionDecision
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActionID,
			&i.DecisionPackageID,
			&i.Kind,
			&i.ActionRevision,
			&i.PayloadHash,
			&i.ActorName,
			&i.ActorRole,
			&i.Note,
			&i.AcknowledgedGapCodes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionsForPackage = `-- name: ListActionsForPackage :many
SELECT id, workspace_id, decision_package_id, position, code, category, title, detail, timing, source_id, execution_mode, status, approval_required, channel, recipient, subject, message, attachments, revision, payload_hash, created_at, updated_at FROM pfas.actions
WHERE decision_package_id = $1 AND workspace_id = $2
ORDER BY position
`

type ListActionsForPackageParams struct {
	DecisionPackageID uuid.UUID `json:"decision_package_id"`
	WorkspaceID       uuid.UUID `json:"workspace_id"`
}

func (q *Queries) ListActionsForPackage(ctx context.Context, arg ListActionsForPackageParams) ([]PfasAction, error) {
	rows, err := q.db.Query(ctx, listActionsForPackage, arg.DecisionPackageID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasAction{}
	for rows.Next() {
		var i PfasAction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DecisionPackageID,
			&i.Position,
			&i.Code,
			&i.Category,
			&i.Title,
			&i.Detail,
			&i.Timing,
			&i.SourceID,
			&i.ExecutionMode,
			&i.Status,
			&i.ApprovalRequired,
			&i.Channel,
			&i.Recipient,
			&i.Subject,
			&i.Message,
			&i.Attachments,
			&i.Revision,
			&i.PayloadHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionsForPackage = `-- name: ListExecutionsForPackage :many
SELECT execution.id, execution.workspace_id, execution.action_id, execution.approval_id, execution.idempotency_key, execution.outcome, execution.receipt, execution.handoff_artifact, execution.handoff_sha256, execution.completed_at, execution.created_at
FROM pfas.execution_attempts execution
JOIN pfas.actions action ON action.id = execution.action_id
WHERE action.decision_package_id = $1 AND execution.workspace_id = $2
ORDER BY execution.created_at, execution.id
`

type ListExecutionsForPackageParams struct {
	DecisionPackageID uuid.UUID `json:"decision_package_id"`
	WorkspaceID       uuid.UUID `json:"workspace_id"`
}

func (q *Queries) ListExecutionsForPackage(ctx context.Context, arg ListExecutionsForPackageParams) ([]PfasExecutionAttempt, error) {
	rows, err := q.db.Query(ctx, listExecutionsForPackage, arg.DecisionPackageID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasExecutionAttempt{}
	for rows.Next() {
		var i PfasExecutionAttempt
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActionID,
			&i.ApprovalID,
			&i.IdempotencyKey,
			&i.Outcome,
			&i.Receipt,
			&i.HandoffArtifact,
			&i.HandoffSha256,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActionPayload = `-- name: UpdateActionPayload :one
UPDATE pfas.actions
SET recipient = $3,
    subject = $4,
    message = $5,
    attachments = $6,
    revision = revision + 1,
    payload_hash = $7,
    status = 'PROPOSED',
    updated_at = $8
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, decision_package_id, position, code, category, title, detail, timing, source_id, execution_mode, status, approval_required, channel, recipient, subject, message, attachments, revision, payload_hash, created_at, updated_at
`

type UpdateActionPayloadParams struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Recipient   string             `json:"recipient"`
	Subject     string             `json:"subject"`
	Message     string             `json:"message"`
	Attachments []byte             `json:"attachments"`
	PayloadHash string             `json:"payload_hash"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateActionPayload(ctx context.Context, arg UpdateActionPayloadParams) (PfasAction, error) {
	row := q.db.QueryRow(ctx, updateActionPayload,
		arg.ID,
		arg.WorkspaceID,
		arg.Recipient,
		arg.Subject,
		arg.Message,
		arg.Attachments,
		arg.PayloadHash,
		arg.UpdatedAt,
	)
	var i PfasAction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionPackageID,
		&i.Position,
		&i.Code,
		&i.Category,
		&i.Title,
		&i.Detail,
		&i.Timing,
		&i.SourceID,
		&i.ExecutionMode,
		&i.Status,
		&i.ApprovalRequired,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Message,
		&i.Attachments,
		&i.Revision,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateActionStatus = `-- name: UpdateActionStatus :one
UPDATE pfas.actions
SET status = $3, updated_at = $4
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, decision_package_id, position, code, category, title, detail, timing, source_id, execution_mode, status, approval_required, channel, recipient, subject, message, attachments, revision, payload_hash, created_at, updated_at
`

type UpdateActionStatusParams struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Status      string             `json:"status"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateActionStatus(ctx context.Context, arg UpdateActionStatusParams) (PfasAction, error) {
	row := q.db.QueryRow(ctx, updateActionStatus,
		arg.ID,
		arg.WorkspaceID,
		arg.Status,
		arg.UpdatedAt,
	)
	var i PfasAction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionPackageID,
		&i.Position,
		&i.Code,
		&i.Category,
		&i.Title,
		&i.Detail,
		&i.Timing,
		&i.SourceID,
		&i.ExecutionMode,
		&i.Status,
		&i.ApprovalRequired,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Message,
		&i.Attachments,
		&i.Revision,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
