// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: application.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmApplication = `-- name: ConfirmApplication :one
UPDATE pfas.application_confirmations
SET confirmed = true, notes = $3, confirmed_at = now()
WHERE id = $1 AND workspace_id = $2 AND confirmed = false
RETURNING id, workspace_id, application_id, farmer_party_id, confirmed, notes, confirmed_at, created_at
`

type ConfirmApplicationParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Notes       string    `json:"notes"`
}

func (q *Queries) ConfirmApplication(ctx context.Context, arg ConfirmApplicationParams) (PfasApplicationConfirmation, error) {
	row := q.db.QueryRow(ctx, confirmApplication, arg.ID, arg.WorkspaceID, arg.Notes)
	var i PfasApplicationConfirmation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ApplicationID,
		&i.FarmerPartyID,
		&i.Confirmed,
		&i.Notes,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createApplicationConfirmation = `-- name: CreateApplicationConfirmation :one
INSERT INTO pfas.application_confirmations (id, workspace_id, application_id, farmer_party_id, confirmed, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, application_id, farmer_party_id, confirmed, notes, confirmed_at, created_at
`

type CreateApplicationConfirmationParams struct {
	ID            uuid.UUID `json:"id"`
	WorkspaceID   uuid.UUID `json:"workspace_id"`
	ApplicationID uuid.UUID `json:"application_id"`
	FarmerPartyID uuid.UUID `json:"farmer_party_id"`
	Confirmed     bool      `json:"confirmed"`
	Notes         string    `json:"notes"`
}

func (q *Queries) CreateApplicationConfirmation(ctx context.Context, arg CreateApplicationConfirmationParams) (PfasApplicationConfirmation, error) {
	row := q.db.QueryRow(ctx, createApplicationConfirmation,
		arg.ID,
		arg.WorkspaceID,
		arg.ApplicationID,
		arg.FarmerPartyID,
		arg.Confirmed,
		arg.Notes,
	)
	var i PfasApplicationConfirmation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ApplicationID,
		&i.FarmerPartyID,
		&i.Confirmed,
		&i.Notes,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createApplicationRecord = `-- name: CreateApplicationRecord :one
INSERT INTO pfas.application_records (id, workspace_id, batch_id, field_id, contractor_party_id, application_date, dry_tons, rate_dry_tons_per_acre, acres_applied, weather_conditions, field_condition_notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workspace_id, batch_id, field_id, contractor_party_id, application_date, dry_tons, rate_dry_tons_per_acre, acres_applied, weather_conditions, field_condition_notes, created_at, updated_at
`

type CreateApplicationRecordParams struct {
	ID                  uuid.UUID      `json:"id"`
	WorkspaceID         uuid.UUID      `json:"workspace_id"`
	BatchID             uuid.NullUUID  `json:"batch_id"`
	FieldID             uuid.UUID      `json:"field_id"`
	ContractorPartyID   uuid.UUID      `json:"contractor_party_id"`
	ApplicationDate     pgtype.Date    `json:"application_date"`
	DryTons             pgtype.Numeric `json:"dry_tons"`
	RateDryTonsPerAcre  pgtype.Numeric `json:"rate_dry_tons_per_acre"`
	AcresApplied        pgtype.Numeric `json:"acres_applied"`
	WeatherConditions   string         `json:"weather_conditions"`
	FieldConditionNotes string         `json:"field_condition_notes"`
}

func (q *Queries) CreateApplicationRecord(ctx context.Context, arg CreateApplicationRecordParams) (PfasApplicationRecord, error) {
	row := q.db.QueryRow(ctx, createApplicationRecord,
		arg.ID,
		arg.WorkspaceID,
		arg.BatchID,
		arg.FieldID,
		arg.ContractorPartyID,
		arg.ApplicationDate,
		arg.DryTons,
		arg.RateDryTonsPerAcre,
		arg.AcresApplied,
		arg.WeatherConditions,
		arg.FieldConditionNotes,
	)
	var i PfasApplicationRecord
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BatchID,
		&i.FieldID,
		&i.ContractorPartyID,
		&i.ApplicationDate,
		&i.DryTons,
		&i.RateDryTonsPerAcre,
		&i.AcresApplied,
		&i.WeatherConditions,
		&i.FieldConditionNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationConfirmation = `-- name: GetApplicationConfirmation :one
SELECT ac.id, ac.workspace_id, ac.application_id, ac.farmer_party_id, ac.confirmed, ac.notes, ac.confirmed_at, ac.created_at, p.name AS farmer_name
FROM pfas.application_confirmations ac
JOIN pfas.parties p ON p.id = ac.farmer_party_id AND p.workspace_id = ac.workspace_id
WHERE ac.id = $1 AND ac.workspace_id = $2
`

type GetApplicationConfirmationParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetApplicationConfirmationRow struct {
	ID            uuid.UUID          `json:"id"`
	WorkspaceID   uuid.UUID          `json:"workspace_id"`
	ApplicationID uuid.UUID          `json:"application_id"`
	FarmerPartyID uuid.UUID          `json:"farmer_party_id"`
	Confirmed     bool               `json:"confirmed"`
	Notes         string             `json:"notes"`
	ConfirmedAt   pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FarmerName    string             `json:"farmer_name"`
}

func (q *Queries) GetApplicationConfirmation(ctx context.Context, arg GetApplicationConfirmationParams) (GetApplicationConfirmationRow, error) {
	row := q.db.QueryRow(ctx, getApplicationConfirmation, arg.ID, arg.WorkspaceID)
	var i GetApplicationConfirmationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ApplicationID,
		&i.FarmerPartyID,
		&i.Confirmed,
		&i.Notes,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.FarmerName,
	)
	return i, err
}

const getApplicationRecord = `-- name: GetApplicationRecord :one
SELECT ar.id, ar.workspace_id, ar.batch_id, ar.field_id, ar.contractor_party_id, ar.application_date, ar.dry_tons, ar.rate_dry_tons_per_acre, ar.acres_applied, ar.weather_conditions, ar.field_condition_notes, ar.created_at, ar.updated_at, f.name AS field_name, p.name AS contractor_name
FROM pfas.application_records ar
JOIN pfas.candidate_fields f ON f.id = ar.field_id AND f.workspace_id = ar.workspace_id
JOIN pfas.parties p ON p.id = ar.contractor_party_id AND p.workspace_id = ar.workspace_id
WHERE ar.id = $1 AND ar.workspace_id = $2
`

type GetApplicationRecordParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetApplicationRecordRow struct {
	ID                  uuid.UUID          `json:"id"`
	WorkspaceID         uuid.UUID          `json:"workspace_id"`
	BatchID             uuid.NullUUID      `json:"batch_id"`
	FieldID             uuid.UUID          `json:"field_id"`
	ContractorPartyID   uuid.UUID          `json:"contractor_party_id"`
	ApplicationDate     pgtype.Date        `json:"application_date"`
	DryTons             pgtype.Numeric     `json:"dry_tons"`
	RateDryTonsPerAcre  pgtype.Numeric     `json:"rate_dry_tons_per_acre"`
	AcresApplied        pgtype.Numeric     `json:"acres_applied"`
	WeatherConditions   string             `json:"weather_conditions"`
	FieldConditionNotes string             `json:"field_condition_notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	FieldName           string             `json:"field_name"`
	ContractorName      string             `json:"contractor_name"`
}

func (q *Queries) GetApplicationRecord(ctx context.Context, arg GetApplicationRecordParams) (GetApplicationRecordRow, error) {
	row := q.db.QueryRow(ctx, getApplicationRecord, arg.ID, arg.WorkspaceID)
	var i GetApplicationRecordRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BatchID,
		&i.FieldID,
		&i.ContractorPartyID,
		&i.ApplicationDate,
		&i.DryTons,
		&i.RateDryTonsPerAcre,
		&i.AcresApplied,
		&i.WeatherConditions,
		&i.FieldConditionNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FieldName,
		&i.ContractorName,
	)
	return i, err
}

const getFieldLoadingLedger = `-- name: GetFieldLoadingLedger :one
SELECT id, workspace_id, field_id, year, cumulative_dry_tons, last_application_date, last_updated FROM pfas.field_loading_ledger
WHERE field_id = $1 AND year = $2 AND workspace_id = $3
`

type GetFieldLoadingLedgerParams struct {
	FieldID     uuid.UUID `json:"field_id"`
	Year        int32     `json:"year"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetFieldLoadingLedger(ctx context.Context, arg GetFieldLoadingLedgerParams) (PfasFieldLoadingLedger, error) {
	row := q.db.QueryRow(ctx, getFieldLoadingLedger, arg.FieldID, arg.Year, arg.WorkspaceID)
	var i PfasFieldLoadingLedger
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FieldID,
		&i.Year,
		&i.CumulativeDryTons,
		&i.LastApplicationDate,
		&i.LastUpdated,
	)
	return i, err
}

const listApplicationRecordsByContractor = `-- name: ListApplicationRecordsByContractor :many
SELECT ar.id, ar.workspace_id, ar.batch_id, ar.field_id, ar.contractor_party_id, ar.application_date, ar.dry_tons, ar.rate_dry_tons_per_acre, ar.acres_applied, ar.weather_conditions, ar.field_condition_notes, ar.created_at, ar.updated_at, f.name AS field_name
FROM pfas.application_records ar
JOIN pfas.candidate_fields f ON f.id = ar.field_id AND f.workspace_id = ar.workspace_id
WHERE ar.contractor_party_id = $1 AND ar.workspace_id = $2
ORDER BY ar.application_date DESC
`

type ListApplicationRecordsByContractorParams struct {
	ContractorPartyID uuid.UUID `json:"contractor_party_id"`
	WorkspaceID       uuid.UUID `json:"workspace_id"`
}

type ListApplicationRecordsByContractorRow struct {
	ID                  uuid.UUID          `json:"id"`
	WorkspaceID         uuid.UUID          `json:"workspace_id"`
	BatchID             uuid.NullUUID      `json:"batch_id"`
	FieldID             uuid.UUID          `json:"field_id"`
	ContractorPartyID   uuid.UUID          `json:"contractor_party_id"`
	ApplicationDate     pgtype.Date        `json:"application_date"`
	DryTons             pgtype.Numeric     `json:"dry_tons"`
	RateDryTonsPerAcre  pgtype.Numeric     `json:"rate_dry_tons_per_acre"`
	AcresApplied        pgtype.Numeric     `json:"acres_applied"`
	WeatherConditions   string             `json:"weather_conditions"`
	FieldConditionNotes string             `json:"field_condition_notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	FieldName           string             `json:"field_name"`
}

func (q *Queries) ListApplicationRecordsByContractor(ctx context.Context, arg ListApplicationRecordsByContractorParams) ([]ListApplicationRecordsByContractorRow, error) {
	rows, err := q.db.Query(ctx, listApplicationRecordsByContractor, arg.ContractorPartyID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationRecordsByContractorRow{}
	for rows.Next() {
		var i ListApplicationRecordsByContractorRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BatchID,
			&i.FieldID,
			&i.ContractorPartyID,
			&i.ApplicationDate,
			&i.DryTons,
			&i.RateDryTonsPerAcre,
			&i.AcresApplied,
			&i.WeatherConditions,
			&i.FieldConditionNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FieldName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationRecordsByField = `-- name: ListApplicationRecordsByField :many
SELECT ar.id, ar.workspace_id, ar.batch_id, ar.field_id, ar.contractor_party_id, ar.application_date, ar.dry_tons, ar.rate_dry_tons_per_acre, ar.acres_applied, ar.weather_conditions, ar.field_condition_notes, ar.created_at, ar.updated_at, p.name AS contractor_name
FROM pfas.application_records ar
JOIN pfas.parties p ON p.id = ar.contractor_party_id AND p.workspace_id = ar.workspace_id
WHERE ar.field_id = $1 AND ar.workspace_id = $2
ORDER BY ar.application_date DESC
`

type ListApplicationRecordsByFieldParams struct {
	FieldID     uuid.UUID `json:"field_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type ListApplicationRecordsByFieldRow struct {
	ID                  uuid.UUID          `json:"id"`
	WorkspaceID         uuid.UUID          `json:"workspace_id"`
	BatchID             uuid.NullUUID      `json:"batch_id"`
	FieldID             uuid.UUID          `json:"field_id"`
	ContractorPartyID   uuid.UUID          `json:"contractor_party_id"`
	ApplicationDate     pgtype.Date        `json:"application_date"`
	DryTons             pgtype.Numeric     `json:"dry_tons"`
	RateDryTonsPerAcre  pgtype.Numeric     `json:"rate_dry_tons_per_acre"`
	AcresApplied        pgtype.Numeric     `json:"acres_applied"`
	WeatherConditions   string             `json:"weather_conditions"`
	FieldConditionNotes string             `json:"field_condition_notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ContractorName      string             `json:"contractor_name"`
}

func (q *Queries) ListApplicationRecordsByField(ctx context.Context, arg ListApplicationRecordsByFieldParams) ([]ListApplicationRecordsByFieldRow, error) {
	rows, err := q.db.Query(ctx, listApplicationRecordsByField, arg.FieldID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationRecordsByFieldRow{}
	for rows.Next() {
		var i ListApplicationRecordsByFieldRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BatchID,
			&i.FieldID,
			&i.ContractorPartyID,
			&i.ApplicationDate,
			&i.DryTons,
			&i.RateDryTonsPerAcre,
			&i.AcresApplied,
			&i.WeatherConditions,
			&i.FieldConditionNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContractorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldLoadingLedgerByField = `-- name: ListFieldLoadingLedgerByField :many
SELECT id, workspace_id, field_id, year, cumulative_dry_tons, last_application_date, last_updated FROM pfas.field_loading_ledger
WHERE field_id = $1 AND workspace_id = $2
ORDER BY year DESC
`

type ListFieldLoadingLedgerByFieldParams struct {
	FieldID     uuid.UUID `json:"field_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) ListFieldLoadingLedgerByField(ctx context.Context, arg ListFieldLoadingLedgerByFieldParams) ([]PfasFieldLoadingLedger, error) {
	rows, err := q.db.Query(ctx, listFieldLoadingLedgerByField, arg.FieldID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasFieldLoadingLedger{}
	for rows.Next() {
		var i PfasFieldLoadingLedger
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FieldID,
			&i.Year,
			&i.CumulativeDryTons,
			&i.LastApplicationDate,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFieldLoadingLedger = `-- name: UpsertFieldLoadingLedger :one
INSERT INTO pfas.field_loading_ledger (id, workspace_id, field_id, year, cumulative_dry_tons, last_application_date, last_updated)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (field_id, year, workspace_id) DO UPDATE
SET cumulative_dry_tons = pfas.field_loading_ledger.cumulative_dry_tons + $5,
    last_application_date = GREATEST(pfas.field_loading_ledger.last_application_date, $6),
    last_updated = now()
RETURNING id, workspace_id, field_id, year, cumulative_dry_tons, last_application_date, last_updated
`

type UpsertFieldLoadingLedgerParams struct {
	ID                  uuid.UUID      `json:"id"`
	WorkspaceID         uuid.UUID      `json:"workspace_id"`
	FieldID             uuid.UUID      `json:"field_id"`
	Year                int32          `json:"year"`
	CumulativeDryTons   pgtype.Numeric `json:"cumulative_dry_tons"`
	LastApplicationDate pgtype.Date    `json:"last_application_date"`
}

func (q *Queries) UpsertFieldLoadingLedger(ctx context.Context, arg UpsertFieldLoadingLedgerParams) (PfasFieldLoadingLedger, error) {
	row := q.db.QueryRow(ctx, upsertFieldLoadingLedger,
		arg.ID,
		arg.WorkspaceID,
		arg.FieldID,
		arg.Year,
		arg.CumulativeDryTons,
		arg.LastApplicationDate,
	)
	var i PfasFieldLoadingLedger
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FieldID,
		&i.Year,
		&i.CumulativeDryTons,
		&i.LastApplicationDate,
		&i.LastUpdated,
	)
	return i, err
}
