// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coordination.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmCoordinationStep = `-- name: ConfirmCoordinationStep :one
UPDATE pfas.coordination_steps
SET status = 'CONFIRMED', party_id = $4, notes = $3, confirmed_at = now()
WHERE id = $1 AND workspace_id = $2 AND status = 'PENDING'
RETURNING id, workspace_id, workflow_id, party_id, step_role, step_type, status, notes, confirmed_at, created_at
`

type ConfirmCoordinationStepParams struct {
	ID          uuid.UUID     `json:"id"`
	WorkspaceID uuid.UUID     `json:"workspace_id"`
	Notes       string        `json:"notes"`
	PartyID     uuid.NullUUID `json:"party_id"`
}

func (q *Queries) ConfirmCoordinationStep(ctx context.Context, arg ConfirmCoordinationStepParams) (PfasCoordinationStep, error) {
	row := q.db.QueryRow(ctx, confirmCoordinationStep,
		arg.ID,
		arg.WorkspaceID,
		arg.Notes,
		arg.PartyID,
	)
	var i PfasCoordinationStep
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WorkflowID,
		&i.PartyID,
		&i.StepRole,
		&i.StepType,
		&i.Status,
		&i.Notes,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCoordinationDocument = `-- name: CreateCoordinationDocument :one
INSERT INTO pfas.coordination_documents (id, workspace_id, workflow_id, party_id, doc_type, filename, file_hash, mime_type, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, workflow_id, party_id, doc_type, filename, file_hash, mime_type, size_bytes, created_at
`

type CreateCoordinationDocumentParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	WorkflowID  uuid.UUID `json:"workflow_id"`
	PartyID     uuid.UUID `json:"party_id"`
	DocType     string    `json:"doc_type"`
	Filename    string    `json:"filename"`
	FileHash    string    `json:"file_hash"`
	MimeType    string    `json:"mime_type"`
	SizeBytes   int64     `json:"size_bytes"`
}

func (q *Queries) CreateCoordinationDocument(ctx context.Context, arg CreateCoordinationDocumentParams) (PfasCoordinationDocument, error) {
	row := q.db.QueryRow(ctx, createCoordinationDocument,
		arg.ID,
		arg.WorkspaceID,
		arg.WorkflowID,
		arg.PartyID,
		arg.DocType,
		arg.Filename,
		arg.FileHash,
		arg.MimeType,
		arg.SizeBytes,
	)
	var i PfasCoordinationDocument
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WorkflowID,
		&i.PartyID,
		&i.DocType,
		&i.Filename,
		&i.FileHash,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const createCoordinationNotification = `-- name: CreateCoordinationNotification :one
INSERT INTO pfas.coordination_notifications (id, workspace_id, workflow_id, recipient_party_id, event_type, message)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, workflow_id, recipient_party_id, event_type, message, read_at, created_at
`

type CreateCoordinationNotificationParams struct {
	ID               uuid.UUID `json:"id"`
	WorkspaceID      uuid.UUID `json:"workspace_id"`
	WorkflowID       uuid.UUID `json:"workflow_id"`
	RecipientPartyID uuid.UUID `json:"recipient_party_id"`
	EventType        string    `json:"event_type"`
	Message          string    `json:"message"`
}

func (q *Queries) CreateCoordinationNotification(ctx context.Context, arg CreateCoordinationNotificationParams) (PfasCoordinationNotification, error) {
	row := q.db.QueryRow(ctx, createCoordinationNotification,
		arg.ID,
		arg.WorkspaceID,
		arg.WorkflowID,
		arg.RecipientPartyID,
		arg.EventType,
		arg.Message,
	)
	var i PfasCoordinationNotification
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WorkflowID,
		&i.RecipientPartyID,
		&i.EventType,
		&i.Message,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCoordinationStep = `-- name: CreateCoordinationStep :one
INSERT INTO pfas.coordination_steps (id, workspace_id, workflow_id, party_id, step_role, step_type, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, workflow_id, party_id, step_role, step_type, status, notes, confirmed_at, created_at
`

type CreateCoordinationStepParams struct {
	ID          uuid.UUID                `json:"id"`
	WorkspaceID uuid.UUID                `json:"workspace_id"`
	WorkflowID  uuid.UUID                `json:"workflow_id"`
	PartyID     uuid.NullUUID            `json:"party_id"`
	StepRole    PfasCoordinationStepRole `json:"step_role"`
	StepType    string                   `json:"step_type"`
	Status      string                   `json:"status"`
}

func (q *Queries) CreateCoordinationStep(ctx context.Context, arg CreateCoordinationStepParams) (PfasCoordinationStep, error) {
	row := q.db.QueryRow(ctx, createCoordinationStep,
		arg.ID,
		arg.WorkspaceID,
		arg.WorkflowID,
		arg.PartyID,
		arg.StepRole,
		arg.StepType,
		arg.Status,
	)
	var i PfasCoordinationStep
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WorkflowID,
		&i.PartyID,
		&i.StepRole,
		&i.StepType,
		&i.Status,
		&i.Notes,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCoordinationWorkflow = `-- name: CreateCoordinationWorkflow :one
INSERT INTO pfas.coordination_workflows (id, workspace_id, batch_id, field_id, status, created_by_party_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, batch_id, field_id, status, created_by_party_id, created_at, updated_at
`

type CreateCoordinationWorkflowParams struct {
	ID               uuid.UUID              `json:"id"`
	WorkspaceID      uuid.UUID              `json:"workspace_id"`
	BatchID          uuid.NullUUID          `json:"batch_id"`
	FieldID          uuid.NullUUID          `json:"field_id"`
	Status           PfasCoordinationStatus `json:"status"`
	CreatedByPartyID uuid.UUID              `json:"created_by_party_id"`
}

func (q *Queries) CreateCoordinationWorkflow(ctx context.Context, arg CreateCoordinationWorkflowParams) (PfasCoordinationWorkflow, error) {
	row := q.db.QueryRow(ctx, createCoordinationWorkflow,
		arg.ID,
		arg.WorkspaceID,
		arg.BatchID,
		arg.FieldID,
		arg.Status,
		arg.CreatedByPartyID,
	)
	var i PfasCoordinationWorkflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BatchID,
		&i.FieldID,
		&i.Status,
		&i.CreatedByPartyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoordinationStep = `-- name: GetCoordinationStep :one
SELECT s.id, s.workspace_id, s.workflow_id, s.party_id, s.step_role, s.step_type, s.status, s.notes, s.confirmed_at, s.created_at, p.name AS party_name
FROM pfas.coordination_steps s
LEFT JOIN pfas.parties p ON p.id = s.party_id AND p.workspace_id = s.workspace_id
WHERE s.id = $1 AND s.workspace_id = $2
`

type GetCoordinationStepParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetCoordinationStepRow struct {
	ID          uuid.UUID                `json:"id"`
	WorkspaceID uuid.UUID                `json:"workspace_id"`
	WorkflowID  uuid.UUID                `json:"workflow_id"`
	PartyID     uuid.NullUUID            `json:"party_id"`
	StepRole    PfasCoordinationStepRole `json:"step_role"`
	StepType    string                   `json:"step_type"`
	Status      string                   `json:"status"`
	Notes       string                   `json:"notes"`
	ConfirmedAt pgtype.Timestamptz       `json:"confirmed_at"`
	CreatedAt   pgtype.Timestamptz       `json:"created_at"`
	PartyName   *string                  `json:"party_name"`
}

func (q *Queries) GetCoordinationStep(ctx context.Context, arg GetCoordinationStepParams) (GetCoordinationStepRow, error) {
	row := q.db.QueryRow(ctx, getCoordinationStep, arg.ID, arg.WorkspaceID)
	var i GetCoordinationStepRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WorkflowID,
		&i.PartyID,
		&i.StepRole,
		&i.StepType,
		&i.Status,
		&i.Notes,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.PartyName,
	)
	return i, err
}

const getCoordinationWorkflow = `-- name: GetCoordinationWorkflow :one
SELECT w.id, w.workspace_id, w.batch_id, w.field_id, w.status, w.created_by_party_id, w.created_at, w.updated_at,
    cb.name AS created_by_name,
    COALESCE(f.name, '') AS field_name
FROM pfas.coordination_workflows w
JOIN pfas.parties cb ON cb.id = w.created_by_party_id AND cb.workspace_id = w.workspace_id
LEFT JOIN pfas.candidate_fields f ON f.id = w.field_id AND f.workspace_id = w.workspace_id
WHERE w.id = $1 AND w.workspace_id = $2
`

type GetCoordinationWorkflowParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetCoordinationWorkflowRow struct {
	ID               uuid.UUID              `json:"id"`
	WorkspaceID      uuid.UUID              `json:"workspace_id"`
	BatchID          uuid.NullUUID          `json:"batch_id"`
	FieldID          uuid.NullUUID          `json:"field_id"`
	Status           PfasCoordinationStatus `json:"status"`
	CreatedByPartyID uuid.UUID              `json:"created_by_party_id"`
	CreatedAt        pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz     `json:"updated_at"`
	CreatedByName    string                 `json:"created_by_name"`
	FieldName        string                 `json:"field_name"`
}

func (q *Queries) GetCoordinationWorkflow(ctx context.Context, arg GetCoordinationWorkflowParams) (GetCoordinationWorkflowRow, error) {
	row := q.db.QueryRow(ctx, getCoordinationWorkflow, arg.ID, arg.WorkspaceID)
	var i GetCoordinationWorkflowRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BatchID,
		&i.FieldID,
		&i.Status,
		&i.CreatedByPartyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByName,
		&i.FieldName,
	)
	return i, err
}

const listCoordinationDocuments = `-- name: ListCoordinationDocuments :many
SELECT d.id, d.workspace_id, d.workflow_id, d.party_id, d.doc_type, d.filename, d.file_hash, d.mime_type, d.size_bytes, d.created_at, p.name AS party_name
FROM pfas.coordination_documents d
JOIN pfas.parties p ON p.id = d.party_id AND p.workspace_id = d.workspace_id
WHERE d.workflow_id = $1 AND d.workspace_id = $2
ORDER BY d.created_at DESC
`

type ListCoordinationDocumentsParams struct {
	WorkflowID  uuid.UUID `json:"workflow_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type ListCoordinationDocumentsRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	WorkflowID  uuid.UUID          `json:"workflow_id"`
	PartyID     uuid.UUID          `json:"party_id"`
	DocType     string             `json:"doc_type"`
	Filename    string             `json:"filename"`
	FileHash    string             `json:"file_hash"`
	MimeType    string             `json:"mime_type"`
	SizeBytes   int64              `json:"size_bytes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PartyName   string             `json:"party_name"`
}

func (q *Queries) ListCoordinationDocuments(ctx context.Context, arg ListCoordinationDocumentsParams) ([]ListCoordinationDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listCoordinationDocuments, arg.WorkflowID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoordinationDocumentsRow{}
	for rows.Next() {
		var i ListCoordinationDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.WorkflowID,
			&i.PartyID,
			&i.DocType,
			&i.Filename,
			&i.FileHash,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.PartyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoordinationNotifications = `-- name: ListCoordinationNotifications :many
SELECT n.id, n.workspace_id, n.workflow_id, n.recipient_party_id, n.event_type, n.message, n.read_at, n.created_at, p.name AS recipient_name
FROM pfas.coordination_notifications n
JOIN pfas.parties p ON p.id = n.recipient_party_id AND p.workspace_id = n.workspace_id
WHERE n.recipient_party_id = $1 AND n.workspace_id = $2
ORDER BY n.created_at DESC
`

type ListCoordinationNotificationsParams struct {
	RecipientPartyID uuid.UUID `json:"recipient_party_id"`
	WorkspaceID      uuid.UUID `json:"workspace_id"`
}

type ListCoordinationNotificationsRow struct {
	ID               uuid.UUID          `json:"id"`
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	WorkflowID       uuid.UUID          `json:"workflow_id"`
	RecipientPartyID uuid.UUID          `json:"recipient_party_id"`
	EventType        string             `json:"event_type"`
	Message          string             `json:"message"`
	ReadAt           pgtype.Timestamptz `json:"read_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	RecipientName    string             `json:"recipient_name"`
}

func (q *Queries) ListCoordinationNotifications(ctx context.Context, arg ListCoordinationNotificationsParams) ([]ListCoordinationNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listCoordinationNotifications, arg.RecipientPartyID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoordinationNotificationsRow{}
	for rows.Next() {
		var i ListCoordinationNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.WorkflowID,
			&i.RecipientPartyID,
			&i.EventType,
			&i.Message,
			&i.ReadAt,
			&i.CreatedAt,
			&i.RecipientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoordinationSteps = `-- name: ListCoordinationSteps :many
SELECT s.id, s.workspace_id, s.workflow_id, s.party_id, s.step_role, s.step_type, s.status, s.notes, s.confirmed_at, s.created_at, p.name AS party_name, p.email AS party_email
FROM pfas.coordination_steps s
LEFT JOIN pfas.parties p ON p.id = s.party_id AND p.workspace_id = s.workspace_id
WHERE s.workflow_id = $1 AND s.workspace_id = $2
ORDER BY s.step_role, s.created_at
`

type ListCoordinationStepsParams struct {
	WorkflowID  uuid.UUID `json:"workflow_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type ListCoordinationStepsRow struct {
	ID          uuid.UUID                `json:"id"`
	WorkspaceID uuid.UUID                `json:"workspace_id"`
	WorkflowID  uuid.UUID                `json:"workflow_id"`
	PartyID     uuid.NullUUID            `json:"party_id"`
	StepRole    PfasCoordinationStepRole `json:"step_role"`
	StepType    string                   `json:"step_type"`
	Status      string                   `json:"status"`
	Notes       string                   `json:"notes"`
	ConfirmedAt pgtype.Timestamptz       `json:"confirmed_at"`
	CreatedAt   pgtype.Timestamptz       `json:"created_at"`
	PartyName   *string                  `json:"party_name"`
	PartyEmail  *string                  `json:"party_email"`
}

func (q *Queries) ListCoordinationSteps(ctx context.Context, arg ListCoordinationStepsParams) ([]ListCoordinationStepsRow, error) {
	rows, err := q.db.Query(ctx, listCoordinationSteps, arg.WorkflowID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoordinationStepsRow{}
	for rows.Next() {
		var i ListCoordinationStepsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.WorkflowID,
			&i.PartyID,
			&i.StepRole,
			&i.StepType,
			&i.Status,
			&i.Notes,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.PartyName,
			&i.PartyEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoordinationWorkflows = `-- name: ListCoordinationWorkflows :many
SELECT w.id, w.workspace_id, w.batch_id, w.field_id, w.status, w.created_by_party_id, w.created_at, w.updated_at,
    cb.name AS created_by_name,
    COALESCE(f.name, '') AS field_name
FROM pfas.coordination_workflows w
JOIN pfas.parties cb ON cb.id = w.created_by_party_id AND cb.workspace_id = w.workspace_id
LEFT JOIN pfas.candidate_fields f ON f.id = w.field_id AND f.workspace_id = w.workspace_id
WHERE w.workspace_id = $1
ORDER BY w.created_at DESC
`

type ListCoordinationWorkflowsRow struct {
	ID               uuid.UUID              `json:"id"`
	WorkspaceID      uuid.UUID              `json:"workspace_id"`
	BatchID          uuid.NullUUID          `json:"batch_id"`
	FieldID          uuid.NullUUID          `json:"field_id"`
	Status           PfasCoordinationStatus `json:"status"`
	CreatedByPartyID uuid.UUID              `json:"created_by_party_id"`
	CreatedAt        pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz     `json:"updated_at"`
	CreatedByName    string                 `json:"created_by_name"`
	FieldName        string                 `json:"field_name"`
}

func (q *Queries) ListCoordinationWorkflows(ctx context.Context, workspaceID uuid.UUID) ([]ListCoordinationWorkflowsRow, error) {
	rows, err := q.db.Query(ctx, listCoordinationWorkflows, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoordinationWorkflowsRow{}
	for rows.Next() {
		var i ListCoordinationWorkflowsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BatchID,
			&i.FieldID,
			&i.Status,
			&i.CreatedByPartyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByName,
			&i.FieldName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE pfas.coordination_notifications
SET read_at = now()
WHERE id = $1 AND workspace_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.WorkspaceID)
	return err
}

const rejectCoordinationStep = `-- name: RejectCoordinationStep :one
UPDATE pfas.coordination_steps
SET status = 'REJECTED', notes = $3, confirmed_at = now()
WHERE id = $1 AND workspace_id = $2 AND status = 'PENDING'
RETURNING id, workspace_id, workflow_id, party_id, step_role, step_type, status, notes, confirmed_at, created_at
`

type RejectCoordinationStepParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Notes       string    `json:"notes"`
}

func (q *Queries) RejectCoordinationStep(ctx context.Context, arg RejectCoordinationStepParams) (PfasCoordinationStep, error) {
	row := q.db.QueryRow(ctx, rejectCoordinationStep, arg.ID, arg.WorkspaceID, arg.Notes)
	var i PfasCoordinationStep
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WorkflowID,
		&i.PartyID,
		&i.StepRole,
		&i.StepType,
		&i.Status,
		&i.Notes,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateCoordinationWorkflowStatus = `-- name: UpdateCoordinationWorkflowStatus :one
UPDATE pfas.coordination_workflows
SET status = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, batch_id, field_id, status, created_by_party_id, created_at, updated_at
`

type UpdateCoordinationWorkflowStatusParams struct {
	ID          uuid.UUID              `json:"id"`
	WorkspaceID uuid.UUID              `json:"workspace_id"`
	Status      PfasCoordinationStatus `json:"status"`
}

func (q *Queries) UpdateCoordinationWorkflowStatus(ctx context.Context, arg UpdateCoordinationWorkflowStatusParams) (PfasCoordinationWorkflow, error) {
	row := q.db.QueryRow(ctx, updateCoordinationWorkflowStatus, arg.ID, arg.WorkspaceID, arg.Status)
	var i PfasCoordinationWorkflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BatchID,
		&i.FieldID,
		&i.Status,
		&i.CreatedByPartyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
