// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: evidence.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completePhysicalEvaluation = `-- name: CompletePhysicalEvaluation :exec
UPDATE pfas.physical_evaluations
SET status = $2, completed_at = now(), updated_at = now(),
    failure_code = NULL, failure_detail = NULL
WHERE id = $1
`

type CompletePhysicalEvaluationParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) CompletePhysicalEvaluation(ctx context.Context, arg CompletePhysicalEvaluationParams) error {
	_, err := q.db.Exec(ctx, completePhysicalEvaluation, arg.ID, arg.Status)
	return err
}

const createMireyeFetchBatch = `-- name: CreateMireyeFetchBatch :exec
INSERT INTO pfas.mireye_fetch_batches (
    id, evaluation_id, request_hash, response_hash, request_id, source_url,
    http_status, request, response, fetched_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateMireyeFetchBatchParams struct {
	ID           uuid.UUID          `json:"id"`
	EvaluationID uuid.UUID          `json:"evaluation_id"`
	RequestHash  string             `json:"request_hash"`
	ResponseHash string             `json:"response_hash"`
	RequestID    *string            `json:"request_id"`
	SourceUrl    string             `json:"source_url"`
	HttpStatus   int32              `json:"http_status"`
	Request      []byte             `json:"request"`
	Response     []byte             `json:"response"`
	FetchedAt    pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) CreateMireyeFetchBatch(ctx context.Context, arg CreateMireyeFetchBatchParams) error {
	_, err := q.db.Exec(ctx, createMireyeFetchBatch,
		arg.ID,
		arg.EvaluationID,
		arg.RequestHash,
		arg.ResponseHash,
		arg.RequestID,
		arg.SourceUrl,
		arg.HttpStatus,
		arg.Request,
		arg.Response,
		arg.FetchedAt,
	)
	return err
}

const createPhysicalEvaluation = `-- name: CreatePhysicalEvaluation :one
INSERT INTO pfas.physical_evaluations (
    id, workspace_id, field_id, geometry_id, status, field_set_version, aggregation_version
)
VALUES ($1, $2, $3, $4, 'QUEUED', $5, $6)
RETURNING id, workspace_id, field_id, geometry_id, status, field_set_version, aggregation_version, catalog_version, catalog_etag, sample_count, projected_credits, request_hash, failure_code, failure_detail, started_at, completed_at, created_at, updated_at
`

type CreatePhysicalEvaluationParams struct {
	ID                 uuid.UUID `json:"id"`
	WorkspaceID        uuid.UUID `json:"workspace_id"`
	FieldID            uuid.UUID `json:"field_id"`
	GeometryID         uuid.UUID `json:"geometry_id"`
	FieldSetVersion    string    `json:"field_set_version"`
	AggregationVersion string    `json:"aggregation_version"`
}

func (q *Queries) CreatePhysicalEvaluation(ctx context.Context, arg CreatePhysicalEvaluationParams) (PfasPhysicalEvaluation, error) {
	row := q.db.QueryRow(ctx, createPhysicalEvaluation,
		arg.ID,
		arg.WorkspaceID,
		arg.FieldID,
		arg.GeometryID,
		arg.FieldSetVersion,
		arg.AggregationVersion,
	)
	var i PfasPhysicalEvaluation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FieldID,
		&i.GeometryID,
		&i.Status,
		&i.FieldSetVersion,
		&i.AggregationVersion,
		&i.CatalogVersion,
		&i.CatalogEtag,
		&i.SampleCount,
		&i.ProjectedCredits,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureDetail,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePhysicalEvaluationEvidence = `-- name: DeletePhysicalEvaluationEvidence :exec
DELETE FROM pfas.physical_sample_points WHERE evaluation_id = $1
`

func (q *Queries) DeletePhysicalEvaluationEvidence(ctx context.Context, evaluationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePhysicalEvaluationEvidence, evaluationID)
	return err
}

const distanceFromFieldToPointMeters = `-- name: DistanceFromFieldToPointMeters :one
SELECT extensions.ST_Distance(
    geometry.geometry::extensions.geography,
    extensions.ST_SetSRID(
        extensions.ST_MakePoint($1::double precision, $2::double precision),
        4326
    )::extensions.geography
)::double precision AS distance_m
FROM pfas.field_geometry_versions geometry
WHERE geometry.id = $3 AND geometry.field_id = $4
`

type DistanceFromFieldToPointMetersParams struct {
	Longitude  float64   `json:"longitude"`
	Latitude   float64   `json:"latitude"`
	GeometryID uuid.UUID `json:"geometry_id"`
	FieldID    uuid.UUID `json:"field_id"`
}

func (q *Queries) DistanceFromFieldToPointMeters(ctx context.Context, arg DistanceFromFieldToPointMetersParams) (float64, error) {
	row := q.db.QueryRow(ctx, distanceFromFieldToPointMeters,
		arg.Longitude,
		arg.Latitude,
		arg.GeometryID,
		arg.FieldID,
	)
	var distance_m float64
	err := row.Scan(&distance_m)
	return distance_m, err
}

const failPhysicalEvaluation = `-- name: FailPhysicalEvaluation :exec
UPDATE pfas.physical_evaluations
SET status = $2, failure_code = $3, failure_detail = $4,
    completed_at = now(), updated_at = now()
WHERE id = $1
`

type FailPhysicalEvaluationParams struct {
	ID            uuid.UUID `json:"id"`
	Status        string    `json:"status"`
	FailureCode   *string   `json:"failure_code"`
	FailureDetail *string   `json:"failure_detail"`
}

func (q *Queries) FailPhysicalEvaluation(ctx context.Context, arg FailPhysicalEvaluationParams) error {
	_, err := q.db.Exec(ctx, failPhysicalEvaluation,
		arg.ID,
		arg.Status,
		arg.FailureCode,
		arg.FailureDetail,
	)
	return err
}

const generatePhysicalSamplePoints = `-- name: GeneratePhysicalSamplePoints :many
WITH target AS (
    SELECT geometry
    FROM pfas.field_geometry_versions
    WHERE id = $1 AND field_id = $2
), bounds AS (
    SELECT geometry, extensions.ST_XMin(geometry) AS xmin, extensions.ST_XMax(geometry) AS xmax,
           extensions.ST_YMin(geometry) AS ymin, extensions.ST_YMax(geometry) AS ymax
    FROM target
), cells AS (
    SELECT row_number() OVER (ORDER BY y, x)::integer AS ordinal,
           extensions.ST_Intersection(
             geometry,
             extensions.ST_MakeEnvelope(
               xmin + (x * (xmax - xmin) / 2.0),
               ymin + (y * (ymax - ymin) / 2.0),
               xmin + ((x + 1) * (xmax - xmin) / 2.0),
               ymin + ((y + 1) * (ymax - ymin) / 2.0),
               4326
             )
           ) AS part
    FROM bounds CROSS JOIN generate_series(0, 1) AS x CROSS JOIN generate_series(0, 1) AS y
), candidates AS (
    SELECT 0 AS priority, 'Interior anchor'::text AS label,
           extensions.ST_PointOnSurface(geometry) AS point
    FROM target
    UNION ALL
    SELECT ordinal AS priority, 'Area ' || ordinal::text AS label,
           extensions.ST_PointOnSurface(part) AS point
    FROM cells
    WHERE NOT extensions.ST_IsEmpty(part) AND extensions.ST_Area(part::extensions.geography) > 1
), distinct_points AS (
    SELECT DISTINCT ON (extensions.ST_AsBinary(point)) priority, label, point
    FROM candidates
    ORDER BY extensions.ST_AsBinary(point), priority
), ordered AS (
    SELECT row_number() OVER (ORDER BY priority, label)::integer - 1 AS sample_index, label, point
    FROM distinct_points
)
INSERT INTO pfas.physical_sample_points (evaluation_id, sample_index, label, point)
SELECT $3, sample_index, label, point FROM ordered
WHERE sample_index < 5
RETURNING sample_index, label, extensions.ST_Y(point)::double precision AS latitude,
          extensions.ST_X(point)::double precision AS longitude
`

type GeneratePhysicalSamplePointsParams struct {
	ID           uuid.UUID `json:"id"`
	FieldID      uuid.UUID `json:"field_id"`
	EvaluationID uuid.UUID `json:"evaluation_id"`
}

type GeneratePhysicalSamplePointsRow struct {
	SampleIndex int32   `json:"sample_index"`
	Label       string  `json:"label"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
}

func (q *Queries) GeneratePhysicalSamplePoints(ctx context.Context, arg GeneratePhysicalSamplePointsParams) ([]GeneratePhysicalSamplePointsRow, error) {
	rows, err := q.db.Query(ctx, generatePhysicalSamplePoints, arg.ID, arg.FieldID, arg.EvaluationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GeneratePhysicalSamplePointsRow{}
	for rows.Next() {
		var i GeneratePhysicalSamplePointsRow
		if err := rows.Scan(
			&i.SampleIndex,
			&i.Label,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivePhysicalEvaluation = `-- name: GetActivePhysicalEvaluation :one
SELECT id, workspace_id, field_id, geometry_id, status, field_set_version, aggregation_version, catalog_version, catalog_etag, sample_count, projected_credits, request_hash, failure_code, failure_detail, started_at, completed_at, created_at, updated_at FROM pfas.physical_evaluations
WHERE field_id = $1 AND workspace_id = $2 AND status IN ('QUEUED', 'RUNNING')
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetActivePhysicalEvaluationParams struct {
	FieldID     uuid.UUID `json:"field_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetActivePhysicalEvaluation(ctx context.Context, arg GetActivePhysicalEvaluationParams) (PfasPhysicalEvaluation, error) {
	row := q.db.QueryRow(ctx, getActivePhysicalEvaluation, arg.FieldID, arg.WorkspaceID)
	var i PfasPhysicalEvaluation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FieldID,
		&i.GeometryID,
		&i.Status,
		&i.FieldSetVersion,
		&i.AggregationVersion,
		&i.CatalogVersion,
		&i.CatalogEtag,
		&i.SampleCount,
		&i.ProjectedCredits,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureDetail,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFieldGeometryEnvelope = `-- name: GetFieldGeometryEnvelope :one
SELECT extensions.ST_XMin(geometry)::double precision AS min_lng,
       extensions.ST_YMin(geometry)::double precision AS min_lat,
       extensions.ST_XMax(geometry)::double precision AS max_lng,
       extensions.ST_YMax(geometry)::double precision AS max_lat
FROM pfas.field_geometry_versions
WHERE id = $1 AND field_id = $2
`

type GetFieldGeometryEnvelopeParams struct {
	ID      uuid.UUID `json:"id"`
	FieldID uuid.UUID `json:"field_id"`
}

type GetFieldGeometryEnvelopeRow struct {
	MinLng float64 `json:"min_lng"`
	MinLat float64 `json:"min_lat"`
	MaxLng float64 `json:"max_lng"`
	MaxLat float64 `json:"max_lat"`
}

func (q *Queries) GetFieldGeometryEnvelope(ctx context.Context, arg GetFieldGeometryEnvelopeParams) (GetFieldGeometryEnvelopeRow, error) {
	row := q.db.QueryRow(ctx, getFieldGeometryEnvelope, arg.ID, arg.FieldID)
	var i GetFieldGeometryEnvelopeRow
	err := row.Scan(
		&i.MinLng,
		&i.MinLat,
		&i.MaxLng,
		&i.MaxLat,
	)
	return i, err
}

const getLatestPhysicalEvaluation = `-- name: GetLatestPhysicalEvaluation :one
SELECT id, workspace_id, field_id, geometry_id, status, field_set_version, aggregation_version, catalog_version, catalog_etag, sample_count, projected_credits, request_hash, failure_code, failure_detail, started_at, completed_at, created_at, updated_at FROM pfas.physical_evaluations
WHERE field_id = $1 AND workspace_id = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetLatestPhysicalEvaluationParams struct {
	FieldID     uuid.UUID `json:"field_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetLatestPhysicalEvaluation(ctx context.Context, arg GetLatestPhysicalEvaluationParams) (PfasPhysicalEvaluation, error) {
	row := q.db.QueryRow(ctx, getLatestPhysicalEvaluation, arg.FieldID, arg.WorkspaceID)
	var i PfasPhysicalEvaluation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FieldID,
		&i.GeometryID,
		&i.Status,
		&i.FieldSetVersion,
		&i.AggregationVersion,
		&i.CatalogVersion,
		&i.CatalogEtag,
		&i.SampleCount,
		&i.ProjectedCredits,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureDetail,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhysicalEvaluation = `-- name: GetPhysicalEvaluation :one
SELECT id, workspace_id, field_id, geometry_id, status, field_set_version, aggregation_version, catalog_version, catalog_etag, sample_count, projected_credits, request_hash, failure_code, failure_detail, started_at, completed_at, created_at, updated_at FROM pfas.physical_evaluations
WHERE id = $1 AND workspace_id = $2
`

type GetPhysicalEvaluationParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetPhysicalEvaluation(ctx context.Context, arg GetPhysicalEvaluationParams) (PfasPhysicalEvaluation, error) {
	row := q.db.QueryRow(ctx, getPhysicalEvaluation, arg.ID, arg.WorkspaceID)
	var i PfasPhysicalEvaluation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FieldID,
		&i.GeometryID,
		&i.Status,
		&i.FieldSetVersion,
		&i.AggregationVersion,
		&i.CatalogVersion,
		&i.CatalogEtag,
		&i.SampleCount,
		&i.ProjectedCredits,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureDetail,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhysicalEvaluationForWork = `-- name: GetPhysicalEvaluationForWork :one
SELECT evaluation.id, evaluation.workspace_id, evaluation.field_id, evaluation.geometry_id, evaluation.status, evaluation.field_set_version, evaluation.aggregation_version, evaluation.catalog_version, evaluation.catalog_etag, evaluation.sample_count, evaluation.projected_credits, evaluation.request_hash, evaluation.failure_code, evaluation.failure_detail, evaluation.started_at, evaluation.completed_at, evaluation.created_at, evaluation.updated_at, field.status AS field_status, field.name AS field_name,
       facility.name AS facility_name, geometry.version AS geometry_version,
       geometry.geometry_hash,
       extensions.ST_AsGeoJSON(geometry.geometry)::text AS geometry_geojson
FROM pfas.physical_evaluations evaluation
JOIN pfas.candidate_fields field
  ON field.id = evaluation.field_id AND field.workspace_id = evaluation.workspace_id
JOIN pfas.facilities facility
  ON facility.id = field.facility_id AND facility.workspace_id = field.workspace_id
JOIN pfas.field_geometry_versions geometry
  ON geometry.id = evaluation.geometry_id AND geometry.field_id = evaluation.field_id
WHERE evaluation.id = $1
`

type GetPhysicalEvaluationForWorkRow struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	FieldID            uuid.UUID          `json:"field_id"`
	GeometryID         uuid.UUID          `json:"geometry_id"`
	Status             string             `json:"status"`
	FieldSetVersion    string             `json:"field_set_version"`
	AggregationVersion string             `json:"aggregation_version"`
	CatalogVersion     *string            `json:"catalog_version"`
	CatalogEtag        *string            `json:"catalog_etag"`
	SampleCount        int32              `json:"sample_count"`
	ProjectedCredits   int32              `json:"projected_credits"`
	RequestHash        *string            `json:"request_hash"`
	FailureCode        *string            `json:"failure_code"`
	FailureDetail      *string            `json:"failure_detail"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	FieldStatus        string             `json:"field_status"`
	FieldName          string             `json:"field_name"`
	FacilityName       string             `json:"facility_name"`
	GeometryVersion    int32              `json:"geometry_version"`
	GeometryHash       string             `json:"geometry_hash"`
	GeometryGeojson    string             `json:"geometry_geojson"`
}

func (q *Queries) GetPhysicalEvaluationForWork(ctx context.Context, id uuid.UUID) (GetPhysicalEvaluationForWorkRow, error) {
	row := q.db.QueryRow(ctx, getPhysicalEvaluationForWork, id)
	var i GetPhysicalEvaluationForWorkRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FieldID,
		&i.GeometryID,
		&i.Status,
		&i.FieldSetVersion,
		&i.AggregationVersion,
		&i.CatalogVersion,
		&i.CatalogEtag,
		&i.SampleCount,
		&i.ProjectedCredits,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureDetail,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FieldStatus,
		&i.FieldName,
		&i.FacilityName,
		&i.GeometryVersion,
		&i.GeometryHash,
		&i.GeometryGeojson,
	)
	return i, err
}

const listPhysicalDataGaps = `-- name: ListPhysicalDataGaps :many
SELECT evaluation_id, code, source, detail, critical FROM pfas.physical_data_gaps
WHERE evaluation_id = $1
ORDER BY critical DESC, source, code
`

func (q *Queries) ListPhysicalDataGaps(ctx context.Context, evaluationID uuid.UUID) ([]PfasPhysicalDataGap, error) {
	rows, err := q.db.Query(ctx, listPhysicalDataGaps, evaluationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasPhysicalDataGap{}
	for rows.Next() {
		var i PfasPhysicalDataGap
		if err := rows.Scan(
			&i.EvaluationID,
			&i.Code,
			&i.Source,
			&i.Detail,
			&i.Critical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhysicalFieldFacts = `-- name: ListPhysicalFieldFacts :many
SELECT evaluation_id, field_name, category, label, state, aggregate_method, value, unit, source, source_url, fetched_at, ok_count, absent_count, failed_count, sample_indices, critical FROM pfas.physical_field_facts
WHERE evaluation_id = $1
ORDER BY category, field_name
`

func (q *Queries) ListPhysicalFieldFacts(ctx context.Context, evaluationID uuid.UUID) ([]PfasPhysicalFieldFact, error) {
	rows, err := q.db.Query(ctx, listPhysicalFieldFacts, evaluationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasPhysicalFieldFact{}
	for rows.Next() {
		var i PfasPhysicalFieldFact
		if err := rows.Scan(
			&i.EvaluationID,
			&i.FieldName,
			&i.Category,
			&i.Label,
			&i.State,
			&i.AggregateMethod,
			&i.Value,
			&i.Unit,
			&i.Source,
			&i.SourceUrl,
			&i.FetchedAt,
			&i.OkCount,
			&i.AbsentCount,
			&i.FailedCount,
			&i.SampleIndices,
			&i.Critical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhysicalSampleFacts = `-- name: ListPhysicalSampleFacts :many
SELECT fact.evaluation_id, fact.sample_index, point.label AS sample_label,
       extensions.ST_Y(point.point)::double precision AS latitude,
       extensions.ST_X(point.point)::double precision AS longitude,
       fact.field_name, fact.status, fact.value, fact.unit, fact.source,
       fact.source_url, fact.confidence, fact.fetched_at, fact.dataset_vintage,
       fact.ttl_seconds, fact.notes, fact.error, fact.retryable
FROM pfas.physical_sample_facts fact
JOIN pfas.physical_sample_points point
  ON point.evaluation_id = fact.evaluation_id AND point.sample_index = fact.sample_index
WHERE fact.evaluation_id = $1
ORDER BY fact.field_name, fact.sample_index
`

type ListPhysicalSampleFactsRow struct {
	EvaluationID   uuid.UUID          `json:"evaluation_id"`
	SampleIndex    int32              `json:"sample_index"`
	SampleLabel    string             `json:"sample_label"`
	Latitude       float64            `json:"latitude"`
	Longitude      float64            `json:"longitude"`
	FieldName      string             `json:"field_name"`
	Status         string             `json:"status"`
	Value          []byte             `json:"value"`
	Unit           *string            `json:"unit"`
	Source         *string            `json:"source"`
	SourceUrl      *string            `json:"source_url"`
	Confidence     *string            `json:"confidence"`
	FetchedAt      pgtype.Timestamptz `json:"fetched_at"`
	DatasetVintage *string            `json:"dataset_vintage"`
	TtlSeconds     *int32             `json:"ttl_seconds"`
	Notes          *string            `json:"notes"`
	Error          *string            `json:"error"`
	Retryable      bool               `json:"retryable"`
}

func (q *Queries) ListPhysicalSampleFacts(ctx context.Context, evaluationID uuid.UUID) ([]ListPhysicalSampleFactsRow, error) {
	rows, err := q.db.Query(ctx, listPhysicalSampleFacts, evaluationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPhysicalSampleFactsRow{}
	for rows.Next() {
		var i ListPhysicalSampleFactsRow
		if err := rows.Scan(
			&i.EvaluationID,
			&i.SampleIndex,
			&i.SampleLabel,
			&i.Latitude,
			&i.Longitude,
			&i.FieldName,
			&i.Status,
			&i.Value,
			&i.Unit,
			&i.Source,
			&i.SourceUrl,
			&i.Confidence,
			&i.FetchedAt,
			&i.DatasetVintage,
			&i.TtlSeconds,
			&i.Notes,
			&i.Error,
			&i.Retryable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhysicalSamplePoints = `-- name: ListPhysicalSamplePoints :many
SELECT sample_index, label, extensions.ST_Y(point)::double precision AS latitude,
       extensions.ST_X(point)::double precision AS longitude
FROM pfas.physical_sample_points
WHERE evaluation_id = $1
ORDER BY sample_index
`

type ListPhysicalSamplePointsRow struct {
	SampleIndex int32   `json:"sample_index"`
	Label       string  `json:"label"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
}

func (q *Queries) ListPhysicalSamplePoints(ctx context.Context, evaluationID uuid.UUID) ([]ListPhysicalSamplePointsRow, error) {
	rows, err := q.db.Query(ctx, listPhysicalSamplePoints, evaluationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPhysicalSamplePointsRow{}
	for rows.Next() {
		var i ListPhysicalSamplePointsRow
		if err := rows.Scan(
			&i.SampleIndex,
			&i.Label,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplementalEvidence = `-- name: ListSupplementalEvidence :many
SELECT evaluation_id, provider, kind, status, title, summary, value, source_url, source_vintage, fetched_at, caveat FROM pfas.supplemental_evidence
WHERE evaluation_id = $1
ORDER BY provider, kind
`

func (q *Queries) ListSupplementalEvidence(ctx context.Context, evaluationID uuid.UUID) ([]PfasSupplementalEvidence, error) {
	rows, err := q.db.Query(ctx, listSupplementalEvidence, evaluationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasSupplementalEvidence{}
	for rows.Next() {
		var i PfasSupplementalEvidence
		if err := rows.Scan(
			&i.EvaluationID,
			&i.Provider,
			&i.Kind,
			&i.Status,
			&i.Title,
			&i.Summary,
			&i.Value,
			&i.SourceUrl,
			&i.SourceVintage,
			&i.FetchedAt,
			&i.Caveat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPhysicalEvaluationRunning = `-- name: MarkPhysicalEvaluationRunning :exec
UPDATE pfas.physical_evaluations
SET status = 'RUNNING', started_at = COALESCE(started_at, now()), updated_at = now(),
    failure_code = NULL, failure_detail = NULL
WHERE id = $1
`

func (q *Queries) MarkPhysicalEvaluationRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPhysicalEvaluationRunning, id)
	return err
}

const setPhysicalEvaluationGuard = `-- name: SetPhysicalEvaluationGuard :exec
UPDATE pfas.physical_evaluations
SET catalog_version = $2, catalog_etag = $3, sample_count = $4,
    projected_credits = $5, request_hash = $6, updated_at = now()
WHERE id = $1
`

type SetPhysicalEvaluationGuardParams struct {
	ID               uuid.UUID `json:"id"`
	CatalogVersion   *string   `json:"catalog_version"`
	CatalogEtag      *string   `json:"catalog_etag"`
	SampleCount      int32     `json:"sample_count"`
	ProjectedCredits int32     `json:"projected_credits"`
	RequestHash      *string   `json:"request_hash"`
}

func (q *Queries) SetPhysicalEvaluationGuard(ctx context.Context, arg SetPhysicalEvaluationGuardParams) error {
	_, err := q.db.Exec(ctx, setPhysicalEvaluationGuard,
		arg.ID,
		arg.CatalogVersion,
		arg.CatalogEtag,
		arg.SampleCount,
		arg.ProjectedCredits,
		arg.RequestHash,
	)
	return err
}

const upsertPhysicalDataGap = `-- name: UpsertPhysicalDataGap :exec
INSERT INTO pfas.physical_data_gaps (evaluation_id, code, source, detail, critical)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (evaluation_id, code) DO UPDATE
SET source = EXCLUDED.source, detail = EXCLUDED.detail, critical = EXCLUDED.critical
`

type UpsertPhysicalDataGapParams struct {
	EvaluationID uuid.UUID `json:"evaluation_id"`
	Code         string    `json:"code"`
	Source       string    `json:"source"`
	Detail       string    `json:"detail"`
	Critical     bool      `json:"critical"`
}

func (q *Queries) UpsertPhysicalDataGap(ctx context.Context, arg UpsertPhysicalDataGapParams) error {
	_, err := q.db.Exec(ctx, upsertPhysicalDataGap,
		arg.EvaluationID,
		arg.Code,
		arg.Source,
		arg.Detail,
		arg.Critical,
	)
	return err
}

const upsertPhysicalFieldFact = `-- name: UpsertPhysicalFieldFact :exec
INSERT INTO pfas.physical_field_facts (
    evaluation_id, field_name, category, label, state, aggregate_method,
    value, unit, source, source_url, fetched_at, ok_count, absent_count,
    failed_count, sample_indices, critical
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (evaluation_id, field_name) DO UPDATE
SET category = EXCLUDED.category, label = EXCLUDED.label, state = EXCLUDED.state,
    aggregate_method = EXCLUDED.aggregate_method, value = EXCLUDED.value,
    unit = EXCLUDED.unit, source = EXCLUDED.source, source_url = EXCLUDED.source_url,
    fetched_at = EXCLUDED.fetched_at, ok_count = EXCLUDED.ok_count,
    absent_count = EXCLUDED.absent_count, failed_count = EXCLUDED.failed_count,
    sample_indices = EXCLUDED.sample_indices, critical = EXCLUDED.critical
`

type UpsertPhysicalFieldFactParams struct {
	EvaluationID    uuid.UUID          `json:"evaluation_id"`
	FieldName       string             `json:"field_name"`
	Category        string             `json:"category"`
	Label           string             `json:"label"`
	State           string             `json:"state"`
	AggregateMethod string             `json:"aggregate_method"`
	Value           []byte             `json:"value"`
	Unit            *string            `json:"unit"`
	Source          *string            `json:"source"`
	SourceUrl       *string            `json:"source_url"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	OkCount         int32              `json:"ok_count"`
	AbsentCount     int32              `json:"absent_count"`
	FailedCount     int32              `json:"failed_count"`
	SampleIndices   []byte             `json:"sample_indices"`
	Critical        bool               `json:"critical"`
}

func (q *Queries) UpsertPhysicalFieldFact(ctx context.Context, arg UpsertPhysicalFieldFactParams) error {
	_, err := q.db.Exec(ctx, upsertPhysicalFieldFact,
		arg.EvaluationID,
		arg.FieldName,
		arg.Category,
		arg.Label,
		arg.State,
		arg.AggregateMethod,
		arg.Value,
		arg.Unit,
		arg.Source,
		arg.SourceUrl,
		arg.FetchedAt,
		arg.OkCount,
		arg.AbsentCount,
		arg.FailedCount,
		arg.SampleIndices,
		arg.Critical,
	)
	return err
}

const upsertPhysicalSampleFact = `-- name: UpsertPhysicalSampleFact :exec
INSERT INTO pfas.physical_sample_facts (
    evaluation_id, sample_index, field_name, status, value, unit, source,
    source_url, confidence, fetched_at, dataset_vintage, ttl_seconds,
    notes, error, retryable
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (evaluation_id, sample_index, field_name) DO UPDATE
SET status = EXCLUDED.status, value = EXCLUDED.value, unit = EXCLUDED.unit,
    source = EXCLUDED.source, source_url = EXCLUDED.source_url,
    confidence = EXCLUDED.confidence, fetched_at = EXCLUDED.fetched_at,
    dataset_vintage = EXCLUDED.dataset_vintage, ttl_seconds = EXCLUDED.ttl_seconds,
    notes = EXCLUDED.notes, error = EXCLUDED.error, retryable = EXCLUDED.retryable
`

type UpsertPhysicalSampleFactParams struct {
	EvaluationID   uuid.UUID          `json:"evaluation_id"`
	SampleIndex    int32              `json:"sample_index"`
	FieldName      string             `json:"field_name"`
	Status         string             `json:"status"`
	Value          []byte             `json:"value"`
	Unit           *string            `json:"unit"`
	Source         *string            `json:"source"`
	SourceUrl      *string            `json:"source_url"`
	Confidence     *string            `json:"confidence"`
	FetchedAt      pgtype.Timestamptz `json:"fetched_at"`
	DatasetVintage *string            `json:"dataset_vintage"`
	TtlSeconds     *int32             `json:"ttl_seconds"`
	Notes          *string            `json:"notes"`
	Error          *string            `json:"error"`
	Retryable      bool               `json:"retryable"`
}

func (q *Queries) UpsertPhysicalSampleFact(ctx context.Context, arg UpsertPhysicalSampleFactParams) error {
	_, err := q.db.Exec(ctx, upsertPhysicalSampleFact,
		arg.EvaluationID,
		arg.SampleIndex,
		arg.FieldName,
		arg.Status,
		arg.Value,
		arg.Unit,
		arg.Source,
		arg.SourceUrl,
		arg.Confidence,
		arg.FetchedAt,
		arg.DatasetVintage,
		arg.TtlSeconds,
		arg.Notes,
		arg.Error,
		arg.Retryable,
	)
	return err
}

const upsertSupplementalEvidence = `-- name: UpsertSupplementalEvidence :exec
INSERT INTO pfas.supplemental_evidence (
    evaluation_id, provider, kind, status, title, summary, value,
    source_url, source_vintage, fetched_at, caveat
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (evaluation_id, provider, kind) DO UPDATE
SET status = EXCLUDED.status, title = EXCLUDED.title, summary = EXCLUDED.summary,
    value = EXCLUDED.value, source_url = EXCLUDED.source_url,
    source_vintage = EXCLUDED.source_vintage, fetched_at = EXCLUDED.fetched_at,
    caveat = EXCLUDED.caveat
`

type UpsertSupplementalEvidenceParams struct {
	EvaluationID  uuid.UUID          `json:"evaluation_id"`
	Provider      string             `json:"provider"`
	Kind          string             `json:"kind"`
	Status        string             `json:"status"`
	Title         string             `json:"title"`
	Summary       string             `json:"summary"`
	Value         []byte             `json:"value"`
	SourceUrl     string             `json:"source_url"`
	SourceVintage *string            `json:"source_vintage"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
	Caveat        *string            `json:"caveat"`
}

func (q *Queries) UpsertSupplementalEvidence(ctx context.Context, arg UpsertSupplementalEvidenceParams) error {
	_, err := q.db.Exec(ctx, upsertSupplementalEvidence,
		arg.EvaluationID,
		arg.Provider,
		arg.Kind,
		arg.Status,
		arg.Title,
		arg.Summary,
		arg.Value,
		arg.SourceUrl,
		arg.SourceVintage,
		arg.FetchedAt,
		arg.Caveat,
	)
	return err
}
