// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fields.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCandidateField = `-- name: CreateCandidateField :one
INSERT INTO pfas.candidate_fields (
    id, workspace_id, facility_id, name, normalized_name,
    locator_kind, locator_input, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, facility_id, name, normalized_name, locator_kind, locator_input, status, mienviro_site_id, rmp_approved, rmp_document_reference, usable_acres, crop_or_use, agronomic_rate_dry_tons_acre, prior_loading_dry_tons, known_constraints, access_constraints, current_geometry_id, created_at, updated_at
`

type CreateCandidateFieldParams struct {
	ID             uuid.UUID `json:"id"`
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	FacilityID     uuid.UUID `json:"facility_id"`
	Name           string    `json:"name"`
	NormalizedName string    `json:"normalized_name"`
	LocatorKind    string    `json:"locator_kind"`
	LocatorInput   string    `json:"locator_input"`
	Status         string    `json:"status"`
}

func (q *Queries) CreateCandidateField(ctx context.Context, arg CreateCandidateFieldParams) (PfasCandidateField, error) {
	row := q.db.QueryRow(ctx, createCandidateField,
		arg.ID,
		arg.WorkspaceID,
		arg.FacilityID,
		arg.Name,
		arg.NormalizedName,
		arg.LocatorKind,
		arg.LocatorInput,
		arg.Status,
	)
	var i PfasCandidateField
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FacilityID,
		&i.Name,
		&i.NormalizedName,
		&i.LocatorKind,
		&i.LocatorInput,
		&i.Status,
		&i.MienviroSiteID,
		&i.RmpApproved,
		&i.RmpDocumentReference,
		&i.UsableAcres,
		&i.CropOrUse,
		&i.AgronomicRateDryTonsAcre,
		&i.PriorLoadingDryTons,
		&i.KnownConstraints,
		&i.AccessConstraints,
		&i.CurrentGeometryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFieldGeometryVersion = `-- name: CreateFieldGeometryVersion :one
INSERT INTO pfas.field_geometry_versions (
    id, field_id, workspace_id, version, source, source_lookup_id,
    geometry, geometry_hash, area_acres
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    extensions.ST_Multi(extensions.ST_SetSRID(extensions.ST_GeomFromGeoJSON($7), 4326)),
    $8,
    extensions.ST_Area(
        extensions.ST_Multi(extensions.ST_SetSRID(extensions.ST_GeomFromGeoJSON($7), 4326))::extensions.geography
    ) / 4046.8564224
)
RETURNING id, field_id, workspace_id, version, source, source_lookup_id,
          extensions.ST_AsGeoJSON(geometry)::text AS geometry_geojson,
          geometry_hash, CAST(area_acres::text AS text) AS area_acres,
          confirmed_at, created_at
`

type CreateFieldGeometryVersionParams struct {
	ID                uuid.UUID     `json:"id"`
	FieldID           uuid.UUID     `json:"field_id"`
	WorkspaceID       uuid.UUID     `json:"workspace_id"`
	Version           int32         `json:"version"`
	Source            string        `json:"source"`
	SourceLookupID    uuid.NullUUID `json:"source_lookup_id"`
	StGeomfromgeojson interface{}   `json:"st_geomfromgeojson"`
	GeometryHash      string        `json:"geometry_hash"`
}

type CreateFieldGeometryVersionRow struct {
	ID              uuid.UUID          `json:"id"`
	FieldID         uuid.UUID          `json:"field_id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	Version         int32              `json:"version"`
	Source          string             `json:"source"`
	SourceLookupID  uuid.NullUUID      `json:"source_lookup_id"`
	GeometryGeojson string             `json:"geometry_geojson"`
	GeometryHash    string             `json:"geometry_hash"`
	AreaAcres       string             `json:"area_acres"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateFieldGeometryVersion(ctx context.Context, arg CreateFieldGeometryVersionParams) (CreateFieldGeometryVersionRow, error) {
	row := q.db.QueryRow(ctx, createFieldGeometryVersion,
		arg.ID,
		arg.FieldID,
		arg.WorkspaceID,
		arg.Version,
		arg.Source,
		arg.SourceLookupID,
		arg.StGeomfromgeojson,
		arg.GeometryHash,
	)
	var i CreateFieldGeometryVersionRow
	err := row.Scan(
		&i.ID,
		&i.FieldID,
		&i.WorkspaceID,
		&i.Version,
		&i.Source,
		&i.SourceLookupID,
		&i.GeometryGeojson,
		&i.GeometryHash,
		&i.AreaAcres,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createLocationLookup = `-- name: CreateLocationLookup :one
INSERT INTO pfas.field_location_lookups (
    id, field_id, workspace_id, input, input_kind, request_hash, response_hash,
    request_id, source_url, disposition, latitude, longitude, resolved_address,
    state, county, fips, confidence, match_method, parcel_id, parcel_geometry,
    parcel_match_type, parcel_match_distance_m, parcel_source, parcel_unavailable,
    candidates, reason, hint, evidence, fetched_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24,
    $25, $26, $27, $28, $29
)
RETURNING id, field_id, workspace_id, input, input_kind, request_hash, response_hash, request_id, source_url, disposition, latitude, longitude, resolved_address, state, county, fips, confidence, match_method, parcel_id, parcel_geometry, parcel_match_type, parcel_match_distance_m, parcel_source, parcel_unavailable, candidates, reason, hint, evidence, fetched_at, created_at
`

type CreateLocationLookupParams struct {
	ID                   uuid.UUID          `json:"id"`
	FieldID              uuid.UUID          `json:"field_id"`
	WorkspaceID          uuid.UUID          `json:"workspace_id"`
	Input                string             `json:"input"`
	InputKind            string             `json:"input_kind"`
	RequestHash          string             `json:"request_hash"`
	ResponseHash         string             `json:"response_hash"`
	RequestID            *string            `json:"request_id"`
	SourceUrl            string             `json:"source_url"`
	Disposition          string             `json:"disposition"`
	Latitude             pgtype.Numeric     `json:"latitude"`
	Longitude            pgtype.Numeric     `json:"longitude"`
	ResolvedAddress      *string            `json:"resolved_address"`
	State                *string            `json:"state"`
	County               *string            `json:"county"`
	Fips                 *string            `json:"fips"`
	Confidence           pgtype.Numeric     `json:"confidence"`
	MatchMethod          *string            `json:"match_method"`
	ParcelID             *string            `json:"parcel_id"`
	ParcelGeometry       []byte             `json:"parcel_geometry"`
	ParcelMatchType      *string            `json:"parcel_match_type"`
	ParcelMatchDistanceM pgtype.Numeric     `json:"parcel_match_distance_m"`
	ParcelSource         *string            `json:"parcel_source"`
	ParcelUnavailable    bool               `json:"parcel_unavailable"`
	Candidates           []byte             `json:"candidates"`
	Reason               *string            `json:"reason"`
	Hint                 *string            `json:"hint"`
	Evidence             []byte             `json:"evidence"`
	FetchedAt            pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) CreateLocationLookup(ctx context.Context, arg CreateLocationLookupParams) (PfasFieldLocationLookup, error) {
	row := q.db.QueryRow(ctx, createLocationLookup,
		arg.ID,
		arg.FieldID,
		arg.WorkspaceID,
		arg.Input,
		arg.InputKind,
		arg.RequestHash,
		arg.ResponseHash,
		arg.RequestID,
		arg.SourceUrl,
		arg.Disposition,
		arg.Latitude,
		arg.Longitude,
		arg.ResolvedAddress,
		arg.State,
		arg.County,
		arg.Fips,
		arg.Confidence,
		arg.MatchMethod,
		arg.ParcelID,
		arg.ParcelGeometry,
		arg.ParcelMatchType,
		arg.ParcelMatchDistanceM,
		arg.ParcelSource,
		arg.ParcelUnavailable,
		arg.Candidates,
		arg.Reason,
		arg.Hint,
		arg.Evidence,
		arg.FetchedAt,
	)
	var i PfasFieldLocationLookup
	err := row.Scan(
		&i.ID,
		&i.FieldID,
		&i.WorkspaceID,
		&i.Input,
		&i.InputKind,
		&i.RequestHash,
		&i.ResponseHash,
		&i.RequestID,
		&i.SourceUrl,
		&i.Disposition,
		&i.Latitude,
		&i.Longitude,
		&i.ResolvedAddress,
		&i.State,
		&i.County,
		&i.Fips,
		&i.Confidence,
		&i.MatchMethod,
		&i.ParcelID,
		&i.ParcelGeometry,
		&i.ParcelMatchType,
		&i.ParcelMatchDistanceM,
		&i.ParcelSource,
		&i.ParcelUnavailable,
		&i.Candidates,
		&i.Reason,
		&i.Hint,
		&i.Evidence,
		&i.FetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCandidateFieldBase = `-- name: GetCandidateFieldBase :one
SELECT id, workspace_id, facility_id, name, normalized_name, locator_kind, locator_input, status, mienviro_site_id, rmp_approved, rmp_document_reference, usable_acres, crop_or_use, agronomic_rate_dry_tons_acre, prior_loading_dry_tons, known_constraints, access_constraints, current_geometry_id, created_at, updated_at
FROM pfas.candidate_fields
WHERE id = $1 AND workspace_id = $2
`

type GetCandidateFieldBaseParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetCandidateFieldBase(ctx context.Context, arg GetCandidateFieldBaseParams) (PfasCandidateField, error) {
	row := q.db.QueryRow(ctx, getCandidateFieldBase, arg.ID, arg.WorkspaceID)
	var i PfasCandidateField
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FacilityID,
		&i.Name,
		&i.NormalizedName,
		&i.LocatorKind,
		&i.LocatorInput,
		&i.Status,
		&i.MienviroSiteID,
		&i.RmpApproved,
		&i.RmpDocumentReference,
		&i.UsableAcres,
		&i.CropOrUse,
		&i.AgronomicRateDryTonsAcre,
		&i.PriorLoadingDryTons,
		&i.KnownConstraints,
		&i.AccessConstraints,
		&i.CurrentGeometryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCandidateFieldForUpdate = `-- name: GetCandidateFieldForUpdate :one
SELECT id, workspace_id, facility_id, name, normalized_name, locator_kind, locator_input, status, mienviro_site_id, rmp_approved, rmp_document_reference, usable_acres, crop_or_use, agronomic_rate_dry_tons_acre, prior_loading_dry_tons, known_constraints, access_constraints, current_geometry_id, created_at, updated_at
FROM pfas.candidate_fields
WHERE id = $1 AND workspace_id = $2
FOR UPDATE
`

type GetCandidateFieldForUpdateParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetCandidateFieldForUpdate(ctx context.Context, arg GetCandidateFieldForUpdateParams) (PfasCandidateField, error) {
	row := q.db.QueryRow(ctx, getCandidateFieldForUpdate, arg.ID, arg.WorkspaceID)
	var i PfasCandidateField
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FacilityID,
		&i.Name,
		&i.NormalizedName,
		&i.LocatorKind,
		&i.LocatorInput,
		&i.Status,
		&i.MienviroSiteID,
		&i.RmpApproved,
		&i.RmpDocumentReference,
		&i.UsableAcres,
		&i.CropOrUse,
		&i.AgronomicRateDryTonsAcre,
		&i.PriorLoadingDryTons,
		&i.KnownConstraints,
		&i.AccessConstraints,
		&i.CurrentGeometryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCandidateFieldRow = `-- name: GetCandidateFieldRow :one
SELECT f.id, f.facility_id, facility.name AS facility_name, f.name, f.locator_kind,
       f.locator_input, f.status, f.mienviro_site_id, f.rmp_approved,
       f.rmp_document_reference,
       CAST(COALESCE(f.usable_acres::text, '') AS text) AS usable_acres,
       f.crop_or_use,
       CAST(COALESCE(f.agronomic_rate_dry_tons_acre::text, '') AS text) AS agronomic_rate_dry_tons_acre,
       CAST(COALESCE(f.prior_loading_dry_tons::text, '') AS text) AS prior_loading_dry_tons,
       f.known_constraints, f.access_constraints, f.current_geometry_id,
       f.created_at, f.updated_at,
       (lookup.id IS NOT NULL) AS has_lookup,
       CAST(COALESCE(lookup.id::text, '') AS text) AS lookup_id,
       CAST(COALESCE(lookup.disposition, '') AS text) AS lookup_disposition,
       CAST(COALESCE(lookup.latitude::text, '') AS text) AS latitude,
       CAST(COALESCE(lookup.longitude::text, '') AS text) AS longitude,
       lookup.resolved_address, lookup.state, lookup.county, lookup.fips,
       CAST(COALESCE(lookup.confidence::text, '') AS text) AS confidence,
       lookup.match_method, lookup.parcel_id, lookup.parcel_geometry,
       lookup.parcel_match_type,
       CAST(COALESCE(lookup.parcel_match_distance_m::text, '') AS text) AS parcel_match_distance_m,
       lookup.parcel_source, COALESCE(lookup.parcel_unavailable, false) AS parcel_unavailable,
       COALESCE(lookup.candidates, '[]'::jsonb) AS candidates,
       lookup.reason, lookup.hint, lookup.request_id,
       CAST(COALESCE(lookup.source_url, '') AS text) AS source_url,
       CAST(COALESCE(lookup.response_hash, '') AS text) AS response_hash,
       lookup.fetched_at,
       geometry.version AS geometry_version, geometry.source AS geometry_source,
       CAST(COALESCE(extensions.ST_AsGeoJSON(geometry.geometry), '') AS text) AS geometry_geojson,
       CAST(COALESCE(geometry.area_acres::text, '') AS text) AS geometry_area_acres,
       geometry.geometry_hash, geometry.confirmed_at AS geometry_confirmed_at
FROM pfas.candidate_fields f
JOIN pfas.facilities facility
  ON facility.id = f.facility_id AND facility.workspace_id = f.workspace_id
LEFT JOIN LATERAL (
    SELECT l.id, l.field_id, l.workspace_id, l.input, l.input_kind, l.request_hash, l.response_hash, l.request_id, l.source_url, l.disposition, l.latitude, l.longitude, l.resolved_address, l.state, l.county, l.fips, l.confidence, l.match_method, l.parcel_id, l.parcel_geometry, l.parcel_match_type, l.parcel_match_distance_m, l.parcel_source, l.parcel_unavailable, l.candidates, l.reason, l.hint, l.evidence, l.fetched_at, l.created_at FROM pfas.field_location_lookups l
    WHERE l.field_id = f.id
    ORDER BY l.fetched_at DESC, l.id DESC
    LIMIT 1
) lookup ON true
LEFT JOIN pfas.field_geometry_versions geometry
  ON geometry.id = f.current_geometry_id AND geometry.field_id = f.id
WHERE f.id = $1 AND f.workspace_id = $2
`

type GetCandidateFieldRowParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetCandidateFieldRowRow struct {
	ID                       uuid.UUID          `json:"id"`
	FacilityID               uuid.UUID          `json:"facility_id"`
	FacilityName             string             `json:"facility_name"`
	Name                     string             `json:"name"`
	LocatorKind              string             `json:"locator_kind"`
	LocatorInput             string             `json:"locator_input"`
	Status                   string             `json:"status"`
	MienviroSiteID           *string            `json:"mienviro_site_id"`
	RmpApproved              *bool              `json:"rmp_approved"`
	RmpDocumentReference     *string            `json:"rmp_document_reference"`
	UsableAcres              string             `json:"usable_acres"`
	CropOrUse                *string            `json:"crop_or_use"`
	AgronomicRateDryTonsAcre string             `json:"agronomic_rate_dry_tons_acre"`
	PriorLoadingDryTons      string             `json:"prior_loading_dry_tons"`
	KnownConstraints         *string            `json:"known_constraints"`
	AccessConstraints        *string            `json:"access_constraints"`
	CurrentGeometryID        uuid.NullUUID      `json:"current_geometry_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	HasLookup                interface{}        `json:"has_lookup"`
	LookupID                 string             `json:"lookup_id"`
	LookupDisposition        string             `json:"lookup_disposition"`
	Latitude                 string             `json:"latitude"`
	Longitude                string             `json:"longitude"`
	ResolvedAddress          *string            `json:"resolved_address"`
	State                    *string            `json:"state"`
	County                   *string            `json:"county"`
	Fips                     *string            `json:"fips"`
	Confidence               string             `json:"confidence"`
	MatchMethod              *string            `json:"match_method"`
	ParcelID                 *string            `json:"parcel_id"`
	ParcelGeometry           []byte             `json:"parcel_geometry"`
	ParcelMatchType          *string            `json:"parcel_match_type"`
	ParcelMatchDistanceM     string             `json:"parcel_match_distance_m"`
	ParcelSource             *string            `json:"parcel_source"`
	ParcelUnavailable        bool               `json:"parcel_unavailable"`
	Candidates               []byte             `json:"candidates"`
	Reason                   *string            `json:"reason"`
	Hint                     *string            `json:"hint"`
	RequestID                *string            `json:"request_id"`
	SourceUrl                string             `json:"source_url"`
	ResponseHash             string             `json:"response_hash"`
	FetchedAt                pgtype.Timestamptz `json:"fetched_at"`
	GeometryVersion          *int32             `json:"geometry_version"`
	GeometrySource           *string            `json:"geometry_source"`
	GeometryGeojson          string             `json:"geometry_geojson"`
	GeometryAreaAcres        string             `json:"geometry_area_acres"`
	GeometryHash             *string            `json:"geometry_hash"`
	GeometryConfirmedAt      pgtype.Timestamptz `json:"geometry_confirmed_at"`
}

func (q *Queries) GetCandidateFieldRow(ctx context.Context, arg GetCandidateFieldRowParams) (GetCandidateFieldRowRow, error) {
	row := q.db.QueryRow(ctx, getCandidateFieldRow, arg.ID, arg.WorkspaceID)
	var i GetCandidateFieldRowRow
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.FacilityName,
		&i.Name,
		&i.LocatorKind,
		&i.LocatorInput,
		&i.Status,
		&i.MienviroSiteID,
		&i.RmpApproved,
		&i.RmpDocumentReference,
		&i.UsableAcres,
		&i.CropOrUse,
		&i.AgronomicRateDryTonsAcre,
		&i.PriorLoadingDryTons,
		&i.KnownConstraints,
		&i.AccessConstraints,
		&i.CurrentGeometryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasLookup,
		&i.LookupID,
		&i.LookupDisposition,
		&i.Latitude,
		&i.Longitude,
		&i.ResolvedAddress,
		&i.State,
		&i.County,
		&i.Fips,
		&i.Confidence,
		&i.MatchMethod,
		&i.ParcelID,
		&i.ParcelGeometry,
		&i.ParcelMatchType,
		&i.ParcelMatchDistanceM,
		&i.ParcelSource,
		&i.ParcelUnavailable,
		&i.Candidates,
		&i.Reason,
		&i.Hint,
		&i.RequestID,
		&i.SourceUrl,
		&i.ResponseHash,
		&i.FetchedAt,
		&i.GeometryVersion,
		&i.GeometrySource,
		&i.GeometryGeojson,
		&i.GeometryAreaAcres,
		&i.GeometryHash,
		&i.GeometryConfirmedAt,
	)
	return i, err
}

const getFacilityForWorkspace = `-- name: GetFacilityForWorkspace :one
SELECT id, name, jurisdiction
FROM pfas.facilities
WHERE id = $1 AND workspace_id = $2
`

type GetFacilityForWorkspaceParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetFacilityForWorkspaceRow struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Jurisdiction string    `json:"jurisdiction"`
}

func (q *Queries) GetFacilityForWorkspace(ctx context.Context, arg GetFacilityForWorkspaceParams) (GetFacilityForWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getFacilityForWorkspace, arg.ID, arg.WorkspaceID)
	var i GetFacilityForWorkspaceRow
	err := row.Scan(&i.ID, &i.Name, &i.Jurisdiction)
	return i, err
}

const getFieldGeometryByHash = `-- name: GetFieldGeometryByHash :one
SELECT id, field_id, workspace_id, version, source, source_lookup_id,
       extensions.ST_AsGeoJSON(geometry)::text AS geometry_geojson,
       geometry_hash, CAST(area_acres::text AS text) AS area_acres,
       confirmed_at, created_at
FROM pfas.field_geometry_versions
WHERE field_id = $1 AND geometry_hash = $2
`

type GetFieldGeometryByHashParams struct {
	FieldID      uuid.UUID `json:"field_id"`
	GeometryHash string    `json:"geometry_hash"`
}

type GetFieldGeometryByHashRow struct {
	ID              uuid.UUID          `json:"id"`
	FieldID         uuid.UUID          `json:"field_id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	Version         int32              `json:"version"`
	Source          string             `json:"source"`
	SourceLookupID  uuid.NullUUID      `json:"source_lookup_id"`
	GeometryGeojson string             `json:"geometry_geojson"`
	GeometryHash    string             `json:"geometry_hash"`
	AreaAcres       string             `json:"area_acres"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetFieldGeometryByHash(ctx context.Context, arg GetFieldGeometryByHashParams) (GetFieldGeometryByHashRow, error) {
	row := q.db.QueryRow(ctx, getFieldGeometryByHash, arg.FieldID, arg.GeometryHash)
	var i GetFieldGeometryByHashRow
	err := row.Scan(
		&i.ID,
		&i.FieldID,
		&i.WorkspaceID,
		&i.Version,
		&i.Source,
		&i.SourceLookupID,
		&i.GeometryGeojson,
		&i.GeometryHash,
		&i.AreaAcres,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestLocationLookup = `-- name: GetLatestLocationLookup :one
SELECT id, field_id, workspace_id, input, input_kind, request_hash, response_hash, request_id, source_url, disposition, latitude, longitude, resolved_address, state, county, fips, confidence, match_method, parcel_id, parcel_geometry, parcel_match_type, parcel_match_distance_m, parcel_source, parcel_unavailable, candidates, reason, hint, evidence, fetched_at, created_at FROM pfas.field_location_lookups
WHERE field_id = $1
ORDER BY fetched_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestLocationLookup(ctx context.Context, fieldID uuid.UUID) (PfasFieldLocationLookup, error) {
	row := q.db.QueryRow(ctx, getLatestLocationLookup, fieldID)
	var i PfasFieldLocationLookup
	err := row.Scan(
		&i.ID,
		&i.FieldID,
		&i.WorkspaceID,
		&i.Input,
		&i.InputKind,
		&i.RequestHash,
		&i.ResponseHash,
		&i.RequestID,
		&i.SourceUrl,
		&i.Disposition,
		&i.Latitude,
		&i.Longitude,
		&i.ResolvedAddress,
		&i.State,
		&i.County,
		&i.Fips,
		&i.Confidence,
		&i.MatchMethod,
		&i.ParcelID,
		&i.ParcelGeometry,
		&i.ParcelMatchType,
		&i.ParcelMatchDistanceM,
		&i.ParcelSource,
		&i.ParcelUnavailable,
		&i.Candidates,
		&i.Reason,
		&i.Hint,
		&i.Evidence,
		&i.FetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLocationLookupByRequestHash = `-- name: GetLocationLookupByRequestHash :one
SELECT id, field_id, workspace_id, input, input_kind, request_hash, response_hash, request_id, source_url, disposition, latitude, longitude, resolved_address, state, county, fips, confidence, match_method, parcel_id, parcel_geometry, parcel_match_type, parcel_match_distance_m, parcel_source, parcel_unavailable, candidates, reason, hint, evidence, fetched_at, created_at FROM pfas.field_location_lookups
WHERE field_id = $1 AND request_hash = $2
`

type GetLocationLookupByRequestHashParams struct {
	FieldID     uuid.UUID `json:"field_id"`
	RequestHash string    `json:"request_hash"`
}

func (q *Queries) GetLocationLookupByRequestHash(ctx context.Context, arg GetLocationLookupByRequestHashParams) (PfasFieldLocationLookup, error) {
	row := q.db.QueryRow(ctx, getLocationLookupByRequestHash, arg.FieldID, arg.RequestHash)
	var i PfasFieldLocationLookup
	err := row.Scan(
		&i.ID,
		&i.FieldID,
		&i.WorkspaceID,
		&i.Input,
		&i.InputKind,
		&i.RequestHash,
		&i.ResponseHash,
		&i.RequestID,
		&i.SourceUrl,
		&i.Disposition,
		&i.Latitude,
		&i.Longitude,
		&i.ResolvedAddress,
		&i.State,
		&i.County,
		&i.Fips,
		&i.Confidence,
		&i.MatchMethod,
		&i.ParcelID,
		&i.ParcelGeometry,
		&i.ParcelMatchType,
		&i.ParcelMatchDistanceM,
		&i.ParcelSource,
		&i.ParcelUnavailable,
		&i.Candidates,
		&i.Reason,
		&i.Hint,
		&i.Evidence,
		&i.FetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCandidateFieldRows = `-- name: ListCandidateFieldRows :many
SELECT f.id, f.facility_id, facility.name AS facility_name, f.name, f.locator_kind,
       f.locator_input, f.status, f.mienviro_site_id, f.rmp_approved,
       f.rmp_document_reference,
       CAST(COALESCE(f.usable_acres::text, '') AS text) AS usable_acres,
       f.crop_or_use,
       CAST(COALESCE(f.agronomic_rate_dry_tons_acre::text, '') AS text) AS agronomic_rate_dry_tons_acre,
       CAST(COALESCE(f.prior_loading_dry_tons::text, '') AS text) AS prior_loading_dry_tons,
       f.known_constraints, f.access_constraints, f.current_geometry_id,
       f.created_at, f.updated_at,
       (lookup.id IS NOT NULL) AS has_lookup,
       CAST(COALESCE(lookup.id::text, '') AS text) AS lookup_id,
       CAST(COALESCE(lookup.disposition, '') AS text) AS lookup_disposition,
       CAST(COALESCE(lookup.latitude::text, '') AS text) AS latitude,
       CAST(COALESCE(lookup.longitude::text, '') AS text) AS longitude,
       lookup.resolved_address, lookup.state, lookup.county, lookup.fips,
       CAST(COALESCE(lookup.confidence::text, '') AS text) AS confidence,
       lookup.match_method, lookup.parcel_id, lookup.parcel_geometry,
       lookup.parcel_match_type,
       CAST(COALESCE(lookup.parcel_match_distance_m::text, '') AS text) AS parcel_match_distance_m,
       lookup.parcel_source, COALESCE(lookup.parcel_unavailable, false) AS parcel_unavailable,
       COALESCE(lookup.candidates, '[]'::jsonb) AS candidates,
       lookup.reason, lookup.hint, lookup.request_id,
       CAST(COALESCE(lookup.source_url, '') AS text) AS source_url,
       CAST(COALESCE(lookup.response_hash, '') AS text) AS response_hash,
       lookup.fetched_at,
       geometry.version AS geometry_version, geometry.source AS geometry_source,
       CAST(COALESCE(extensions.ST_AsGeoJSON(geometry.geometry), '') AS text) AS geometry_geojson,
       CAST(COALESCE(geometry.area_acres::text, '') AS text) AS geometry_area_acres,
       geometry.geometry_hash, geometry.confirmed_at AS geometry_confirmed_at
FROM pfas.candidate_fields f
JOIN pfas.facilities facility
  ON facility.id = f.facility_id AND facility.workspace_id = f.workspace_id
LEFT JOIN LATERAL (
    SELECT l.id, l.field_id, l.workspace_id, l.input, l.input_kind, l.request_hash, l.response_hash, l.request_id, l.source_url, l.disposition, l.latitude, l.longitude, l.resolved_address, l.state, l.county, l.fips, l.confidence, l.match_method, l.parcel_id, l.parcel_geometry, l.parcel_match_type, l.parcel_match_distance_m, l.parcel_source, l.parcel_unavailable, l.candidates, l.reason, l.hint, l.evidence, l.fetched_at, l.created_at FROM pfas.field_location_lookups l
    WHERE l.field_id = f.id
    ORDER BY l.fetched_at DESC, l.id DESC
    LIMIT 1
) lookup ON true
LEFT JOIN pfas.field_geometry_versions geometry
  ON geometry.id = f.current_geometry_id AND geometry.field_id = f.id
WHERE f.workspace_id = $1
  AND ($2::uuid IS NULL OR f.facility_id = $2)
  AND ($3::uuid IS NULL OR f.id = $3)
ORDER BY f.created_at DESC, f.id
`

type ListCandidateFieldRowsParams struct {
	WorkspaceID uuid.UUID     `json:"workspace_id"`
	FacilityID  uuid.NullUUID `json:"facility_id"`
	FieldID     uuid.NullUUID `json:"field_id"`
}

type ListCandidateFieldRowsRow struct {
	ID                       uuid.UUID          `json:"id"`
	FacilityID               uuid.UUID          `json:"facility_id"`
	FacilityName             string             `json:"facility_name"`
	Name                     string             `json:"name"`
	LocatorKind              string             `json:"locator_kind"`
	LocatorInput             string             `json:"locator_input"`
	Status                   string             `json:"status"`
	MienviroSiteID           *string            `json:"mienviro_site_id"`
	RmpApproved              *bool              `json:"rmp_approved"`
	RmpDocumentReference     *string            `json:"rmp_document_reference"`
	UsableAcres              string             `json:"usable_acres"`
	CropOrUse                *string            `json:"crop_or_use"`
	AgronomicRateDryTonsAcre string             `json:"agronomic_rate_dry_tons_acre"`
	PriorLoadingDryTons      string             `json:"prior_loading_dry_tons"`
	KnownConstraints         *string            `json:"known_constraints"`
	AccessConstraints        *string            `json:"access_constraints"`
	CurrentGeometryID        uuid.NullUUID      `json:"current_geometry_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	HasLookup                interface{}        `json:"has_lookup"`
	LookupID                 string             `json:"lookup_id"`
	LookupDisposition        string             `json:"lookup_disposition"`
	Latitude                 string             `json:"latitude"`
	Longitude                string             `json:"longitude"`
	ResolvedAddress          *string            `json:"resolved_address"`
	State                    *string            `json:"state"`
	County                   *string            `json:"county"`
	Fips                     *string            `json:"fips"`
	Confidence               string             `json:"confidence"`
	MatchMethod              *string            `json:"match_method"`
	ParcelID                 *string            `json:"parcel_id"`
	ParcelGeometry           []byte             `json:"parcel_geometry"`
	ParcelMatchType          *string            `json:"parcel_match_type"`
	ParcelMatchDistanceM     string             `json:"parcel_match_distance_m"`
	ParcelSource             *string            `json:"parcel_source"`
	ParcelUnavailable        bool               `json:"parcel_unavailable"`
	Candidates               []byte             `json:"candidates"`
	Reason                   *string            `json:"reason"`
	Hint                     *string            `json:"hint"`
	RequestID                *string            `json:"request_id"`
	SourceUrl                string             `json:"source_url"`
	ResponseHash             string             `json:"response_hash"`
	FetchedAt                pgtype.Timestamptz `json:"fetched_at"`
	GeometryVersion          *int32             `json:"geometry_version"`
	GeometrySource           *string            `json:"geometry_source"`
	GeometryGeojson          string             `json:"geometry_geojson"`
	GeometryAreaAcres        string             `json:"geometry_area_acres"`
	GeometryHash             *string            `json:"geometry_hash"`
	GeometryConfirmedAt      pgtype.Timestamptz `json:"geometry_confirmed_at"`
}

func (q *Queries) ListCandidateFieldRows(ctx context.Context, arg ListCandidateFieldRowsParams) ([]ListCandidateFieldRowsRow, error) {
	rows, err := q.db.Query(ctx, listCandidateFieldRows, arg.WorkspaceID, arg.FacilityID, arg.FieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCandidateFieldRowsRow{}
	for rows.Next() {
		var i ListCandidateFieldRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.FacilityName,
			&i.Name,
			&i.LocatorKind,
			&i.LocatorInput,
			&i.Status,
			&i.MienviroSiteID,
			&i.RmpApproved,
			&i.RmpDocumentReference,
			&i.UsableAcres,
			&i.CropOrUse,
			&i.AgronomicRateDryTonsAcre,
			&i.PriorLoadingDryTons,
			&i.KnownConstraints,
			&i.AccessConstraints,
			&i.CurrentGeometryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasLookup,
			&i.LookupID,
			&i.LookupDisposition,
			&i.Latitude,
			&i.Longitude,
			&i.ResolvedAddress,
			&i.State,
			&i.County,
			&i.Fips,
			&i.Confidence,
			&i.MatchMethod,
			&i.ParcelID,
			&i.ParcelGeometry,
			&i.ParcelMatchType,
			&i.ParcelMatchDistanceM,
			&i.ParcelSource,
			&i.ParcelUnavailable,
			&i.Candidates,
			&i.Reason,
			&i.Hint,
			&i.RequestID,
			&i.SourceUrl,
			&i.ResponseHash,
			&i.FetchedAt,
			&i.GeometryVersion,
			&i.GeometrySource,
			&i.GeometryGeojson,
			&i.GeometryAreaAcres,
			&i.GeometryHash,
			&i.GeometryConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenFieldGaps = `-- name: ListOpenFieldGaps :many
SELECT id, code, detail, resolution, created_at
FROM pfas.field_data_gaps
WHERE field_id = $1 AND status = 'OPEN'
ORDER BY created_at, code
`

type ListOpenFieldGapsRow struct {
	ID         uuid.UUID          `json:"id"`
	Code       string             `json:"code"`
	Detail     string             `json:"detail"`
	Resolution string             `json:"resolution"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOpenFieldGaps(ctx context.Context, fieldID uuid.UUID) ([]ListOpenFieldGapsRow, error) {
	rows, err := q.db.Query(ctx, listOpenFieldGaps, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenFieldGapsRow{}
	for rows.Next() {
		var i ListOpenFieldGapsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Detail,
			&i.Resolution,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenFieldGapsForWorkspace = `-- name: ListOpenFieldGapsForWorkspace :many
SELECT gap.id, gap.field_id, gap.code, gap.detail, gap.resolution, gap.created_at
FROM pfas.field_data_gaps gap
JOIN pfas.candidate_fields field ON field.id = gap.field_id
WHERE field.workspace_id = $1 AND gap.status = 'OPEN'
ORDER BY gap.field_id, gap.created_at, gap.code
`

type ListOpenFieldGapsForWorkspaceRow struct {
	ID         uuid.UUID          `json:"id"`
	FieldID    uuid.UUID          `json:"field_id"`
	Code       string             `json:"code"`
	Detail     string             `json:"detail"`
	Resolution string             `json:"resolution"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOpenFieldGapsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListOpenFieldGapsForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listOpenFieldGapsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenFieldGapsForWorkspaceRow{}
	for rows.Next() {
		var i ListOpenFieldGapsForWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.Code,
			&i.Detail,
			&i.Resolution,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextFieldGeometryVersion = `-- name: NextFieldGeometryVersion :one
SELECT COALESCE(MAX(version), 0)::integer + 1
FROM pfas.field_geometry_versions
WHERE field_id = $1
`

func (q *Queries) NextFieldGeometryVersion(ctx context.Context, fieldID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextFieldGeometryVersion, fieldID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const openFieldGap = `-- name: OpenFieldGap :exec
INSERT INTO pfas.field_data_gaps (id, field_id, code, detail, resolution, status)
VALUES ($1, $2, $3, $4, $5, 'OPEN')
ON CONFLICT (field_id, code) DO UPDATE
SET detail = EXCLUDED.detail,
    resolution = EXCLUDED.resolution,
    status = 'OPEN',
    resolved_at = NULL
`

type OpenFieldGapParams struct {
	ID         uuid.UUID `json:"id"`
	FieldID    uuid.UUID `json:"field_id"`
	Code       string    `json:"code"`
	Detail     string    `json:"detail"`
	Resolution string    `json:"resolution"`
}

func (q *Queries) OpenFieldGap(ctx context.Context, arg OpenFieldGapParams) error {
	_, err := q.db.Exec(ctx, openFieldGap,
		arg.ID,
		arg.FieldID,
		arg.Code,
		arg.Detail,
		arg.Resolution,
	)
	return err
}

const resolveFieldGap = `-- name: ResolveFieldGap :exec
UPDATE pfas.field_data_gaps
SET status = 'RESOLVED', resolved_at = now()
WHERE field_id = $1 AND code = $2 AND status = 'OPEN'
`

type ResolveFieldGapParams struct {
	FieldID uuid.UUID `json:"field_id"`
	Code    string    `json:"code"`
}

func (q *Queries) ResolveFieldGap(ctx context.Context, arg ResolveFieldGapParams) error {
	_, err := q.db.Exec(ctx, resolveFieldGap, arg.FieldID, arg.Code)
	return err
}

const setCandidateFieldGeometry = `-- name: SetCandidateFieldGeometry :exec
UPDATE pfas.candidate_fields
SET current_geometry_id = $2, updated_at = now()
WHERE id = $1 AND workspace_id = $3
`

type SetCandidateFieldGeometryParams struct {
	ID                uuid.UUID     `json:"id"`
	CurrentGeometryID uuid.NullUUID `json:"current_geometry_id"`
	WorkspaceID       uuid.UUID     `json:"workspace_id"`
}

func (q *Queries) SetCandidateFieldGeometry(ctx context.Context, arg SetCandidateFieldGeometryParams) error {
	_, err := q.db.Exec(ctx, setCandidateFieldGeometry, arg.ID, arg.CurrentGeometryID, arg.WorkspaceID)
	return err
}

const setCandidateFieldStatus = `-- name: SetCandidateFieldStatus :exec
UPDATE pfas.candidate_fields
SET status = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2
`

type SetCandidateFieldStatusParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Status      string    `json:"status"`
}

func (q *Queries) SetCandidateFieldStatus(ctx context.Context, arg SetCandidateFieldStatusParams) error {
	_, err := q.db.Exec(ctx, setCandidateFieldStatus, arg.ID, arg.WorkspaceID, arg.Status)
	return err
}

const updateCandidateFieldDetails = `-- name: UpdateCandidateFieldDetails :execrows
UPDATE pfas.candidate_fields
SET mienviro_site_id = $3,
    rmp_approved = $4,
    rmp_document_reference = $5,
    usable_acres = $6,
    crop_or_use = $7,
    agronomic_rate_dry_tons_acre = $8,
    prior_loading_dry_tons = $9,
    known_constraints = $10,
    access_constraints = $11,
    updated_at = now()
WHERE id = $1 AND workspace_id = $2
`

type UpdateCandidateFieldDetailsParams struct {
	ID                       uuid.UUID      `json:"id"`
	WorkspaceID              uuid.UUID      `json:"workspace_id"`
	MienviroSiteID           *string        `json:"mienviro_site_id"`
	RmpApproved              *bool          `json:"rmp_approved"`
	RmpDocumentReference     *string        `json:"rmp_document_reference"`
	UsableAcres              pgtype.Numeric `json:"usable_acres"`
	CropOrUse                *string        `json:"crop_or_use"`
	AgronomicRateDryTonsAcre pgtype.Numeric `json:"agronomic_rate_dry_tons_acre"`
	PriorLoadingDryTons      pgtype.Numeric `json:"prior_loading_dry_tons"`
	KnownConstraints         *string        `json:"known_constraints"`
	AccessConstraints        *string        `json:"access_constraints"`
}

func (q *Queries) UpdateCandidateFieldDetails(ctx context.Context, arg UpdateCandidateFieldDetailsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCandidateFieldDetails,
		arg.ID,
		arg.WorkspaceID,
		arg.MienviroSiteID,
		arg.RmpApproved,
		arg.RmpDocumentReference,
		arg.UsableAcres,
		arg.CropOrUse,
		arg.AgronomicRateDryTonsAcre,
		arg.PriorLoadingDryTons,
		arg.KnownConstraints,
		arg.AccessConstraints,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const validateFieldGeometry = `-- name: ValidateFieldGeometry :one
WITH candidate AS (
    SELECT extensions.ST_Multi(
        extensions.ST_SetSRID(extensions.ST_GeomFromGeoJSON($1), 4326)
    ) AS geometry
)
SELECT CAST(extensions.ST_IsValid(geometry) AS boolean) AS is_valid,
       CAST(extensions.ST_IsValidReason(geometry) AS text) AS reason,
       CAST(NOT extensions.ST_IsEmpty(geometry) AS boolean) AS has_area,
       CAST(extensions.GeometryType(geometry) AS text) AS geometry_type
FROM candidate
`

type ValidateFieldGeometryRow struct {
	IsValid      bool   `json:"is_valid"`
	Reason       string `json:"reason"`
	HasArea      bool   `json:"has_area"`
	GeometryType string `json:"geometry_type"`
}

func (q *Queries) ValidateFieldGeometry(ctx context.Context, geojson interface{}) (ValidateFieldGeometryRow, error) {
	row := q.db.QueryRow(ctx, validateFieldGeometry, geojson)
	var i ValidateFieldGeometryRow
	err := row.Scan(
		&i.IsValid,
		&i.Reason,
		&i.HasArea,
		&i.GeometryType,
	)
	return i, err
}
