// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: judge_demo.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJudgeDemoRun = `-- name: CreateJudgeDemoRun :one
INSERT INTO pfas.judge_demo_runs (
    id, idempotency_key, status, fixture_version, record, decision_hash, package_artifact, created_at, completed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, idempotency_key, status, fixture_version, record, decision_hash, created_at, completed_at, package_artifact
`

type CreateJudgeDemoRunParams struct {
	ID              uuid.UUID          `json:"id"`
	IdempotencyKey  string             `json:"idempotency_key"`
	Status          string             `json:"status"`
	FixtureVersion  string             `json:"fixture_version"`
	Record          []byte             `json:"record"`
	DecisionHash    string             `json:"decision_hash"`
	PackageArtifact []byte             `json:"package_artifact"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateJudgeDemoRun(ctx context.Context, arg CreateJudgeDemoRunParams) (PfasJudgeDemoRun, error) {
	row := q.db.QueryRow(ctx, createJudgeDemoRun,
		arg.ID,
		arg.IdempotencyKey,
		arg.Status,
		arg.FixtureVersion,
		arg.Record,
		arg.DecisionHash,
		arg.PackageArtifact,
		arg.CreatedAt,
		arg.CompletedAt,
	)
	var i PfasJudgeDemoRun
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Status,
		&i.FixtureVersion,
		&i.Record,
		&i.DecisionHash,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.PackageArtifact,
	)
	return i, err
}

const getJudgeDemoRun = `-- name: GetJudgeDemoRun :one
SELECT id, idempotency_key, status, fixture_version, record, decision_hash, created_at, completed_at, package_artifact FROM pfas.judge_demo_runs WHERE id = $1
`

func (q *Queries) GetJudgeDemoRun(ctx context.Context, id uuid.UUID) (PfasJudgeDemoRun, error) {
	row := q.db.QueryRow(ctx, getJudgeDemoRun, id)
	var i PfasJudgeDemoRun
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Status,
		&i.FixtureVersion,
		&i.Record,
		&i.DecisionHash,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.PackageArtifact,
	)
	return i, err
}

const getJudgeDemoRunByIdempotencyKey = `-- name: GetJudgeDemoRunByIdempotencyKey :one
SELECT id, idempotency_key, status, fixture_version, record, decision_hash, created_at, completed_at, package_artifact FROM pfas.judge_demo_runs WHERE idempotency_key = $1
`

func (q *Queries) GetJudgeDemoRunByIdempotencyKey(ctx context.Context, idempotencyKey string) (PfasJudgeDemoRun, error) {
	row := q.db.QueryRow(ctx, getJudgeDemoRunByIdempotencyKey, idempotencyKey)
	var i PfasJudgeDemoRun
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Status,
		&i.FixtureVersion,
		&i.Record,
		&i.DecisionHash,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.PackageArtifact,
	)
	return i, err
}
