// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lab.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeLabReportExtraction = `-- name: CompleteLabReportExtraction :exec
UPDATE pfas.lab_reports
SET status = $2, current_version = $3, failure_code = NULL, updated_at = now()
WHERE id = $1
`

type CompleteLabReportExtractionParams struct {
	ID             uuid.UUID `json:"id"`
	Status         string    `json:"status"`
	CurrentVersion int32     `json:"current_version"`
}

func (q *Queries) CompleteLabReportExtraction(ctx context.Context, arg CompleteLabReportExtractionParams) error {
	_, err := q.db.Exec(ctx, completeLabReportExtraction, arg.ID, arg.Status, arg.CurrentVersion)
	return err
}

const confirmLabReport = `-- name: ConfirmLabReport :exec
UPDATE pfas.lab_reports
SET status = 'CONFIRMED', confirmed_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) ConfirmLabReport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmLabReport, id)
	return err
}

const confirmLabReportVersion = `-- name: ConfirmLabReportVersion :execrows
UPDATE pfas.lab_report_versions
SET status = 'CONFIRMED', confirmed_at = now()
WHERE id = $1 AND status = 'DRAFT'
`

func (q *Queries) ConfirmLabReportVersion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, confirmLabReportVersion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAnalyteResult = `-- name: CreateAnalyteResult :one
INSERT INTO pfas.analyte_results (
    id, report_id, version_id, canonical_analyte, reported_analyte,
    result_text, value, unit, basis, qualifier, is_non_detect,
    reporting_limit, detection_limit, normalized_value_ug_kg_dry,
    normalized_reporting_limit_ug_kg_dry, normalized_detection_limit_ug_kg_dry,
    source_page, source_excerpt, source_bounds
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16,
    $17, $18, $19
)
RETURNING id, report_id, version_id, canonical_analyte, reported_analyte, result_text, value, unit, basis, qualifier, is_non_detect, reporting_limit, detection_limit, normalized_value_ug_kg_dry, normalized_reporting_limit_ug_kg_dry, normalized_detection_limit_ug_kg_dry, source_page, source_excerpt, source_bounds, created_at
`

type CreateAnalyteResultParams struct {
	ID                              uuid.UUID      `json:"id"`
	ReportID                        uuid.UUID      `json:"report_id"`
	VersionID                       uuid.UUID      `json:"version_id"`
	CanonicalAnalyte                string         `json:"canonical_analyte"`
	ReportedAnalyte                 string         `json:"reported_analyte"`
	ResultText                      string         `json:"result_text"`
	Value                           pgtype.Numeric `json:"value"`
	Unit                            *string        `json:"unit"`
	Basis                           *string        `json:"basis"`
	Qualifier                       *string        `json:"qualifier"`
	IsNonDetect                     bool           `json:"is_non_detect"`
	ReportingLimit                  pgtype.Numeric `json:"reporting_limit"`
	DetectionLimit                  pgtype.Numeric `json:"detection_limit"`
	NormalizedValueUgKgDry          pgtype.Numeric `json:"normalized_value_ug_kg_dry"`
	NormalizedReportingLimitUgKgDry pgtype.Numeric `json:"normalized_reporting_limit_ug_kg_dry"`
	NormalizedDetectionLimitUgKgDry pgtype.Numeric `json:"normalized_detection_limit_ug_kg_dry"`
	SourcePage                      int32          `json:"source_page"`
	SourceExcerpt                   string         `json:"source_excerpt"`
	SourceBounds                    []byte         `json:"source_bounds"`
}

func (q *Queries) CreateAnalyteResult(ctx context.Context, arg CreateAnalyteResultParams) (PfasAnalyteResult, error) {
	row := q.db.QueryRow(ctx, createAnalyteResult,
		arg.ID,
		arg.ReportID,
		arg.VersionID,
		arg.CanonicalAnalyte,
		arg.ReportedAnalyte,
		arg.ResultText,
		arg.Value,
		arg.Unit,
		arg.Basis,
		arg.Qualifier,
		arg.IsNonDetect,
		arg.ReportingLimit,
		arg.DetectionLimit,
		arg.NormalizedValueUgKgDry,
		arg.NormalizedReportingLimitUgKgDry,
		arg.NormalizedDetectionLimitUgKgDry,
		arg.SourcePage,
		arg.SourceExcerpt,
		arg.SourceBounds,
	)
	var i PfasAnalyteResult
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.VersionID,
		&i.CanonicalAnalyte,
		&i.ReportedAnalyte,
		&i.ResultText,
		&i.Value,
		&i.Unit,
		&i.Basis,
		&i.Qualifier,
		&i.IsNonDetect,
		&i.ReportingLimit,
		&i.DetectionLimit,
		&i.NormalizedValueUgKgDry,
		&i.NormalizedReportingLimitUgKgDry,
		&i.NormalizedDetectionLimitUgKgDry,
		&i.SourcePage,
		&i.SourceExcerpt,
		&i.SourceBounds,
		&i.CreatedAt,
	)
	return i, err
}

const createLabConfirmation = `-- name: CreateLabConfirmation :one
INSERT INTO pfas.lab_confirmations (
    id, workspace_id, report_id, version_id, evidence_hash
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, report_id, version_id, evidence_hash, confirmed_at
`

type CreateLabConfirmationParams struct {
	ID           uuid.UUID `json:"id"`
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	ReportID     uuid.UUID `json:"report_id"`
	VersionID    uuid.UUID `json:"version_id"`
	EvidenceHash string    `json:"evidence_hash"`
}

func (q *Queries) CreateLabConfirmation(ctx context.Context, arg CreateLabConfirmationParams) (PfasLabConfirmation, error) {
	row := q.db.QueryRow(ctx, createLabConfirmation,
		arg.ID,
		arg.WorkspaceID,
		arg.ReportID,
		arg.VersionID,
		arg.EvidenceHash,
	)
	var i PfasLabConfirmation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ReportID,
		&i.VersionID,
		&i.EvidenceHash,
		&i.ConfirmedAt,
	)
	return i, err
}

const createLabReport = `-- name: CreateLabReport :one
INSERT INTO pfas.lab_reports (
    id, workspace_id, facility_id, batch_id, original_filename,
    media_type, size_bytes, sha256, content, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'UPLOADED')
ON CONFLICT (workspace_id, sha256) DO NOTHING
RETURNING id, workspace_id, facility_id, batch_id, original_filename, media_type, size_bytes, sha256, content, status, current_version, failure_code, created_at, updated_at, confirmed_at
`

type CreateLabReportParams struct {
	ID               uuid.UUID `json:"id"`
	WorkspaceID      uuid.UUID `json:"workspace_id"`
	FacilityID       uuid.UUID `json:"facility_id"`
	BatchID          uuid.UUID `json:"batch_id"`
	OriginalFilename string    `json:"original_filename"`
	MediaType        string    `json:"media_type"`
	SizeBytes        int32     `json:"size_bytes"`
	Sha256           string    `json:"sha256"`
	Content          []byte    `json:"content"`
}

func (q *Queries) CreateLabReport(ctx context.Context, arg CreateLabReportParams) (PfasLabReport, error) {
	row := q.db.QueryRow(ctx, createLabReport,
		arg.ID,
		arg.WorkspaceID,
		arg.FacilityID,
		arg.BatchID,
		arg.OriginalFilename,
		arg.MediaType,
		arg.SizeBytes,
		arg.Sha256,
		arg.Content,
	)
	var i PfasLabReport
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FacilityID,
		&i.BatchID,
		&i.OriginalFilename,
		&i.MediaType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Content,
		&i.Status,
		&i.CurrentVersion,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const createLabReportGap = `-- name: CreateLabReportGap :one
INSERT INTO pfas.lab_report_gaps (
    id, report_id, version_id, code, field_name, detail, resolution, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'OPEN')
RETURNING id, report_id, version_id, code, field_name, detail, resolution, status, created_at, resolved_at
`

type CreateLabReportGapParams struct {
	ID         uuid.UUID `json:"id"`
	ReportID   uuid.UUID `json:"report_id"`
	VersionID  uuid.UUID `json:"version_id"`
	Code       string    `json:"code"`
	FieldName  string    `json:"field_name"`
	Detail     string    `json:"detail"`
	Resolution string    `json:"resolution"`
}

func (q *Queries) CreateLabReportGap(ctx context.Context, arg CreateLabReportGapParams) (PfasLabReportGap, error) {
	row := q.db.QueryRow(ctx, createLabReportGap,
		arg.ID,
		arg.ReportID,
		arg.VersionID,
		arg.Code,
		arg.FieldName,
		arg.Detail,
		arg.Resolution,
	)
	var i PfasLabReportGap
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.VersionID,
		&i.Code,
		&i.FieldName,
		&i.Detail,
		&i.Resolution,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const createLabReportVersion = `-- name: CreateLabReportVersion :one
INSERT INTO pfas.lab_report_versions (
    id, report_id, version, status, source, laboratory, sample_identifier,
    collection_date, matrix, method, basis
)
VALUES ($1, $2, $3, 'DRAFT', $4, $5, $6, $7, $8, $9, $10)
RETURNING id, report_id, version, status, source, laboratory, sample_identifier, collection_date, matrix, method, basis, created_at, confirmed_at
`

type CreateLabReportVersionParams struct {
	ID               uuid.UUID   `json:"id"`
	ReportID         uuid.UUID   `json:"report_id"`
	Version          int32       `json:"version"`
	Source           string      `json:"source"`
	Laboratory       *string     `json:"laboratory"`
	SampleIdentifier *string     `json:"sample_identifier"`
	CollectionDate   pgtype.Date `json:"collection_date"`
	Matrix           *string     `json:"matrix"`
	Method           *string     `json:"method"`
	Basis            *string     `json:"basis"`
}

func (q *Queries) CreateLabReportVersion(ctx context.Context, arg CreateLabReportVersionParams) (PfasLabReportVersion, error) {
	row := q.db.QueryRow(ctx, createLabReportVersion,
		arg.ID,
		arg.ReportID,
		arg.Version,
		arg.Source,
		arg.Laboratory,
		arg.SampleIdentifier,
		arg.CollectionDate,
		arg.Matrix,
		arg.Method,
		arg.Basis,
	)
	var i PfasLabReportVersion
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.Version,
		&i.Status,
		&i.Source,
		&i.Laboratory,
		&i.SampleIdentifier,
		&i.CollectionDate,
		&i.Matrix,
		&i.Method,
		&i.Basis,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const deleteLabReportPages = `-- name: DeleteLabReportPages :exec
DELETE FROM pfas.lab_report_pages WHERE report_id = $1
`

func (q *Queries) DeleteLabReportPages(ctx context.Context, reportID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLabReportPages, reportID)
	return err
}

const failLabReport = `-- name: FailLabReport :exec
UPDATE pfas.lab_reports
SET status = 'FAILED', failure_code = $2, updated_at = now()
WHERE id = $1 AND status <> 'CONFIRMED'
`

type FailLabReportParams struct {
	ID          uuid.UUID `json:"id"`
	FailureCode *string   `json:"failure_code"`
}

func (q *Queries) FailLabReport(ctx context.Context, arg FailLabReportParams) error {
	_, err := q.db.Exec(ctx, failLabReport, arg.ID, arg.FailureCode)
	return err
}

const getCurrentLabReportVersion = `-- name: GetCurrentLabReportVersion :one
SELECT id, report_id, version, status, source, laboratory, sample_identifier,
       CAST(COALESCE(collection_date::text, '') AS text) AS collection_date,
       matrix, method, basis,
       created_at, confirmed_at
FROM pfas.lab_report_versions
WHERE report_id = $1 AND version = $2
`

type GetCurrentLabReportVersionParams struct {
	ReportID uuid.UUID `json:"report_id"`
	Version  int32     `json:"version"`
}

type GetCurrentLabReportVersionRow struct {
	ID               uuid.UUID          `json:"id"`
	ReportID         uuid.UUID          `json:"report_id"`
	Version          int32              `json:"version"`
	Status           string             `json:"status"`
	Source           string             `json:"source"`
	Laboratory       *string            `json:"laboratory"`
	SampleIdentifier *string            `json:"sample_identifier"`
	CollectionDate   string             `json:"collection_date"`
	Matrix           *string            `json:"matrix"`
	Method           *string            `json:"method"`
	Basis            *string            `json:"basis"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
}

func (q *Queries) GetCurrentLabReportVersion(ctx context.Context, arg GetCurrentLabReportVersionParams) (GetCurrentLabReportVersionRow, error) {
	row := q.db.QueryRow(ctx, getCurrentLabReportVersion, arg.ReportID, arg.Version)
	var i GetCurrentLabReportVersionRow
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.Version,
		&i.Status,
		&i.Source,
		&i.Laboratory,
		&i.SampleIdentifier,
		&i.CollectionDate,
		&i.Matrix,
		&i.Method,
		&i.Basis,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getLabReportByHash = `-- name: GetLabReportByHash :one
SELECT id, workspace_id, facility_id, batch_id, original_filename, media_type, size_bytes, sha256, content, status, current_version, failure_code, created_at, updated_at, confirmed_at FROM pfas.lab_reports
WHERE workspace_id = $1 AND sha256 = $2
`

type GetLabReportByHashParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Sha256      string    `json:"sha256"`
}

func (q *Queries) GetLabReportByHash(ctx context.Context, arg GetLabReportByHashParams) (PfasLabReport, error) {
	row := q.db.QueryRow(ctx, getLabReportByHash, arg.WorkspaceID, arg.Sha256)
	var i PfasLabReport
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FacilityID,
		&i.BatchID,
		&i.OriginalFilename,
		&i.MediaType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Content,
		&i.Status,
		&i.CurrentVersion,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getLabReportContent = `-- name: GetLabReportContent :one
SELECT original_filename, media_type, content
FROM pfas.lab_reports
WHERE id = $1 AND workspace_id = $2
`

type GetLabReportContentParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetLabReportContentRow struct {
	OriginalFilename string `json:"original_filename"`
	MediaType        string `json:"media_type"`
	Content          []byte `json:"content"`
}

func (q *Queries) GetLabReportContent(ctx context.Context, arg GetLabReportContentParams) (GetLabReportContentRow, error) {
	row := q.db.QueryRow(ctx, getLabReportContent, arg.ID, arg.WorkspaceID)
	var i GetLabReportContentRow
	err := row.Scan(&i.OriginalFilename, &i.MediaType, &i.Content)
	return i, err
}

const getLabReportForProcessing = `-- name: GetLabReportForProcessing :one
SELECT r.id, r.workspace_id, r.facility_id, r.batch_id, r.original_filename, r.media_type, r.size_bytes, r.sha256, r.content, r.status, r.current_version, r.failure_code, r.created_at, r.updated_at, r.confirmed_at, CAST(COALESCE(b.percent_solids::text, '') AS text) AS percent_solids
FROM pfas.lab_reports r
JOIN pfas.biosolids_batches b ON b.id = r.batch_id AND b.workspace_id = r.workspace_id
WHERE r.id = $1
FOR UPDATE OF r
`

type GetLabReportForProcessingRow struct {
	ID               uuid.UUID          `json:"id"`
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	FacilityID       uuid.UUID          `json:"facility_id"`
	BatchID          uuid.UUID          `json:"batch_id"`
	OriginalFilename string             `json:"original_filename"`
	MediaType        string             `json:"media_type"`
	SizeBytes        int32              `json:"size_bytes"`
	Sha256           string             `json:"sha256"`
	Content          []byte             `json:"content"`
	Status           string             `json:"status"`
	CurrentVersion   int32              `json:"current_version"`
	FailureCode      *string            `json:"failure_code"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
	PercentSolids    string             `json:"percent_solids"`
}

func (q *Queries) GetLabReportForProcessing(ctx context.Context, id uuid.UUID) (GetLabReportForProcessingRow, error) {
	row := q.db.QueryRow(ctx, getLabReportForProcessing, id)
	var i GetLabReportForProcessingRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FacilityID,
		&i.BatchID,
		&i.OriginalFilename,
		&i.MediaType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Content,
		&i.Status,
		&i.CurrentVersion,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedAt,
		&i.PercentSolids,
	)
	return i, err
}

const getLabReportForWorkspace = `-- name: GetLabReportForWorkspace :one
SELECT r.id, r.status, r.original_filename, r.media_type, r.size_bytes, r.sha256,
       r.current_version, r.failure_code, r.created_at, r.updated_at, r.confirmed_at,
       f.id AS facility_id, f.name AS facility_name, f.jurisdiction,
       b.id AS batch_id, b.identifier AS batch_identifier,
       CAST(COALESCE(b.wet_mass_kg::text, '') AS text) AS wet_mass_kg,
       CAST(COALESCE(b.percent_solids::text, '') AS text) AS percent_solids
FROM pfas.lab_reports r
JOIN pfas.facilities f ON f.id = r.facility_id AND f.workspace_id = r.workspace_id
JOIN pfas.biosolids_batches b ON b.id = r.batch_id AND b.workspace_id = r.workspace_id
WHERE r.id = $1 AND r.workspace_id = $2
`

type GetLabReportForWorkspaceParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetLabReportForWorkspaceRow struct {
	ID               uuid.UUID          `json:"id"`
	Status           string             `json:"status"`
	OriginalFilename string             `json:"original_filename"`
	MediaType        string             `json:"media_type"`
	SizeBytes        int32              `json:"size_bytes"`
	Sha256           string             `json:"sha256"`
	CurrentVersion   int32              `json:"current_version"`
	FailureCode      *string            `json:"failure_code"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
	FacilityID       uuid.UUID          `json:"facility_id"`
	FacilityName     string             `json:"facility_name"`
	Jurisdiction     string             `json:"jurisdiction"`
	BatchID          uuid.UUID          `json:"batch_id"`
	BatchIdentifier  string             `json:"batch_identifier"`
	WetMassKg        string             `json:"wet_mass_kg"`
	PercentSolids    string             `json:"percent_solids"`
}

func (q *Queries) GetLabReportForWorkspace(ctx context.Context, arg GetLabReportForWorkspaceParams) (GetLabReportForWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getLabReportForWorkspace, arg.ID, arg.WorkspaceID)
	var i GetLabReportForWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.OriginalFilename,
		&i.MediaType,
		&i.SizeBytes,
		&i.Sha256,
		&i.CurrentVersion,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedAt,
		&i.FacilityID,
		&i.FacilityName,
		&i.Jurisdiction,
		&i.BatchID,
		&i.BatchIdentifier,
		&i.WetMassKg,
		&i.PercentSolids,
	)
	return i, err
}

const getWorkspaceByHash = `-- name: GetWorkspaceByHash :one
SELECT id, key_hash, created_at, last_seen_at FROM pfas.workspaces WHERE key_hash = $1
`

func (q *Queries) GetWorkspaceByHash(ctx context.Context, keyHash string) (PfasWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByHash, keyHash)
	var i PfasWorkspace
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listAnalytesForVersion = `-- name: ListAnalytesForVersion :many
SELECT id, canonical_analyte, reported_analyte, result_text,
       CAST(COALESCE(value::text, '') AS text) AS value,
       unit, basis, qualifier, is_non_detect,
       CAST(COALESCE(reporting_limit::text, '') AS text) AS reporting_limit,
       CAST(COALESCE(detection_limit::text, '') AS text) AS detection_limit,
       CAST(COALESCE(normalized_value_ug_kg_dry::text, '') AS text) AS normalized_value_ug_kg_dry,
       CAST(COALESCE(normalized_reporting_limit_ug_kg_dry::text, '') AS text) AS normalized_reporting_limit_ug_kg_dry,
       CAST(COALESCE(normalized_detection_limit_ug_kg_dry::text, '') AS text) AS normalized_detection_limit_ug_kg_dry,
       source_page, source_excerpt, source_bounds
FROM pfas.analyte_results
WHERE version_id = $1
ORDER BY canonical_analyte DESC
`

type ListAnalytesForVersionRow struct {
	ID                              uuid.UUID `json:"id"`
	CanonicalAnalyte                string    `json:"canonical_analyte"`
	ReportedAnalyte                 string    `json:"reported_analyte"`
	ResultText                      string    `json:"result_text"`
	Value                           string    `json:"value"`
	Unit                            *string   `json:"unit"`
	Basis                           *string   `json:"basis"`
	Qualifier                       *string   `json:"qualifier"`
	IsNonDetect                     bool      `json:"is_non_detect"`
	ReportingLimit                  string    `json:"reporting_limit"`
	DetectionLimit                  string    `json:"detection_limit"`
	NormalizedValueUgKgDry          string    `json:"normalized_value_ug_kg_dry"`
	NormalizedReportingLimitUgKgDry string    `json:"normalized_reporting_limit_ug_kg_dry"`
	NormalizedDetectionLimitUgKgDry string    `json:"normalized_detection_limit_ug_kg_dry"`
	SourcePage                      int32     `json:"source_page"`
	SourceExcerpt                   string    `json:"source_excerpt"`
	SourceBounds                    []byte    `json:"source_bounds"`
}

func (q *Queries) ListAnalytesForVersion(ctx context.Context, versionID uuid.UUID) ([]ListAnalytesForVersionRow, error) {
	rows, err := q.db.Query(ctx, listAnalytesForVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalytesForVersionRow{}
	for rows.Next() {
		var i ListAnalytesForVersionRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalAnalyte,
			&i.ReportedAnalyte,
			&i.ResultText,
			&i.Value,
			&i.Unit,
			&i.Basis,
			&i.Qualifier,
			&i.IsNonDetect,
			&i.ReportingLimit,
			&i.DetectionLimit,
			&i.NormalizedValueUgKgDry,
			&i.NormalizedReportingLimitUgKgDry,
			&i.NormalizedDetectionLimitUgKgDry,
			&i.SourcePage,
			&i.SourceExcerpt,
			&i.SourceBounds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBatchesForWorkspace = `-- name: ListBatchesForWorkspace :many
SELECT b.id, b.identifier, CAST(COALESCE(b.wet_mass_kg::text, '') AS text) AS wet_mass_kg,
       CAST(COALESCE(b.percent_solids::text, '') AS text) AS percent_solids, b.facility_id,
       f.name AS facility_name, f.jurisdiction
FROM pfas.biosolids_batches b
JOIN pfas.facilities f ON f.id = b.facility_id AND f.workspace_id = b.workspace_id
WHERE b.workspace_id = $1
ORDER BY b.created_at DESC, b.id
`

type ListBatchesForWorkspaceRow struct {
	ID            uuid.UUID `json:"id"`
	Identifier    string    `json:"identifier"`
	WetMassKg     string    `json:"wet_mass_kg"`
	PercentSolids string    `json:"percent_solids"`
	FacilityID    uuid.UUID `json:"facility_id"`
	FacilityName  string    `json:"facility_name"`
	Jurisdiction  string    `json:"jurisdiction"`
}

func (q *Queries) ListBatchesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListBatchesForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listBatchesForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBatchesForWorkspaceRow{}
	for rows.Next() {
		var i ListBatchesForWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.WetMassKg,
			&i.PercentSolids,
			&i.FacilityID,
			&i.FacilityName,
			&i.Jurisdiction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacilitiesForWorkspace = `-- name: ListFacilitiesForWorkspace :many
SELECT id, name, jurisdiction
FROM pfas.facilities
WHERE workspace_id = $1
ORDER BY name, id
`

type ListFacilitiesForWorkspaceRow struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Jurisdiction string    `json:"jurisdiction"`
}

func (q *Queries) ListFacilitiesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListFacilitiesForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listFacilitiesForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFacilitiesForWorkspaceRow{}
	for rows.Next() {
		var i ListFacilitiesForWorkspaceRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Jurisdiction); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGapsForVersion = `-- name: ListGapsForVersion :many
SELECT id, code, field_name, detail, resolution, status, created_at, resolved_at
FROM pfas.lab_report_gaps
WHERE version_id = $1
ORDER BY created_at, code
`

type ListGapsForVersionRow struct {
	ID         uuid.UUID          `json:"id"`
	Code       string             `json:"code"`
	FieldName  string             `json:"field_name"`
	Detail     string             `json:"detail"`
	Resolution string             `json:"resolution"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) ListGapsForVersion(ctx context.Context, versionID uuid.UUID) ([]ListGapsForVersionRow, error) {
	rows, err := q.db.Query(ctx, listGapsForVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGapsForVersionRow{}
	for rows.Next() {
		var i ListGapsForVersionRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.FieldName,
			&i.Detail,
			&i.Resolution,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabReportPages = `-- name: ListLabReportPages :many
SELECT page_number, extracted_text, extraction_method, read_error,
       CAST(COALESCE(width::text, '') AS text) AS width,
       CAST(COALESCE(height::text, '') AS text) AS height
FROM pfas.lab_report_pages
WHERE report_id = $1
ORDER BY page_number
`

type ListLabReportPagesRow struct {
	PageNumber       int32   `json:"page_number"`
	ExtractedText    string  `json:"extracted_text"`
	ExtractionMethod string  `json:"extraction_method"`
	ReadError        *string `json:"read_error"`
	Width            string  `json:"width"`
	Height           string  `json:"height"`
}

func (q *Queries) ListLabReportPages(ctx context.Context, reportID uuid.UUID) ([]ListLabReportPagesRow, error) {
	rows, err := q.db.Query(ctx, listLabReportPages, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabReportPagesRow{}
	for rows.Next() {
		var i ListLabReportPagesRow
		if err := rows.Scan(
			&i.PageNumber,
			&i.ExtractedText,
			&i.ExtractionMethod,
			&i.ReadError,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLabReportProcessing = `-- name: MarkLabReportProcessing :execrows
UPDATE pfas.lab_reports
SET status = 'PROCESSING', failure_code = NULL, updated_at = now()
WHERE id = $1 AND status IN ('UPLOADED', 'PROCESSING')
`

func (q *Queries) MarkLabReportProcessing(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markLabReportProcessing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryFailedLabReport = `-- name: RetryFailedLabReport :execrows
UPDATE pfas.lab_reports
SET status = 'UPLOADED', failure_code = NULL, updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND status = 'FAILED'
`

type RetryFailedLabReportParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) RetryFailedLabReport(ctx context.Context, arg RetryFailedLabReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryFailedLabReport, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeCurrentLabReportVersion = `-- name: SupersedeCurrentLabReportVersion :exec
UPDATE pfas.lab_report_versions
SET status = 'SUPERSEDED'
WHERE report_id = $1 AND version = $2 AND status IN ('DRAFT', 'CONFIRMED')
`

type SupersedeCurrentLabReportVersionParams struct {
	ReportID uuid.UUID `json:"report_id"`
	Version  int32     `json:"version"`
}

func (q *Queries) SupersedeCurrentLabReportVersion(ctx context.Context, arg SupersedeCurrentLabReportVersionParams) error {
	_, err := q.db.Exec(ctx, supersedeCurrentLabReportVersion, arg.ReportID, arg.Version)
	return err
}

const upsertBatch = `-- name: UpsertBatch :one
INSERT INTO pfas.biosolids_batches (
    id, workspace_id, facility_id, identifier, normalized_identifier,
    wet_mass_kg, percent_solids
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (facility_id, normalized_identifier) DO UPDATE
SET identifier = EXCLUDED.identifier,
    wet_mass_kg = COALESCE(EXCLUDED.wet_mass_kg, pfas.biosolids_batches.wet_mass_kg),
    percent_solids = COALESCE(EXCLUDED.percent_solids, pfas.biosolids_batches.percent_solids),
    updated_at = now()
RETURNING id, workspace_id, facility_id, identifier, normalized_identifier, wet_mass_kg, percent_solids, created_at, updated_at
`

type UpsertBatchParams struct {
	ID                   uuid.UUID      `json:"id"`
	WorkspaceID          uuid.UUID      `json:"workspace_id"`
	FacilityID           uuid.UUID      `json:"facility_id"`
	Identifier           string         `json:"identifier"`
	NormalizedIdentifier string         `json:"normalized_identifier"`
	WetMassKg            pgtype.Numeric `json:"wet_mass_kg"`
	PercentSolids        pgtype.Numeric `json:"percent_solids"`
}

func (q *Queries) UpsertBatch(ctx context.Context, arg UpsertBatchParams) (PfasBiosolidsBatch, error) {
	row := q.db.QueryRow(ctx, upsertBatch,
		arg.ID,
		arg.WorkspaceID,
		arg.FacilityID,
		arg.Identifier,
		arg.NormalizedIdentifier,
		arg.WetMassKg,
		arg.PercentSolids,
	)
	var i PfasBiosolidsBatch
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FacilityID,
		&i.Identifier,
		&i.NormalizedIdentifier,
		&i.WetMassKg,
		&i.PercentSolids,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFacility = `-- name: UpsertFacility :one
INSERT INTO pfas.facilities (id, workspace_id, name, normalized_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, normalized_name) DO UPDATE
SET name = EXCLUDED.name, updated_at = now()
RETURNING id, workspace_id, name, normalized_name, jurisdiction, created_at, updated_at
`

type UpsertFacilityParams struct {
	ID             uuid.UUID `json:"id"`
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	Name           string    `json:"name"`
	NormalizedName string    `json:"normalized_name"`
}

func (q *Queries) UpsertFacility(ctx context.Context, arg UpsertFacilityParams) (PfasFacility, error) {
	row := q.db.QueryRow(ctx, upsertFacility,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.NormalizedName,
	)
	var i PfasFacility
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.NormalizedName,
		&i.Jurisdiction,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLabReportPage = `-- name: UpsertLabReportPage :exec
INSERT INTO pfas.lab_report_pages (
    report_id, page_number, extracted_text, extraction_method, read_error, width, height
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (report_id, page_number) DO UPDATE
SET extracted_text = EXCLUDED.extracted_text,
    extraction_method = EXCLUDED.extraction_method,
    read_error = EXCLUDED.read_error,
    width = EXCLUDED.width,
    height = EXCLUDED.height
`

type UpsertLabReportPageParams struct {
	ReportID         uuid.UUID      `json:"report_id"`
	PageNumber       int32          `json:"page_number"`
	ExtractedText    string         `json:"extracted_text"`
	ExtractionMethod string         `json:"extraction_method"`
	ReadError        *string        `json:"read_error"`
	Width            pgtype.Numeric `json:"width"`
	Height           pgtype.Numeric `json:"height"`
}

func (q *Queries) UpsertLabReportPage(ctx context.Context, arg UpsertLabReportPageParams) error {
	_, err := q.db.Exec(ctx, upsertLabReportPage,
		arg.ReportID,
		arg.PageNumber,
		arg.ExtractedText,
		arg.ExtractionMethod,
		arg.ReadError,
		arg.Width,
		arg.Height,
	)
	return err
}

const upsertWorkspace = `-- name: UpsertWorkspace :one
INSERT INTO pfas.workspaces (id, key_hash)
VALUES ($1, $2)
ON CONFLICT (key_hash) DO UPDATE SET last_seen_at = now()
RETURNING id, key_hash, created_at, last_seen_at
`

type UpsertWorkspaceParams struct {
	ID      uuid.UUID `json:"id"`
	KeyHash string    `json:"key_hash"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (PfasWorkspace, error) {
	row := q.db.QueryRow(ctx, upsertWorkspace, arg.ID, arg.KeyHash)
	var i PfasWorkspace
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
