// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PfasAgentRun struct {
	ID          uuid.UUID          `json:"id"`
	Kind        string             `json:"kind"`
	Status      string             `json:"status"`
	NextStep    int16              `json:"next_step"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PfasAgentStep struct {
	ID           uuid.UUID          `json:"id"`
	RunID        uuid.UUID          `json:"run_id"`
	Position     int16              `json:"position"`
	ToolName     string             `json:"tool_name"`
	Status       string             `json:"status"`
	AttemptCount int32              `json:"attempt_count"`
	Summary      []byte             `json:"summary"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PfasAnalyteResult struct {
	ID                              uuid.UUID          `json:"id"`
	ReportID                        uuid.UUID          `json:"report_id"`
	VersionID                       uuid.UUID          `json:"version_id"`
	CanonicalAnalyte                string             `json:"canonical_analyte"`
	ReportedAnalyte                 string             `json:"reported_analyte"`
	ResultText                      string             `json:"result_text"`
	Value                           pgtype.Numeric     `json:"value"`
	Unit                            *string            `json:"unit"`
	Basis                           *string            `json:"basis"`
	Qualifier                       *string            `json:"qualifier"`
	IsNonDetect                     bool               `json:"is_non_detect"`
	ReportingLimit                  pgtype.Numeric     `json:"reporting_limit"`
	DetectionLimit                  pgtype.Numeric     `json:"detection_limit"`
	NormalizedValueUgKgDry          pgtype.Numeric     `json:"normalized_value_ug_kg_dry"`
	NormalizedReportingLimitUgKgDry pgtype.Numeric     `json:"normalized_reporting_limit_ug_kg_dry"`
	NormalizedDetectionLimitUgKgDry pgtype.Numeric     `json:"normalized_detection_limit_ug_kg_dry"`
	SourcePage                      int32              `json:"source_page"`
	SourceExcerpt                   string             `json:"source_excerpt"`
	SourceBounds                    []byte             `json:"source_bounds"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
}

type PfasBatchPolicyDecision struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	ReportID        uuid.UUID          `json:"report_id"`
	ReportVersionID uuid.UUID          `json:"report_version_id"`
	RulePackID      uuid.UUID          `json:"rule_pack_id"`
	Jurisdiction    string             `json:"jurisdiction"`
	Tier            string             `json:"tier"`
	MatchedRuleID   *string            `json:"matched_rule_id"`
	Explanation     string             `json:"explanation"`
	BlockingReason  *string            `json:"blocking_reason"`
	InputHash       string             `json:"input_hash"`
	AnalyteEvidence []byte             `json:"analyte_evidence"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PfasBatchPolicyRequirement struct {
	ID            uuid.UUID          `json:"id"`
	DecisionID    uuid.UUID          `json:"decision_id"`
	Position      int32              `json:"position"`
	RequirementID string             `json:"requirement_id"`
	Title         string             `json:"title"`
	Detail        string             `json:"detail"`
	Timing        string             `json:"timing"`
	RuleID        string             `json:"rule_id"`
	SourceUrl     string             `json:"source_url"`
	SourceTitle   string             `json:"source_title"`
	AuthorityType string             `json:"authority_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PfasBiosolidsBatch struct {
	ID                   uuid.UUID          `json:"id"`
	WorkspaceID          uuid.UUID          `json:"workspace_id"`
	FacilityID           uuid.UUID          `json:"facility_id"`
	Identifier           string             `json:"identifier"`
	NormalizedIdentifier string             `json:"normalized_identifier"`
	WetMassKg            pgtype.Numeric     `json:"wet_mass_kg"`
	PercentSolids        pgtype.Numeric     `json:"percent_solids"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PfasCandidateField struct {
	ID                       uuid.UUID          `json:"id"`
	WorkspaceID              uuid.UUID          `json:"workspace_id"`
	FacilityID               uuid.UUID          `json:"facility_id"`
	Name                     string             `json:"name"`
	NormalizedName           string             `json:"normalized_name"`
	LocatorKind              string             `json:"locator_kind"`
	LocatorInput             string             `json:"locator_input"`
	Status                   string             `json:"status"`
	MienviroSiteID           *string            `json:"mienviro_site_id"`
	RmpApproved              *bool              `json:"rmp_approved"`
	RmpDocumentReference     *string            `json:"rmp_document_reference"`
	UsableAcres              pgtype.Numeric     `json:"usable_acres"`
	CropOrUse                *string            `json:"crop_or_use"`
	AgronomicRateDryTonsAcre pgtype.Numeric     `json:"agronomic_rate_dry_tons_acre"`
	PriorLoadingDryTons      pgtype.Numeric     `json:"prior_loading_dry_tons"`
	KnownConstraints         *string            `json:"known_constraints"`
	AccessConstraints        *string            `json:"access_constraints"`
	CurrentGeometryID        uuid.NullUUID      `json:"current_geometry_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type PfasDataGap struct {
	ID         uuid.UUID          `json:"id"`
	RunID      uuid.UUID          `json:"run_id"`
	StepID     uuid.NullUUID      `json:"step_id"`
	Code       string             `json:"code"`
	Detail     string             `json:"detail"`
	Resolution string             `json:"resolution"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type PfasFacility struct {
	ID             uuid.UUID          `json:"id"`
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	Jurisdiction   string             `json:"jurisdiction"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PfasFieldDataGap struct {
	ID         uuid.UUID          `json:"id"`
	FieldID    uuid.UUID          `json:"field_id"`
	Code       string             `json:"code"`
	Detail     string             `json:"detail"`
	Resolution string             `json:"resolution"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type PfasFieldGeometryVersion struct {
	ID             uuid.UUID          `json:"id"`
	FieldID        uuid.UUID          `json:"field_id"`
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	Version        int32              `json:"version"`
	Source         string             `json:"source"`
	SourceLookupID uuid.NullUUID      `json:"source_lookup_id"`
	Geometry       interface{}        `json:"geometry"`
	GeometryHash   string             `json:"geometry_hash"`
	AreaAcres      pgtype.Numeric     `json:"area_acres"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PfasFieldLocationLookup struct {
	ID                   uuid.UUID          `json:"id"`
	FieldID              uuid.UUID          `json:"field_id"`
	WorkspaceID          uuid.UUID          `json:"workspace_id"`
	Input                string             `json:"input"`
	InputKind            string             `json:"input_kind"`
	RequestHash          string             `json:"request_hash"`
	ResponseHash         string             `json:"response_hash"`
	RequestID            *string            `json:"request_id"`
	SourceUrl            string             `json:"source_url"`
	Disposition          string             `json:"disposition"`
	Latitude             pgtype.Numeric     `json:"latitude"`
	Longitude            pgtype.Numeric     `json:"longitude"`
	ResolvedAddress      *string            `json:"resolved_address"`
	State                *string            `json:"state"`
	County               *string            `json:"county"`
	Fips                 *string            `json:"fips"`
	Confidence           pgtype.Numeric     `json:"confidence"`
	MatchMethod          *string            `json:"match_method"`
	ParcelID             *string            `json:"parcel_id"`
	ParcelGeometry       []byte             `json:"parcel_geometry"`
	ParcelMatchType      *string            `json:"parcel_match_type"`
	ParcelMatchDistanceM pgtype.Numeric     `json:"parcel_match_distance_m"`
	ParcelSource         *string            `json:"parcel_source"`
	ParcelUnavailable    bool               `json:"parcel_unavailable"`
	Candidates           []byte             `json:"candidates"`
	Reason               *string            `json:"reason"`
	Hint                 *string            `json:"hint"`
	Evidence             []byte             `json:"evidence"`
	FetchedAt            pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type PfasLabConfirmation struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceID  uuid.UUID          `json:"workspace_id"`
	ReportID     uuid.UUID          `json:"report_id"`
	VersionID    uuid.UUID          `json:"version_id"`
	EvidenceHash string             `json:"evidence_hash"`
	ConfirmedAt  pgtype.Timestamptz `json:"confirmed_at"`
}

type PfasLabReport struct {
	ID               uuid.UUID          `json:"id"`
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	FacilityID       uuid.UUID          `json:"facility_id"`
	BatchID          uuid.UUID          `json:"batch_id"`
	OriginalFilename string             `json:"original_filename"`
	MediaType        string             `json:"media_type"`
	SizeBytes        int32              `json:"size_bytes"`
	Sha256           string             `json:"sha256"`
	Content          []byte             `json:"content"`
	Status           string             `json:"status"`
	CurrentVersion   int32              `json:"current_version"`
	FailureCode      *string            `json:"failure_code"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
}

type PfasLabReportGap struct {
	ID         uuid.UUID          `json:"id"`
	ReportID   uuid.UUID          `json:"report_id"`
	VersionID  uuid.UUID          `json:"version_id"`
	Code       string             `json:"code"`
	FieldName  string             `json:"field_name"`
	Detail     string             `json:"detail"`
	Resolution string             `json:"resolution"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type PfasLabReportPage struct {
	ReportID         uuid.UUID          `json:"report_id"`
	PageNumber       int32              `json:"page_number"`
	ExtractedText    string             `json:"extracted_text"`
	ExtractionMethod string             `json:"extraction_method"`
	Width            pgtype.Numeric     `json:"width"`
	Height           pgtype.Numeric     `json:"height"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type PfasLabReportVersion struct {
	ID               uuid.UUID          `json:"id"`
	ReportID         uuid.UUID          `json:"report_id"`
	Version          int32              `json:"version"`
	Status           string             `json:"status"`
	Source           string             `json:"source"`
	Laboratory       *string            `json:"laboratory"`
	SampleIdentifier *string            `json:"sample_identifier"`
	CollectionDate   pgtype.Date        `json:"collection_date"`
	Matrix           *string            `json:"matrix"`
	Method           *string            `json:"method"`
	Basis            *string            `json:"basis"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
}

type PfasMireyeFetchBatch struct {
	ID           uuid.UUID          `json:"id"`
	EvaluationID uuid.UUID          `json:"evaluation_id"`
	RequestHash  string             `json:"request_hash"`
	ResponseHash string             `json:"response_hash"`
	RequestID    *string            `json:"request_id"`
	SourceUrl    string             `json:"source_url"`
	HttpStatus   int32              `json:"http_status"`
	Request      []byte             `json:"request"`
	Response     []byte             `json:"response"`
	FetchedAt    pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PfasPhysicalDataGap struct {
	EvaluationID uuid.UUID `json:"evaluation_id"`
	Code         string    `json:"code"`
	Source       string    `json:"source"`
	Detail       string    `json:"detail"`
	Critical     bool      `json:"critical"`
}

type PfasPhysicalEvaluation struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	FieldID            uuid.UUID          `json:"field_id"`
	GeometryID         uuid.UUID          `json:"geometry_id"`
	Status             string             `json:"status"`
	FieldSetVersion    string             `json:"field_set_version"`
	AggregationVersion string             `json:"aggregation_version"`
	CatalogVersion     *string            `json:"catalog_version"`
	CatalogEtag        *string            `json:"catalog_etag"`
	SampleCount        int32              `json:"sample_count"`
	ProjectedCredits   int32              `json:"projected_credits"`
	RequestHash        *string            `json:"request_hash"`
	FailureCode        *string            `json:"failure_code"`
	FailureDetail      *string            `json:"failure_detail"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type PfasPhysicalFieldFact struct {
	EvaluationID    uuid.UUID          `json:"evaluation_id"`
	FieldName       string             `json:"field_name"`
	Category        string             `json:"category"`
	Label           string             `json:"label"`
	State           string             `json:"state"`
	AggregateMethod string             `json:"aggregate_method"`
	Value           []byte             `json:"value"`
	Unit            *string            `json:"unit"`
	Source          *string            `json:"source"`
	SourceUrl       *string            `json:"source_url"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	OkCount         int32              `json:"ok_count"`
	AbsentCount     int32              `json:"absent_count"`
	FailedCount     int32              `json:"failed_count"`
	SampleIndices   []byte             `json:"sample_indices"`
	Critical        bool               `json:"critical"`
}

type PfasPhysicalSampleFact struct {
	EvaluationID   uuid.UUID          `json:"evaluation_id"`
	SampleIndex    int32              `json:"sample_index"`
	FieldName      string             `json:"field_name"`
	Status         string             `json:"status"`
	Value          []byte             `json:"value"`
	Unit           *string            `json:"unit"`
	Source         *string            `json:"source"`
	SourceUrl      *string            `json:"source_url"`
	Confidence     *string            `json:"confidence"`
	FetchedAt      pgtype.Timestamptz `json:"fetched_at"`
	DatasetVintage *string            `json:"dataset_vintage"`
	TtlSeconds     *int32             `json:"ttl_seconds"`
	Notes          *string            `json:"notes"`
	Error          *string            `json:"error"`
	Retryable      bool               `json:"retryable"`
}

type PfasPhysicalSamplePoint struct {
	EvaluationID uuid.UUID   `json:"evaluation_id"`
	SampleIndex  int32       `json:"sample_index"`
	Label        string      `json:"label"`
	Point        interface{} `json:"point"`
}

type PfasPolicyRulePack struct {
	ID            uuid.UUID          `json:"id"`
	Code          string             `json:"code"`
	Version       string             `json:"version"`
	Jurisdiction  string             `json:"jurisdiction"`
	AuthorityType string             `json:"authority_type"`
	EffectiveFrom pgtype.Date        `json:"effective_from"`
	EffectiveTo   pgtype.Date        `json:"effective_to"`
	RetrievedAt   pgtype.Timestamptz `json:"retrieved_at"`
	SourceUrl     string             `json:"source_url"`
	SourceTitle   string             `json:"source_title"`
	ReviewStatus  string             `json:"review_status"`
	ReviewedBy    *string            `json:"reviewed_by"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	Checksum      string             `json:"checksum"`
	Explanation   string             `json:"explanation"`
	Definition    []byte             `json:"definition"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PfasSupplementalEvidence struct {
	EvaluationID  uuid.UUID          `json:"evaluation_id"`
	Provider      string             `json:"provider"`
	Kind          string             `json:"kind"`
	Status        string             `json:"status"`
	Title         string             `json:"title"`
	Summary       string             `json:"summary"`
	Value         []byte             `json:"value"`
	SourceUrl     string             `json:"source_url"`
	SourceVintage *string            `json:"source_vintage"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
	Caveat        *string            `json:"caveat"`
}

type PfasToolCall struct {
	ID            uuid.UUID          `json:"id"`
	RunID         uuid.UUID          `json:"run_id"`
	StepID        uuid.UUID          `json:"step_id"`
	Attempt       int32              `json:"attempt"`
	Status        string             `json:"status"`
	RequestMethod string             `json:"request_method"`
	RequestPath   string             `json:"request_path"`
	RequestHash   string             `json:"request_hash"`
	ResponseHash  *string            `json:"response_hash"`
	RequestID     *string            `json:"request_id"`
	SourceUrl     string             `json:"source_url"`
	HttpStatus    *int32             `json:"http_status"`
	DurationMs    int64              `json:"duration_ms"`
	CreditCost    int32              `json:"credit_cost"`
	ResponseBody  []byte             `json:"response_body"`
	ErrorCode     *string            `json:"error_code"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PfasWorkspace struct {
	ID         uuid.UUID          `json:"id"`
	KeyHash    string             `json:"key_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}
