// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PfasAgentRun struct {
	ID          uuid.UUID          `json:"id"`
	Kind        string             `json:"kind"`
	Status      string             `json:"status"`
	NextStep    int16              `json:"next_step"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PfasAgentStep struct {
	ID           uuid.UUID          `json:"id"`
	RunID        uuid.UUID          `json:"run_id"`
	Position     int16              `json:"position"`
	ToolName     string             `json:"tool_name"`
	Status       string             `json:"status"`
	AttemptCount int32              `json:"attempt_count"`
	Summary      []byte             `json:"summary"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PfasDataGap struct {
	ID         uuid.UUID          `json:"id"`
	RunID      uuid.UUID          `json:"run_id"`
	StepID     uuid.NullUUID      `json:"step_id"`
	Code       string             `json:"code"`
	Detail     string             `json:"detail"`
	Resolution string             `json:"resolution"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type PfasToolCall struct {
	ID            uuid.UUID          `json:"id"`
	RunID         uuid.UUID          `json:"run_id"`
	StepID        uuid.UUID          `json:"step_id"`
	Attempt       int32              `json:"attempt"`
	Status        string             `json:"status"`
	RequestMethod string             `json:"request_method"`
	RequestPath   string             `json:"request_path"`
	RequestHash   string             `json:"request_hash"`
	ResponseHash  *string            `json:"response_hash"`
	RequestID     *string            `json:"request_id"`
	SourceUrl     string             `json:"source_url"`
	HttpStatus    *int32             `json:"http_status"`
	DurationMs    int64              `json:"duration_ms"`
	CreditCost    int32              `json:"credit_cost"`
	ResponseBody  []byte             `json:"response_body"`
	ErrorCode     *string            `json:"error_code"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
