// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PfasAction struct {
	ID                uuid.UUID          `json:"id"`
	WorkspaceID       uuid.UUID          `json:"workspace_id"`
	DecisionPackageID uuid.UUID          `json:"decision_package_id"`
	Position          int32              `json:"position"`
	Code              string             `json:"code"`
	Category          string             `json:"category"`
	Title             string             `json:"title"`
	Detail            string             `json:"detail"`
	Timing            string             `json:"timing"`
	SourceID          string             `json:"source_id"`
	ExecutionMode     string             `json:"execution_mode"`
	Status            string             `json:"status"`
	ApprovalRequired  bool               `json:"approval_required"`
	Channel           string             `json:"channel"`
	Recipient         string             `json:"recipient"`
	Subject           string             `json:"subject"`
	Message           string             `json:"message"`
	Attachments       []byte             `json:"attachments"`
	Revision          int32              `json:"revision"`
	PayloadHash       string             `json:"payload_hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type PfasActionDecision struct {
	ID                   uuid.UUID          `json:"id"`
	WorkspaceID          uuid.UUID          `json:"workspace_id"`
	ActionID             uuid.UUID          `json:"action_id"`
	DecisionPackageID    uuid.UUID          `json:"decision_package_id"`
	Kind                 string             `json:"kind"`
	ActionRevision       int32              `json:"action_revision"`
	PayloadHash          string             `json:"payload_hash"`
	ActorName            string             `json:"actor_name"`
	ActorRole            string             `json:"actor_role"`
	Note                 string             `json:"note"`
	AcknowledgedGapCodes []byte             `json:"acknowledged_gap_codes"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type PfasAgentRun struct {
	ID          uuid.UUID          `json:"id"`
	Kind        string             `json:"kind"`
	Status      string             `json:"status"`
	NextStep    int16              `json:"next_step"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PfasAgentStep struct {
	ID           uuid.UUID          `json:"id"`
	RunID        uuid.UUID          `json:"run_id"`
	Position     int16              `json:"position"`
	ToolName     string             `json:"tool_name"`
	Status       string             `json:"status"`
	AttemptCount int32              `json:"attempt_count"`
	Summary      []byte             `json:"summary"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PfasAlternativeManagementCandidate struct {
	RunID                  uuid.UUID `json:"run_id"`
	Position               int32     `json:"position"`
	WdsID                  string    `json:"wds_id"`
	FacilityName           string    `json:"facility_name"`
	FacilityType           string    `json:"facility_type"`
	Address                string    `json:"address"`
	City                   string    `json:"city"`
	County                 string    `json:"county"`
	Latitude               float64   `json:"latitude"`
	Longitude              float64   `json:"longitude"`
	DisposalAreaStatus     string    `json:"disposal_area_status"`
	StraightlineDistanceKm float64   `json:"straightline_distance_km"`
	RouteStatus            string    `json:"route_status"`
	DrivingDistanceKm      *float64  `json:"driving_distance_km"`
	DurationMinutes        *float64  `json:"duration_minutes"`
	RouteNote              *string   `json:"route_note"`
	AcceptanceStatus       string    `json:"acceptance_status"`
	Executable             bool      `json:"executable"`
	SourceUrl              string    `json:"source_url"`
}

type PfasAnalyteResult struct {
	ID                              uuid.UUID          `json:"id"`
	ReportID                        uuid.UUID          `json:"report_id"`
	VersionID                       uuid.UUID          `json:"version_id"`
	CanonicalAnalyte                string             `json:"canonical_analyte"`
	ReportedAnalyte                 string             `json:"reported_analyte"`
	ResultText                      string             `json:"result_text"`
	Value                           pgtype.Numeric     `json:"value"`
	Unit                            *string            `json:"unit"`
	Basis                           *string            `json:"basis"`
	Qualifier                       *string            `json:"qualifier"`
	IsNonDetect                     bool               `json:"is_non_detect"`
	ReportingLimit                  pgtype.Numeric     `json:"reporting_limit"`
	DetectionLimit                  pgtype.Numeric     `json:"detection_limit"`
	NormalizedValueUgKgDry          pgtype.Numeric     `json:"normalized_value_ug_kg_dry"`
	NormalizedReportingLimitUgKgDry pgtype.Numeric     `json:"normalized_reporting_limit_ug_kg_dry"`
	NormalizedDetectionLimitUgKgDry pgtype.Numeric     `json:"normalized_detection_limit_ug_kg_dry"`
	SourcePage                      int32              `json:"source_page"`
	SourceExcerpt                   string             `json:"source_excerpt"`
	SourceBounds                    []byte             `json:"source_bounds"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
}

type PfasBatchPolicyDecision struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	ReportID        uuid.UUID          `json:"report_id"`
	ReportVersionID uuid.UUID          `json:"report_version_id"`
	RulePackID      uuid.UUID          `json:"rule_pack_id"`
	Jurisdiction    string             `json:"jurisdiction"`
	Tier            string             `json:"tier"`
	MatchedRuleID   *string            `json:"matched_rule_id"`
	Explanation     string             `json:"explanation"`
	BlockingReason  *string            `json:"blocking_reason"`
	InputHash       string             `json:"input_hash"`
	AnalyteEvidence []byte             `json:"analyte_evidence"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PfasBatchPolicyRequirement struct {
	ID            uuid.UUID          `json:"id"`
	DecisionID    uuid.UUID          `json:"decision_id"`
	Position      int32              `json:"position"`
	RequirementID string             `json:"requirement_id"`
	Title         string             `json:"title"`
	Detail        string             `json:"detail"`
	Timing        string             `json:"timing"`
	RuleID        string             `json:"rule_id"`
	SourceUrl     string             `json:"source_url"`
	SourceTitle   string             `json:"source_title"`
	AuthorityType string             `json:"authority_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PfasBiosolidsBatch struct {
	ID                   uuid.UUID          `json:"id"`
	WorkspaceID          uuid.UUID          `json:"workspace_id"`
	FacilityID           uuid.UUID          `json:"facility_id"`
	Identifier           string             `json:"identifier"`
	NormalizedIdentifier string             `json:"normalized_identifier"`
	WetMassKg            pgtype.Numeric     `json:"wet_mass_kg"`
	PercentSolids        pgtype.Numeric     `json:"percent_solids"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PfasCandidateField struct {
	ID                       uuid.UUID          `json:"id"`
	WorkspaceID              uuid.UUID          `json:"workspace_id"`
	FacilityID               uuid.UUID          `json:"facility_id"`
	Name                     string             `json:"name"`
	NormalizedName           string             `json:"normalized_name"`
	LocatorKind              string             `json:"locator_kind"`
	LocatorInput             string             `json:"locator_input"`
	Status                   string             `json:"status"`
	MienviroSiteID           *string            `json:"mienviro_site_id"`
	RmpApproved              *bool              `json:"rmp_approved"`
	RmpDocumentReference     *string            `json:"rmp_document_reference"`
	UsableAcres              pgtype.Numeric     `json:"usable_acres"`
	CropOrUse                *string            `json:"crop_or_use"`
	AgronomicRateDryTonsAcre pgtype.Numeric     `json:"agronomic_rate_dry_tons_acre"`
	PriorLoadingDryTons      pgtype.Numeric     `json:"prior_loading_dry_tons"`
	KnownConstraints         *string            `json:"known_constraints"`
	AccessConstraints        *string            `json:"access_constraints"`
	CurrentGeometryID        uuid.NullUUID      `json:"current_geometry_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type PfasDataGap struct {
	ID         uuid.UUID          `json:"id"`
	RunID      uuid.UUID          `json:"run_id"`
	StepID     uuid.NullUUID      `json:"step_id"`
	Code       string             `json:"code"`
	Detail     string             `json:"detail"`
	Resolution string             `json:"resolution"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type PfasDecisionPackage struct {
	ID                    uuid.UUID          `json:"id"`
	WorkspaceID           uuid.UUID          `json:"workspace_id"`
	DecisionID            uuid.UUID          `json:"decision_id"`
	PlacementEvaluationID uuid.NullUUID      `json:"placement_evaluation_id"`
	ResponseRunID         uuid.NullUUID      `json:"response_run_id"`
	SchemaVersion         string             `json:"schema_version"`
	Status                string             `json:"status"`
	InputHash             string             `json:"input_hash"`
	Snapshot              []byte             `json:"snapshot"`
	EvidenceLedger        []byte             `json:"evidence_ledger"`
	ProposedActions       []byte             `json:"proposed_actions"`
	JsonArtifact          []byte             `json:"json_artifact"`
	HtmlArtifact          string             `json:"html_artifact"`
	PdfArtifact           []byte             `json:"pdf_artifact"`
	JsonSha256            string             `json:"json_sha256"`
	HtmlSha256            string             `json:"html_sha256"`
	PdfSha256             string             `json:"pdf_sha256"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type PfasExecutionAttempt struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	ActionID        uuid.UUID          `json:"action_id"`
	ApprovalID      uuid.UUID          `json:"approval_id"`
	IdempotencyKey  string             `json:"idempotency_key"`
	Outcome         string             `json:"outcome"`
	Receipt         []byte             `json:"receipt"`
	HandoffArtifact []byte             `json:"handoff_artifact"`
	HandoffSha256   *string            `json:"handoff_sha256"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PfasFacility struct {
	ID             uuid.UUID          `json:"id"`
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	Jurisdiction   string             `json:"jurisdiction"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PfasFacilityLocationLookup struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	FacilityID      uuid.UUID          `json:"facility_id"`
	Input           string             `json:"input"`
	InputKind       string             `json:"input_kind"`
	RequestHash     string             `json:"request_hash"`
	ResponseHash    string             `json:"response_hash"`
	RequestID       *string            `json:"request_id"`
	SourceUrl       string             `json:"source_url"`
	Disposition     string             `json:"disposition"`
	Latitude        *float64           `json:"latitude"`
	Longitude       *float64           `json:"longitude"`
	ResolvedAddress *string            `json:"resolved_address"`
	State           *string            `json:"state"`
	County          *string            `json:"county"`
	Confidence      *float64           `json:"confidence"`
	MatchMethod     *string            `json:"match_method"`
	Candidates      []byte             `json:"candidates"`
	Reason          *string            `json:"reason"`
	Hint            *string            `json:"hint"`
	Evidence        []byte             `json:"evidence"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PfasFieldDataGap struct {
	ID         uuid.UUID          `json:"id"`
	FieldID    uuid.UUID          `json:"field_id"`
	Code       string             `json:"code"`
	Detail     string             `json:"detail"`
	Resolution string             `json:"resolution"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type PfasFieldGeometryVersion struct {
	ID             uuid.UUID          `json:"id"`
	FieldID        uuid.UUID          `json:"field_id"`
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	Version        int32              `json:"version"`
	Source         string             `json:"source"`
	SourceLookupID uuid.NullUUID      `json:"source_lookup_id"`
	Geometry       interface{}        `json:"geometry"`
	GeometryHash   string             `json:"geometry_hash"`
	AreaAcres      pgtype.Numeric     `json:"area_acres"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PfasFieldLocationLookup struct {
	ID                   uuid.UUID          `json:"id"`
	FieldID              uuid.UUID          `json:"field_id"`
	WorkspaceID          uuid.UUID          `json:"workspace_id"`
	Input                string             `json:"input"`
	InputKind            string             `json:"input_kind"`
	RequestHash          string             `json:"request_hash"`
	ResponseHash         string             `json:"response_hash"`
	RequestID            *string            `json:"request_id"`
	SourceUrl            string             `json:"source_url"`
	Disposition          string             `json:"disposition"`
	Latitude             pgtype.Numeric     `json:"latitude"`
	Longitude            pgtype.Numeric     `json:"longitude"`
	ResolvedAddress      *string            `json:"resolved_address"`
	State                *string            `json:"state"`
	County               *string            `json:"county"`
	Fips                 *string            `json:"fips"`
	Confidence           pgtype.Numeric     `json:"confidence"`
	MatchMethod          *string            `json:"match_method"`
	ParcelID             *string            `json:"parcel_id"`
	ParcelGeometry       []byte             `json:"parcel_geometry"`
	ParcelMatchType      *string            `json:"parcel_match_type"`
	ParcelMatchDistanceM pgtype.Numeric     `json:"parcel_match_distance_m"`
	ParcelSource         *string            `json:"parcel_source"`
	ParcelUnavailable    bool               `json:"parcel_unavailable"`
	Candidates           []byte             `json:"candidates"`
	Reason               *string            `json:"reason"`
	Hint                 *string            `json:"hint"`
	Evidence             []byte             `json:"evidence"`
	FetchedAt            pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type PfasInvestigationLead struct {
	RunID         uuid.UUID `json:"run_id"`
	Position      int32     `json:"position"`
	RegistryID    string    `json:"registry_id"`
	FacilityName  string    `json:"facility_name"`
	City          *string   `json:"city"`
	State         *string   `json:"state"`
	NaicsCodes    []byte    `json:"naics_codes"`
	EvidenceTier  int32     `json:"evidence_tier"`
	EvidenceLabel string    `json:"evidence_label"`
	Rationale     string    `json:"rationale"`
	Caveat        string    `json:"caveat"`
	SourceUrl     string    `json:"source_url"`
}

type PfasLabConfirmation struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceID  uuid.UUID          `json:"workspace_id"`
	ReportID     uuid.UUID          `json:"report_id"`
	VersionID    uuid.UUID          `json:"version_id"`
	EvidenceHash string             `json:"evidence_hash"`
	ConfirmedAt  pgtype.Timestamptz `json:"confirmed_at"`
}

type PfasLabReport struct {
	ID               uuid.UUID          `json:"id"`
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	FacilityID       uuid.UUID          `json:"facility_id"`
	BatchID          uuid.UUID          `json:"batch_id"`
	OriginalFilename string             `json:"original_filename"`
	MediaType        string             `json:"media_type"`
	SizeBytes        int32              `json:"size_bytes"`
	Sha256           string             `json:"sha256"`
	Content          []byte             `json:"content"`
	Status           string             `json:"status"`
	CurrentVersion   int32              `json:"current_version"`
	FailureCode      *string            `json:"failure_code"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
}

type PfasLabReportGap struct {
	ID         uuid.UUID          `json:"id"`
	ReportID   uuid.UUID          `json:"report_id"`
	VersionID  uuid.UUID          `json:"version_id"`
	Code       string             `json:"code"`
	FieldName  string             `json:"field_name"`
	Detail     string             `json:"detail"`
	Resolution string             `json:"resolution"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type PfasLabReportPage struct {
	ReportID         uuid.UUID          `json:"report_id"`
	PageNumber       int32              `json:"page_number"`
	ExtractedText    string             `json:"extracted_text"`
	ExtractionMethod string             `json:"extraction_method"`
	Width            pgtype.Numeric     `json:"width"`
	Height           pgtype.Numeric     `json:"height"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type PfasLabReportVersion struct {
	ID               uuid.UUID          `json:"id"`
	ReportID         uuid.UUID          `json:"report_id"`
	Version          int32              `json:"version"`
	Status           string             `json:"status"`
	Source           string             `json:"source"`
	Laboratory       *string            `json:"laboratory"`
	SampleIdentifier *string            `json:"sample_identifier"`
	CollectionDate   pgtype.Date        `json:"collection_date"`
	Matrix           *string            `json:"matrix"`
	Method           *string            `json:"method"`
	Basis            *string            `json:"basis"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
}

type PfasMireyeFetchBatch struct {
	ID           uuid.UUID          `json:"id"`
	EvaluationID uuid.UUID          `json:"evaluation_id"`
	RequestHash  string             `json:"request_hash"`
	ResponseHash string             `json:"response_hash"`
	RequestID    *string            `json:"request_id"`
	SourceUrl    string             `json:"source_url"`
	HttpStatus   int32              `json:"http_status"`
	Request      []byte             `json:"request"`
	Response     []byte             `json:"response"`
	FetchedAt    pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PfasPhysicalDataGap struct {
	EvaluationID uuid.UUID `json:"evaluation_id"`
	Code         string    `json:"code"`
	Source       string    `json:"source"`
	Detail       string    `json:"detail"`
	Critical     bool      `json:"critical"`
}

type PfasPhysicalEvaluation struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	FieldID            uuid.UUID          `json:"field_id"`
	GeometryID         uuid.UUID          `json:"geometry_id"`
	Status             string             `json:"status"`
	FieldSetVersion    string             `json:"field_set_version"`
	AggregationVersion string             `json:"aggregation_version"`
	CatalogVersion     *string            `json:"catalog_version"`
	CatalogEtag        *string            `json:"catalog_etag"`
	SampleCount        int32              `json:"sample_count"`
	ProjectedCredits   int32              `json:"projected_credits"`
	RequestHash        *string            `json:"request_hash"`
	FailureCode        *string            `json:"failure_code"`
	FailureDetail      *string            `json:"failure_detail"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type PfasPhysicalFieldFact struct {
	EvaluationID    uuid.UUID          `json:"evaluation_id"`
	FieldName       string             `json:"field_name"`
	Category        string             `json:"category"`
	Label           string             `json:"label"`
	State           string             `json:"state"`
	AggregateMethod string             `json:"aggregate_method"`
	Value           []byte             `json:"value"`
	Unit            *string            `json:"unit"`
	Source          *string            `json:"source"`
	SourceUrl       *string            `json:"source_url"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	OkCount         int32              `json:"ok_count"`
	AbsentCount     int32              `json:"absent_count"`
	FailedCount     int32              `json:"failed_count"`
	SampleIndices   []byte             `json:"sample_indices"`
	Critical        bool               `json:"critical"`
}

type PfasPhysicalSampleFact struct {
	EvaluationID   uuid.UUID          `json:"evaluation_id"`
	SampleIndex    int32              `json:"sample_index"`
	FieldName      string             `json:"field_name"`
	Status         string             `json:"status"`
	Value          []byte             `json:"value"`
	Unit           *string            `json:"unit"`
	Source         *string            `json:"source"`
	SourceUrl      *string            `json:"source_url"`
	Confidence     *string            `json:"confidence"`
	FetchedAt      pgtype.Timestamptz `json:"fetched_at"`
	DatasetVintage *string            `json:"dataset_vintage"`
	TtlSeconds     *int32             `json:"ttl_seconds"`
	Notes          *string            `json:"notes"`
	Error          *string            `json:"error"`
	Retryable      bool               `json:"retryable"`
}

type PfasPhysicalSamplePoint struct {
	EvaluationID uuid.UUID   `json:"evaluation_id"`
	SampleIndex  int32       `json:"sample_index"`
	Label        string      `json:"label"`
	Point        interface{} `json:"point"`
}

type PfasPlacementAllocation struct {
	EvaluationID    uuid.UUID      `json:"evaluation_id"`
	Position        int32          `json:"position"`
	FieldID         uuid.UUID      `json:"field_id"`
	FieldName       string         `json:"field_name"`
	DryTons         pgtype.Numeric `json:"dry_tons"`
	Acres           pgtype.Numeric `json:"acres"`
	RateDryTonsAcre pgtype.Numeric `json:"rate_dry_tons_acre"`
}

type PfasPlacementDataGap struct {
	EvaluationID uuid.UUID `json:"evaluation_id"`
	Code         string    `json:"code"`
	Detail       string    `json:"detail"`
	Resolution   string    `json:"resolution"`
}

type PfasPlacementEvaluation struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	DecisionID         uuid.UUID          `json:"decision_id"`
	BatchID            uuid.UUID          `json:"batch_id"`
	Status             string             `json:"status"`
	Tier               string             `json:"tier"`
	ConfigVersion      string             `json:"config_version"`
	ConfigChecksum     string             `json:"config_checksum"`
	InputHash          string             `json:"input_hash"`
	WetMassKg          pgtype.Numeric     `json:"wet_mass_kg"`
	PercentSolids      pgtype.Numeric     `json:"percent_solids"`
	BatchDryTons       pgtype.Numeric     `json:"batch_dry_tons"`
	AllocatedDryTons   pgtype.Numeric     `json:"allocated_dry_tons"`
	UnallocatedDryTons pgtype.Numeric     `json:"unallocated_dry_tons"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type PfasPlacementFieldResult struct {
	EvaluationID             uuid.UUID      `json:"evaluation_id"`
	FieldID                  uuid.UUID      `json:"field_id"`
	PhysicalEvaluationID     uuid.NullUUID  `json:"physical_evaluation_id"`
	FieldName                string         `json:"field_name"`
	Disposition              string         `json:"disposition"`
	Rank                     *int32         `json:"rank"`
	Explanation              string         `json:"explanation"`
	Counterfactual           *string        `json:"counterfactual"`
	HighConcernCount         int32          `json:"high_concern_count"`
	ModerateConcernCount     int32          `json:"moderate_concern_count"`
	DataGapCount             int32          `json:"data_gap_count"`
	AllowedRateDryTonsAcre   pgtype.Numeric `json:"allowed_rate_dry_tons_acre"`
	AvailableCapacityDryTons pgtype.Numeric `json:"available_capacity_dry_tons"`
	RoadAccessDistanceM      *float64       `json:"road_access_distance_m"`
	Reasons                  []byte         `json:"reasons"`
}

type PfasPlacementRelease struct {
	ID                    uuid.UUID          `json:"id"`
	WorkspaceID           uuid.UUID          `json:"workspace_id"`
	DecisionPackageID     uuid.UUID          `json:"decision_package_id"`
	PlacementEvaluationID uuid.UUID          `json:"placement_evaluation_id"`
	ActionID              uuid.UUID          `json:"action_id"`
	ApprovalID            uuid.UUID          `json:"approval_id"`
	ExecutionAttemptID    uuid.UUID          `json:"execution_attempt_id"`
	ReleasedAt            pgtype.Timestamptz `json:"released_at"`
}

type PfasPlacementVulnerabilityCategory struct {
	EvaluationID  uuid.UUID `json:"evaluation_id"`
	FieldID       uuid.UUID `json:"field_id"`
	CategoryKey   string    `json:"category_key"`
	Label         string    `json:"label"`
	Band          string    `json:"band"`
	Explanation   string    `json:"explanation"`
	Components    []byte    `json:"components"`
	AuthorityType string    `json:"authority_type"`
	SourceTitle   string    `json:"source_title"`
	SourceUrl     *string   `json:"source_url"`
	ConfigVersion string    `json:"config_version"`
}

type PfasPolicyRulePack struct {
	ID            uuid.UUID          `json:"id"`
	Code          string             `json:"code"`
	Version       string             `json:"version"`
	Jurisdiction  string             `json:"jurisdiction"`
	AuthorityType string             `json:"authority_type"`
	EffectiveFrom pgtype.Date        `json:"effective_from"`
	EffectiveTo   pgtype.Date        `json:"effective_to"`
	RetrievedAt   pgtype.Timestamptz `json:"retrieved_at"`
	SourceUrl     string             `json:"source_url"`
	SourceTitle   string             `json:"source_title"`
	ReviewStatus  string             `json:"review_status"`
	ReviewedBy    *string            `json:"reviewed_by"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	Checksum      string             `json:"checksum"`
	Explanation   string             `json:"explanation"`
	Definition    []byte             `json:"definition"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PfasResponseDataGap struct {
	RunID      uuid.UUID `json:"run_id"`
	Code       string    `json:"code"`
	Detail     string    `json:"detail"`
	Resolution string    `json:"resolution"`
	Critical   bool      `json:"critical"`
}

type PfasResponseEvidence struct {
	ID            uuid.UUID          `json:"id"`
	RunID         uuid.UUID          `json:"run_id"`
	Provider      string             `json:"provider"`
	Kind          string             `json:"kind"`
	Status        string             `json:"status"`
	Title         string             `json:"title"`
	Summary       string             `json:"summary"`
	Data          []byte             `json:"data"`
	SourceUrl     string             `json:"source_url"`
	SourceVintage *string            `json:"source_vintage"`
	RequestHash   *string            `json:"request_hash"`
	ResponseHash  *string            `json:"response_hash"`
	RequestID     *string            `json:"request_id"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
	Caveat        string             `json:"caveat"`
}

type PfasResponseRun struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	DecisionID         uuid.UUID          `json:"decision_id"`
	FacilityLocationID uuid.UUID          `json:"facility_location_id"`
	Tier               string             `json:"tier"`
	Status             string             `json:"status"`
	InputHash          string             `json:"input_hash"`
	PolicySourceUrl    string             `json:"policy_source_url"`
	PolicyVersion      string             `json:"policy_version"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	FailureCode        *string            `json:"failure_code"`
	FailureDetail      *string            `json:"failure_detail"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type PfasResponseTask struct {
	RunID    uuid.UUID `json:"run_id"`
	Position int32     `json:"position"`
	Code     string    `json:"code"`
	Category string    `json:"category"`
	Title    string    `json:"title"`
	Detail   string    `json:"detail"`
	Timing   string    `json:"timing"`
	State    string    `json:"state"`
}

type PfasSupplementalEvidence struct {
	EvaluationID  uuid.UUID          `json:"evaluation_id"`
	Provider      string             `json:"provider"`
	Kind          string             `json:"kind"`
	Status        string             `json:"status"`
	Title         string             `json:"title"`
	Summary       string             `json:"summary"`
	Value         []byte             `json:"value"`
	SourceUrl     string             `json:"source_url"`
	SourceVintage *string            `json:"source_vintage"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
	Caveat        *string            `json:"caveat"`
}

type PfasToolCall struct {
	ID            uuid.UUID          `json:"id"`
	RunID         uuid.UUID          `json:"run_id"`
	StepID        uuid.UUID          `json:"step_id"`
	Attempt       int32              `json:"attempt"`
	Status        string             `json:"status"`
	RequestMethod string             `json:"request_method"`
	RequestPath   string             `json:"request_path"`
	RequestHash   string             `json:"request_hash"`
	ResponseHash  *string            `json:"response_hash"`
	RequestID     *string            `json:"request_id"`
	SourceUrl     string             `json:"source_url"`
	HttpStatus    *int32             `json:"http_status"`
	DurationMs    int64              `json:"duration_ms"`
	CreditCost    int32              `json:"credit_cost"`
	ResponseBody  []byte             `json:"response_body"`
	ErrorCode     *string            `json:"error_code"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PfasWorkspace struct {
	ID         uuid.UUID          `json:"id"`
	KeyHash    string             `json:"key_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}
