// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: package.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDecisionPackage = `-- name: CreateDecisionPackage :one
INSERT INTO pfas.decision_packages (
    id, workspace_id, decision_id, placement_evaluation_id, response_run_id,
    schema_version, status, input_hash, snapshot, evidence_ledger,
    proposed_actions, json_artifact, html_artifact, pdf_artifact,
    json_sha256, html_sha256, pdf_sha256, created_at
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18
)
ON CONFLICT (decision_id, input_hash) DO NOTHING
RETURNING id, workspace_id, decision_id, placement_evaluation_id, response_run_id, schema_version, status, input_hash, snapshot, evidence_ledger, proposed_actions, json_artifact, html_artifact, pdf_artifact, json_sha256, html_sha256, pdf_sha256, created_at
`

type CreateDecisionPackageParams struct {
	ID                    uuid.UUID          `json:"id"`
	WorkspaceID           uuid.UUID          `json:"workspace_id"`
	DecisionID            uuid.UUID          `json:"decision_id"`
	PlacementEvaluationID uuid.NullUUID      `json:"placement_evaluation_id"`
	ResponseRunID         uuid.NullUUID      `json:"response_run_id"`
	SchemaVersion         string             `json:"schema_version"`
	Status                string             `json:"status"`
	InputHash             string             `json:"input_hash"`
	Snapshot              []byte             `json:"snapshot"`
	EvidenceLedger        []byte             `json:"evidence_ledger"`
	ProposedActions       []byte             `json:"proposed_actions"`
	JsonArtifact          []byte             `json:"json_artifact"`
	HtmlArtifact          string             `json:"html_artifact"`
	PdfArtifact           []byte             `json:"pdf_artifact"`
	JsonSha256            string             `json:"json_sha256"`
	HtmlSha256            string             `json:"html_sha256"`
	PdfSha256             string             `json:"pdf_sha256"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDecisionPackage(ctx context.Context, arg CreateDecisionPackageParams) (PfasDecisionPackage, error) {
	row := q.db.QueryRow(ctx, createDecisionPackage,
		arg.ID,
		arg.WorkspaceID,
		arg.DecisionID,
		arg.PlacementEvaluationID,
		arg.ResponseRunID,
		arg.SchemaVersion,
		arg.Status,
		arg.InputHash,
		arg.Snapshot,
		arg.EvidenceLedger,
		arg.ProposedActions,
		arg.JsonArtifact,
		arg.HtmlArtifact,
		arg.PdfArtifact,
		arg.JsonSha256,
		arg.HtmlSha256,
		arg.PdfSha256,
		arg.CreatedAt,
	)
	var i PfasDecisionPackage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionID,
		&i.PlacementEvaluationID,
		&i.ResponseRunID,
		&i.SchemaVersion,
		&i.Status,
		&i.InputHash,
		&i.Snapshot,
		&i.EvidenceLedger,
		&i.ProposedActions,
		&i.JsonArtifact,
		&i.HtmlArtifact,
		&i.PdfArtifact,
		&i.JsonSha256,
		&i.HtmlSha256,
		&i.PdfSha256,
		&i.CreatedAt,
	)
	return i, err
}

const getDecisionPackage = `-- name: GetDecisionPackage :one
SELECT id, workspace_id, decision_id, placement_evaluation_id, response_run_id, schema_version, status, input_hash, snapshot, evidence_ledger, proposed_actions, json_artifact, html_artifact, pdf_artifact, json_sha256, html_sha256, pdf_sha256, created_at FROM pfas.decision_packages
WHERE id = $1 AND workspace_id = $2
`

type GetDecisionPackageParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetDecisionPackage(ctx context.Context, arg GetDecisionPackageParams) (PfasDecisionPackage, error) {
	row := q.db.QueryRow(ctx, getDecisionPackage, arg.ID, arg.WorkspaceID)
	var i PfasDecisionPackage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionID,
		&i.PlacementEvaluationID,
		&i.ResponseRunID,
		&i.SchemaVersion,
		&i.Status,
		&i.InputHash,
		&i.Snapshot,
		&i.EvidenceLedger,
		&i.ProposedActions,
		&i.JsonArtifact,
		&i.HtmlArtifact,
		&i.PdfArtifact,
		&i.JsonSha256,
		&i.HtmlSha256,
		&i.PdfSha256,
		&i.CreatedAt,
	)
	return i, err
}

const getDecisionPackageByInput = `-- name: GetDecisionPackageByInput :one
SELECT id, workspace_id, decision_id, placement_evaluation_id, response_run_id, schema_version, status, input_hash, snapshot, evidence_ledger, proposed_actions, json_artifact, html_artifact, pdf_artifact, json_sha256, html_sha256, pdf_sha256, created_at FROM pfas.decision_packages
WHERE decision_id = $1 AND input_hash = $2
`

type GetDecisionPackageByInputParams struct {
	DecisionID uuid.UUID `json:"decision_id"`
	InputHash  string    `json:"input_hash"`
}

func (q *Queries) GetDecisionPackageByInput(ctx context.Context, arg GetDecisionPackageByInputParams) (PfasDecisionPackage, error) {
	row := q.db.QueryRow(ctx, getDecisionPackageByInput, arg.DecisionID, arg.InputHash)
	var i PfasDecisionPackage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionID,
		&i.PlacementEvaluationID,
		&i.ResponseRunID,
		&i.SchemaVersion,
		&i.Status,
		&i.InputHash,
		&i.Snapshot,
		&i.EvidenceLedger,
		&i.ProposedActions,
		&i.JsonArtifact,
		&i.HtmlArtifact,
		&i.PdfArtifact,
		&i.JsonSha256,
		&i.HtmlSha256,
		&i.PdfSha256,
		&i.CreatedAt,
	)
	return i, err
}

const getDecisionPackageContext = `-- name: GetDecisionPackageContext :one
SELECT decision.id AS decision_id, decision.workspace_id, decision.report_id,
       decision.tier, decision.input_hash AS decision_input_hash
FROM pfas.batch_policy_decisions decision
WHERE decision.id = $1 AND decision.workspace_id = $2
`

type GetDecisionPackageContextParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetDecisionPackageContextRow struct {
	DecisionID        uuid.UUID `json:"decision_id"`
	WorkspaceID       uuid.UUID `json:"workspace_id"`
	ReportID          uuid.UUID `json:"report_id"`
	Tier              string    `json:"tier"`
	DecisionInputHash string    `json:"decision_input_hash"`
}

func (q *Queries) GetDecisionPackageContext(ctx context.Context, arg GetDecisionPackageContextParams) (GetDecisionPackageContextRow, error) {
	row := q.db.QueryRow(ctx, getDecisionPackageContext, arg.ID, arg.WorkspaceID)
	var i GetDecisionPackageContextRow
	err := row.Scan(
		&i.DecisionID,
		&i.WorkspaceID,
		&i.ReportID,
		&i.Tier,
		&i.DecisionInputHash,
	)
	return i, err
}

const getLatestDecisionPackage = `-- name: GetLatestDecisionPackage :one
SELECT id, workspace_id, decision_id, placement_evaluation_id, response_run_id, schema_version, status, input_hash, snapshot, evidence_ledger, proposed_actions, json_artifact, html_artifact, pdf_artifact, json_sha256, html_sha256, pdf_sha256, created_at FROM pfas.decision_packages
WHERE decision_id = $1 AND workspace_id = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetLatestDecisionPackageParams struct {
	DecisionID  uuid.UUID `json:"decision_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetLatestDecisionPackage(ctx context.Context, arg GetLatestDecisionPackageParams) (PfasDecisionPackage, error) {
	row := q.db.QueryRow(ctx, getLatestDecisionPackage, arg.DecisionID, arg.WorkspaceID)
	var i PfasDecisionPackage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionID,
		&i.PlacementEvaluationID,
		&i.ResponseRunID,
		&i.SchemaVersion,
		&i.Status,
		&i.InputHash,
		&i.Snapshot,
		&i.EvidenceLedger,
		&i.ProposedActions,
		&i.JsonArtifact,
		&i.HtmlArtifact,
		&i.PdfArtifact,
		&i.JsonSha256,
		&i.HtmlSha256,
		&i.PdfSha256,
		&i.CreatedAt,
	)
	return i, err
}
