// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policy.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBatchPolicyDecision = `-- name: CreateBatchPolicyDecision :one
INSERT INTO pfas.batch_policy_decisions (
    id, workspace_id, report_id, report_version_id, rule_pack_id,
    jurisdiction, tier, matched_rule_id, explanation, blocking_reason,
    input_hash, analyte_evidence
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (report_version_id, rule_pack_id) DO NOTHING
RETURNING id, workspace_id, report_id, report_version_id, rule_pack_id, jurisdiction, tier, matched_rule_id, explanation, blocking_reason, input_hash, analyte_evidence, created_at
`

type CreateBatchPolicyDecisionParams struct {
	ID              uuid.UUID `json:"id"`
	WorkspaceID     uuid.UUID `json:"workspace_id"`
	ReportID        uuid.UUID `json:"report_id"`
	ReportVersionID uuid.UUID `json:"report_version_id"`
	RulePackID      uuid.UUID `json:"rule_pack_id"`
	Jurisdiction    string    `json:"jurisdiction"`
	Tier            string    `json:"tier"`
	MatchedRuleID   *string   `json:"matched_rule_id"`
	Explanation     string    `json:"explanation"`
	BlockingReason  *string   `json:"blocking_reason"`
	InputHash       string    `json:"input_hash"`
	AnalyteEvidence []byte    `json:"analyte_evidence"`
}

func (q *Queries) CreateBatchPolicyDecision(ctx context.Context, arg CreateBatchPolicyDecisionParams) (PfasBatchPolicyDecision, error) {
	row := q.db.QueryRow(ctx, createBatchPolicyDecision,
		arg.ID,
		arg.WorkspaceID,
		arg.ReportID,
		arg.ReportVersionID,
		arg.RulePackID,
		arg.Jurisdiction,
		arg.Tier,
		arg.MatchedRuleID,
		arg.Explanation,
		arg.BlockingReason,
		arg.InputHash,
		arg.AnalyteEvidence,
	)
	var i PfasBatchPolicyDecision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ReportID,
		&i.ReportVersionID,
		&i.RulePackID,
		&i.Jurisdiction,
		&i.Tier,
		&i.MatchedRuleID,
		&i.Explanation,
		&i.BlockingReason,
		&i.InputHash,
		&i.AnalyteEvidence,
		&i.CreatedAt,
	)
	return i, err
}

const createBatchPolicyRequirement = `-- name: CreateBatchPolicyRequirement :exec
INSERT INTO pfas.batch_policy_requirements (
    id, decision_id, position, requirement_id, title, detail, timing,
    rule_id, source_url, source_title, authority_type
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateBatchPolicyRequirementParams struct {
	ID            uuid.UUID `json:"id"`
	DecisionID    uuid.UUID `json:"decision_id"`
	Position      int32     `json:"position"`
	RequirementID string    `json:"requirement_id"`
	Title         string    `json:"title"`
	Detail        string    `json:"detail"`
	Timing        string    `json:"timing"`
	RuleID        string    `json:"rule_id"`
	SourceUrl     string    `json:"source_url"`
	SourceTitle   string    `json:"source_title"`
	AuthorityType string    `json:"authority_type"`
}

func (q *Queries) CreateBatchPolicyRequirement(ctx context.Context, arg CreateBatchPolicyRequirementParams) error {
	_, err := q.db.Exec(ctx, createBatchPolicyRequirement,
		arg.ID,
		arg.DecisionID,
		arg.Position,
		arg.RequirementID,
		arg.Title,
		arg.Detail,
		arg.Timing,
		arg.RuleID,
		arg.SourceUrl,
		arg.SourceTitle,
		arg.AuthorityType,
	)
	return err
}

const getBatchPolicyDecisionByVersion = `-- name: GetBatchPolicyDecisionByVersion :one
SELECT id, workspace_id, report_id, report_version_id, rule_pack_id, jurisdiction, tier, matched_rule_id, explanation, blocking_reason, input_hash, analyte_evidence, created_at FROM pfas.batch_policy_decisions
WHERE report_version_id = $1 AND rule_pack_id = $2
`

type GetBatchPolicyDecisionByVersionParams struct {
	ReportVersionID uuid.UUID `json:"report_version_id"`
	RulePackID      uuid.UUID `json:"rule_pack_id"`
}

func (q *Queries) GetBatchPolicyDecisionByVersion(ctx context.Context, arg GetBatchPolicyDecisionByVersionParams) (PfasBatchPolicyDecision, error) {
	row := q.db.QueryRow(ctx, getBatchPolicyDecisionByVersion, arg.ReportVersionID, arg.RulePackID)
	var i PfasBatchPolicyDecision
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ReportID,
		&i.ReportVersionID,
		&i.RulePackID,
		&i.Jurisdiction,
		&i.Tier,
		&i.MatchedRuleID,
		&i.Explanation,
		&i.BlockingReason,
		&i.InputHash,
		&i.AnalyteEvidence,
		&i.CreatedAt,
	)
	return i, err
}

const getBatchPolicyDecisionForWorkspace = `-- name: GetBatchPolicyDecisionForWorkspace :one
SELECT d.id, d.workspace_id, d.report_id, d.report_version_id, d.rule_pack_id, d.jurisdiction, d.tier, d.matched_rule_id, d.explanation, d.blocking_reason, d.input_hash, d.analyte_evidence, d.created_at, f.name AS facility_name, b.identifier AS batch_identifier,
       v.version AS report_version
FROM pfas.batch_policy_decisions d
JOIN pfas.lab_reports r ON r.id = d.report_id AND r.workspace_id = d.workspace_id
JOIN pfas.facilities f ON f.id = r.facility_id AND f.workspace_id = r.workspace_id
JOIN pfas.biosolids_batches b ON b.id = r.batch_id AND b.workspace_id = r.workspace_id
JOIN pfas.lab_report_versions v ON v.id = d.report_version_id AND v.report_id = d.report_id
JOIN pfas.policy_rule_packs p ON p.id = d.rule_pack_id
WHERE d.report_id = $1 AND d.workspace_id = $2
  AND p.review_status = 'ACTIVE'
  AND p.effective_from <= CURRENT_DATE
  AND (p.effective_to IS NULL OR p.effective_to >= CURRENT_DATE)
ORDER BY p.effective_from DESC, p.version DESC
LIMIT 1
`

type GetBatchPolicyDecisionForWorkspaceParams struct {
	ReportID    uuid.UUID `json:"report_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetBatchPolicyDecisionForWorkspaceRow struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	ReportID        uuid.UUID          `json:"report_id"`
	ReportVersionID uuid.UUID          `json:"report_version_id"`
	RulePackID      uuid.UUID          `json:"rule_pack_id"`
	Jurisdiction    string             `json:"jurisdiction"`
	Tier            string             `json:"tier"`
	MatchedRuleID   *string            `json:"matched_rule_id"`
	Explanation     string             `json:"explanation"`
	BlockingReason  *string            `json:"blocking_reason"`
	InputHash       string             `json:"input_hash"`
	AnalyteEvidence []byte             `json:"analyte_evidence"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	FacilityName    string             `json:"facility_name"`
	BatchIdentifier string             `json:"batch_identifier"`
	ReportVersion   int32              `json:"report_version"`
}

func (q *Queries) GetBatchPolicyDecisionForWorkspace(ctx context.Context, arg GetBatchPolicyDecisionForWorkspaceParams) (GetBatchPolicyDecisionForWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getBatchPolicyDecisionForWorkspace, arg.ReportID, arg.WorkspaceID)
	var i GetBatchPolicyDecisionForWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ReportID,
		&i.ReportVersionID,
		&i.RulePackID,
		&i.Jurisdiction,
		&i.Tier,
		&i.MatchedRuleID,
		&i.Explanation,
		&i.BlockingReason,
		&i.InputHash,
		&i.AnalyteEvidence,
		&i.CreatedAt,
		&i.FacilityName,
		&i.BatchIdentifier,
		&i.ReportVersion,
	)
	return i, err
}

const getConfirmedReportForClassification = `-- name: GetConfirmedReportForClassification :one
SELECT r.id AS report_id, r.workspace_id, r.status AS report_status,
       r.current_version, v.id AS report_version_id, v.status AS version_status,
       v.matrix, v.method, v.basis, f.name AS facility_name, f.jurisdiction,
       b.identifier AS batch_identifier
FROM pfas.lab_reports r
JOIN pfas.lab_report_versions v
  ON v.report_id = r.id AND v.version = r.current_version
JOIN pfas.facilities f
  ON f.id = r.facility_id AND f.workspace_id = r.workspace_id
JOIN pfas.biosolids_batches b
  ON b.id = r.batch_id AND b.workspace_id = r.workspace_id
WHERE r.id = $1 AND r.workspace_id = $2
`

type GetConfirmedReportForClassificationParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetConfirmedReportForClassificationRow struct {
	ReportID        uuid.UUID `json:"report_id"`
	WorkspaceID     uuid.UUID `json:"workspace_id"`
	ReportStatus    string    `json:"report_status"`
	CurrentVersion  int32     `json:"current_version"`
	ReportVersionID uuid.UUID `json:"report_version_id"`
	VersionStatus   string    `json:"version_status"`
	Matrix          *string   `json:"matrix"`
	Method          *string   `json:"method"`
	Basis           *string   `json:"basis"`
	FacilityName    string    `json:"facility_name"`
	Jurisdiction    string    `json:"jurisdiction"`
	BatchIdentifier string    `json:"batch_identifier"`
}

func (q *Queries) GetConfirmedReportForClassification(ctx context.Context, arg GetConfirmedReportForClassificationParams) (GetConfirmedReportForClassificationRow, error) {
	row := q.db.QueryRow(ctx, getConfirmedReportForClassification, arg.ID, arg.WorkspaceID)
	var i GetConfirmedReportForClassificationRow
	err := row.Scan(
		&i.ReportID,
		&i.WorkspaceID,
		&i.ReportStatus,
		&i.CurrentVersion,
		&i.ReportVersionID,
		&i.VersionStatus,
		&i.Matrix,
		&i.Method,
		&i.Basis,
		&i.FacilityName,
		&i.Jurisdiction,
		&i.BatchIdentifier,
	)
	return i, err
}

const getPolicyRulePackByCodeVersion = `-- name: GetPolicyRulePackByCodeVersion :one
SELECT id, code, version, jurisdiction, authority_type, effective_from, effective_to, retrieved_at, source_url, source_title, review_status, reviewed_by, reviewed_at, checksum, explanation, definition, created_at FROM pfas.policy_rule_packs
WHERE code = $1 AND version = $2
`

type GetPolicyRulePackByCodeVersionParams struct {
	Code    string `json:"code"`
	Version string `json:"version"`
}

func (q *Queries) GetPolicyRulePackByCodeVersion(ctx context.Context, arg GetPolicyRulePackByCodeVersionParams) (PfasPolicyRulePack, error) {
	row := q.db.QueryRow(ctx, getPolicyRulePackByCodeVersion, arg.Code, arg.Version)
	var i PfasPolicyRulePack
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Version,
		&i.Jurisdiction,
		&i.AuthorityType,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.RetrievedAt,
		&i.SourceUrl,
		&i.SourceTitle,
		&i.ReviewStatus,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Checksum,
		&i.Explanation,
		&i.Definition,
		&i.CreatedAt,
	)
	return i, err
}

const getPolicyRulePackByID = `-- name: GetPolicyRulePackByID :one
SELECT id, code, version, jurisdiction, authority_type, effective_from, effective_to, retrieved_at, source_url, source_title, review_status, reviewed_by, reviewed_at, checksum, explanation, definition, created_at FROM pfas.policy_rule_packs WHERE id = $1
`

func (q *Queries) GetPolicyRulePackByID(ctx context.Context, id uuid.UUID) (PfasPolicyRulePack, error) {
	row := q.db.QueryRow(ctx, getPolicyRulePackByID, id)
	var i PfasPolicyRulePack
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Version,
		&i.Jurisdiction,
		&i.AuthorityType,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.RetrievedAt,
		&i.SourceUrl,
		&i.SourceTitle,
		&i.ReviewStatus,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Checksum,
		&i.Explanation,
		&i.Definition,
		&i.CreatedAt,
	)
	return i, err
}

const insertPolicyRulePack = `-- name: InsertPolicyRulePack :execrows
INSERT INTO pfas.policy_rule_packs (
    id, code, version, jurisdiction, authority_type, effective_from,
    retrieved_at, source_url, source_title, review_status,
    reviewed_by, reviewed_at, checksum, explanation, definition
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (code, version) DO NOTHING
`

type InsertPolicyRulePackParams struct {
	ID            uuid.UUID          `json:"id"`
	Code          string             `json:"code"`
	Version       string             `json:"version"`
	Jurisdiction  string             `json:"jurisdiction"`
	AuthorityType string             `json:"authority_type"`
	EffectiveFrom pgtype.Date        `json:"effective_from"`
	RetrievedAt   pgtype.Timestamptz `json:"retrieved_at"`
	SourceUrl     string             `json:"source_url"`
	SourceTitle   string             `json:"source_title"`
	ReviewStatus  string             `json:"review_status"`
	ReviewedBy    *string            `json:"reviewed_by"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	Checksum      string             `json:"checksum"`
	Explanation   string             `json:"explanation"`
	Definition    []byte             `json:"definition"`
}

func (q *Queries) InsertPolicyRulePack(ctx context.Context, arg InsertPolicyRulePackParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPolicyRulePack,
		arg.ID,
		arg.Code,
		arg.Version,
		arg.Jurisdiction,
		arg.AuthorityType,
		arg.EffectiveFrom,
		arg.RetrievedAt,
		arg.SourceUrl,
		arg.SourceTitle,
		arg.ReviewStatus,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.Checksum,
		arg.Explanation,
		arg.Definition,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listApplicablePolicyRulePacks = `-- name: ListApplicablePolicyRulePacks :many
SELECT id, code, version, jurisdiction, authority_type, effective_from, effective_to, retrieved_at, source_url, source_title, review_status, reviewed_by, reviewed_at, checksum, explanation, definition, created_at FROM pfas.policy_rule_packs
WHERE jurisdiction = $1
  AND review_status = 'ACTIVE'
  AND effective_from <= $2
  AND (effective_to IS NULL OR effective_to >= $2)
ORDER BY effective_from DESC, version DESC
`

type ListApplicablePolicyRulePacksParams struct {
	Jurisdiction  string      `json:"jurisdiction"`
	EffectiveFrom pgtype.Date `json:"effective_from"`
}

func (q *Queries) ListApplicablePolicyRulePacks(ctx context.Context, arg ListApplicablePolicyRulePacksParams) ([]PfasPolicyRulePack, error) {
	rows, err := q.db.Query(ctx, listApplicablePolicyRulePacks, arg.Jurisdiction, arg.EffectiveFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasPolicyRulePack{}
	for rows.Next() {
		var i PfasPolicyRulePack
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Version,
			&i.Jurisdiction,
			&i.AuthorityType,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.RetrievedAt,
			&i.SourceUrl,
			&i.SourceTitle,
			&i.ReviewStatus,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Checksum,
			&i.Explanation,
			&i.Definition,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBatchPolicyRequirements = `-- name: ListBatchPolicyRequirements :many
SELECT id, decision_id, position, requirement_id, title, detail, timing, rule_id, source_url, source_title, authority_type, created_at FROM pfas.batch_policy_requirements
WHERE decision_id = $1
ORDER BY position
`

func (q *Queries) ListBatchPolicyRequirements(ctx context.Context, decisionID uuid.UUID) ([]PfasBatchPolicyRequirement, error) {
	rows, err := q.db.Query(ctx, listBatchPolicyRequirements, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasBatchPolicyRequirement{}
	for rows.Next() {
		var i PfasBatchPolicyRequirement
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.Position,
			&i.RequirementID,
			&i.Title,
			&i.Detail,
			&i.Timing,
			&i.RuleID,
			&i.SourceUrl,
			&i.SourceTitle,
			&i.AuthorityType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfirmedAnalytesForClassification = `-- name: ListConfirmedAnalytesForClassification :many
SELECT canonical_analyte, result_text, is_non_detect,
       CAST(COALESCE(normalized_value_ug_kg_dry::text, '') AS text) AS normalized_value_ug_kg_dry,
       CAST(COALESCE(normalized_reporting_limit_ug_kg_dry::text,
                     normalized_detection_limit_ug_kg_dry::text, '') AS text) AS upper_bound_ug_kg_dry,
       source_page
FROM pfas.analyte_results
WHERE report_id = $1 AND version_id = $2
ORDER BY canonical_analyte
`

type ListConfirmedAnalytesForClassificationParams struct {
	ReportID  uuid.UUID `json:"report_id"`
	VersionID uuid.UUID `json:"version_id"`
}

type ListConfirmedAnalytesForClassificationRow struct {
	CanonicalAnalyte       string `json:"canonical_analyte"`
	ResultText             string `json:"result_text"`
	IsNonDetect            bool   `json:"is_non_detect"`
	NormalizedValueUgKgDry string `json:"normalized_value_ug_kg_dry"`
	UpperBoundUgKgDry      string `json:"upper_bound_ug_kg_dry"`
	SourcePage             int32  `json:"source_page"`
}

func (q *Queries) ListConfirmedAnalytesForClassification(ctx context.Context, arg ListConfirmedAnalytesForClassificationParams) ([]ListConfirmedAnalytesForClassificationRow, error) {
	rows, err := q.db.Query(ctx, listConfirmedAnalytesForClassification, arg.ReportID, arg.VersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfirmedAnalytesForClassificationRow{}
	for rows.Next() {
		var i ListConfirmedAnalytesForClassificationRow
		if err := rows.Scan(
			&i.CanonicalAnalyte,
			&i.ResultText,
			&i.IsNonDetect,
			&i.NormalizedValueUgKgDry,
			&i.UpperBoundUgKgDry,
			&i.SourcePage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
