// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: response.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearResponseRunOutputs = `-- name: ClearResponseRunOutputs :exec
WITH deleted_tasks AS (DELETE FROM pfas.response_tasks WHERE run_id = $1),
deleted_evidence AS (DELETE FROM pfas.response_evidence WHERE run_id = $1),
deleted_leads AS (DELETE FROM pfas.investigation_leads WHERE run_id = $1),
deleted_candidates AS (DELETE FROM pfas.alternative_management_candidates WHERE run_id = $1)
DELETE FROM pfas.response_data_gaps WHERE response_data_gaps.run_id = $1
`

func (q *Queries) ClearResponseRunOutputs(ctx context.Context, runID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearResponseRunOutputs, runID)
	return err
}

const completeResponseRun = `-- name: CompleteResponseRun :exec
UPDATE pfas.response_runs
SET status = $2, completed_at = now(), updated_at = now()
WHERE id = $1
`

type CompleteResponseRunParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) CompleteResponseRun(ctx context.Context, arg CompleteResponseRunParams) error {
	_, err := q.db.Exec(ctx, completeResponseRun, arg.ID, arg.Status)
	return err
}

const confirmFacilityLocationLookup = `-- name: ConfirmFacilityLocationLookup :one
UPDATE pfas.facility_location_lookups
SET confirmed_at = COALESCE(confirmed_at, now())
WHERE id = $1 AND workspace_id = $2 AND disposition = 'resolved'
  AND latitude IS NOT NULL AND longitude IS NOT NULL AND state = 'MI'
RETURNING id, workspace_id, facility_id, input, input_kind, request_hash, response_hash, request_id, source_url, disposition, latitude, longitude, resolved_address, state, county, confidence, match_method, candidates, reason, hint, evidence, fetched_at, confirmed_at, created_at
`

type ConfirmFacilityLocationLookupParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) ConfirmFacilityLocationLookup(ctx context.Context, arg ConfirmFacilityLocationLookupParams) (PfasFacilityLocationLookup, error) {
	row := q.db.QueryRow(ctx, confirmFacilityLocationLookup, arg.ID, arg.WorkspaceID)
	var i PfasFacilityLocationLookup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FacilityID,
		&i.Input,
		&i.InputKind,
		&i.RequestHash,
		&i.ResponseHash,
		&i.RequestID,
		&i.SourceUrl,
		&i.Disposition,
		&i.Latitude,
		&i.Longitude,
		&i.ResolvedAddress,
		&i.State,
		&i.County,
		&i.Confidence,
		&i.MatchMethod,
		&i.Candidates,
		&i.Reason,
		&i.Hint,
		&i.Evidence,
		&i.FetchedAt,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAlternativeCandidate = `-- name: CreateAlternativeCandidate :exec
INSERT INTO pfas.alternative_management_candidates (
    run_id, position, wds_id, facility_name, facility_type, address, city, county,
    latitude, longitude, disposal_area_status, straightline_distance_km,
    route_status, driving_distance_km, duration_minutes, route_note, source_url
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
`

type CreateAlternativeCandidateParams struct {
	RunID                  uuid.UUID `json:"run_id"`
	Position               int32     `json:"position"`
	WdsID                  string    `json:"wds_id"`
	FacilityName           string    `json:"facility_name"`
	FacilityType           string    `json:"facility_type"`
	Address                string    `json:"address"`
	City                   string    `json:"city"`
	County                 string    `json:"county"`
	Latitude               float64   `json:"latitude"`
	Longitude              float64   `json:"longitude"`
	DisposalAreaStatus     string    `json:"disposal_area_status"`
	StraightlineDistanceKm float64   `json:"straightline_distance_km"`
	RouteStatus            string    `json:"route_status"`
	DrivingDistanceKm      *float64  `json:"driving_distance_km"`
	DurationMinutes        *float64  `json:"duration_minutes"`
	RouteNote              *string   `json:"route_note"`
	SourceUrl              string    `json:"source_url"`
}

func (q *Queries) CreateAlternativeCandidate(ctx context.Context, arg CreateAlternativeCandidateParams) error {
	_, err := q.db.Exec(ctx, createAlternativeCandidate,
		arg.RunID,
		arg.Position,
		arg.WdsID,
		arg.FacilityName,
		arg.FacilityType,
		arg.Address,
		arg.City,
		arg.County,
		arg.Latitude,
		arg.Longitude,
		arg.DisposalAreaStatus,
		arg.StraightlineDistanceKm,
		arg.RouteStatus,
		arg.DrivingDistanceKm,
		arg.DurationMinutes,
		arg.RouteNote,
		arg.SourceUrl,
	)
	return err
}

const createFacilityLocationLookup = `-- name: CreateFacilityLocationLookup :one
INSERT INTO pfas.facility_location_lookups (
    id, workspace_id, facility_id, input, input_kind, request_hash, response_hash,
    request_id, source_url, disposition, latitude, longitude, resolved_address,
    state, county, confidence, match_method, candidates, reason, hint, evidence, fetched_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
        $14, $15, $16, $17, $18, $19, $20, $21, $22)
RETURNING id, workspace_id, facility_id, input, input_kind, request_hash, response_hash, request_id, source_url, disposition, latitude, longitude, resolved_address, state, county, confidence, match_method, candidates, reason, hint, evidence, fetched_at, confirmed_at, created_at
`

type CreateFacilityLocationLookupParams struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	FacilityID      uuid.UUID          `json:"facility_id"`
	Input           string             `json:"input"`
	InputKind       string             `json:"input_kind"`
	RequestHash     string             `json:"request_hash"`
	ResponseHash    string             `json:"response_hash"`
	RequestID       *string            `json:"request_id"`
	SourceUrl       string             `json:"source_url"`
	Disposition     string             `json:"disposition"`
	Latitude        *float64           `json:"latitude"`
	Longitude       *float64           `json:"longitude"`
	ResolvedAddress *string            `json:"resolved_address"`
	State           *string            `json:"state"`
	County          *string            `json:"county"`
	Confidence      *float64           `json:"confidence"`
	MatchMethod     *string            `json:"match_method"`
	Candidates      []byte             `json:"candidates"`
	Reason          *string            `json:"reason"`
	Hint            *string            `json:"hint"`
	Evidence        []byte             `json:"evidence"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) CreateFacilityLocationLookup(ctx context.Context, arg CreateFacilityLocationLookupParams) (PfasFacilityLocationLookup, error) {
	row := q.db.QueryRow(ctx, createFacilityLocationLookup,
		arg.ID,
		arg.WorkspaceID,
		arg.FacilityID,
		arg.Input,
		arg.InputKind,
		arg.RequestHash,
		arg.ResponseHash,
		arg.RequestID,
		arg.SourceUrl,
		arg.Disposition,
		arg.Latitude,
		arg.Longitude,
		arg.ResolvedAddress,
		arg.State,
		arg.County,
		arg.Confidence,
		arg.MatchMethod,
		arg.Candidates,
		arg.Reason,
		arg.Hint,
		arg.Evidence,
		arg.FetchedAt,
	)
	var i PfasFacilityLocationLookup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FacilityID,
		&i.Input,
		&i.InputKind,
		&i.RequestHash,
		&i.ResponseHash,
		&i.RequestID,
		&i.SourceUrl,
		&i.Disposition,
		&i.Latitude,
		&i.Longitude,
		&i.ResolvedAddress,
		&i.State,
		&i.County,
		&i.Confidence,
		&i.MatchMethod,
		&i.Candidates,
		&i.Reason,
		&i.Hint,
		&i.Evidence,
		&i.FetchedAt,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvestigationLead = `-- name: CreateInvestigationLead :exec
INSERT INTO pfas.investigation_leads (
    run_id, position, registry_id, facility_name, city, state, naics_codes,
    evidence_tier, evidence_label, rationale, caveat, source_url
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateInvestigationLeadParams struct {
	RunID         uuid.UUID `json:"run_id"`
	Position      int32     `json:"position"`
	RegistryID    string    `json:"registry_id"`
	FacilityName  string    `json:"facility_name"`
	City          *string   `json:"city"`
	State         *string   `json:"state"`
	NaicsCodes    []byte    `json:"naics_codes"`
	EvidenceTier  int32     `json:"evidence_tier"`
	EvidenceLabel string    `json:"evidence_label"`
	Rationale     string    `json:"rationale"`
	Caveat        string    `json:"caveat"`
	SourceUrl     string    `json:"source_url"`
}

func (q *Queries) CreateInvestigationLead(ctx context.Context, arg CreateInvestigationLeadParams) error {
	_, err := q.db.Exec(ctx, createInvestigationLead,
		arg.RunID,
		arg.Position,
		arg.RegistryID,
		arg.FacilityName,
		arg.City,
		arg.State,
		arg.NaicsCodes,
		arg.EvidenceTier,
		arg.EvidenceLabel,
		arg.Rationale,
		arg.Caveat,
		arg.SourceUrl,
	)
	return err
}

const createResponseDataGap = `-- name: CreateResponseDataGap :exec
INSERT INTO pfas.response_data_gaps (run_id, code, detail, resolution, critical)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (run_id, code) DO UPDATE
SET detail = EXCLUDED.detail, resolution = EXCLUDED.resolution, critical = EXCLUDED.critical
`

type CreateResponseDataGapParams struct {
	RunID      uuid.UUID `json:"run_id"`
	Code       string    `json:"code"`
	Detail     string    `json:"detail"`
	Resolution string    `json:"resolution"`
	Critical   bool      `json:"critical"`
}

func (q *Queries) CreateResponseDataGap(ctx context.Context, arg CreateResponseDataGapParams) error {
	_, err := q.db.Exec(ctx, createResponseDataGap,
		arg.RunID,
		arg.Code,
		arg.Detail,
		arg.Resolution,
		arg.Critical,
	)
	return err
}

const createResponseEvidence = `-- name: CreateResponseEvidence :exec
INSERT INTO pfas.response_evidence (
    id, run_id, provider, kind, status, title, summary, data, source_url,
    source_vintage, request_hash, response_hash, request_id, fetched_at, caveat
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type CreateResponseEvidenceParams struct {
	ID            uuid.UUID          `json:"id"`
	RunID         uuid.UUID          `json:"run_id"`
	Provider      string             `json:"provider"`
	Kind          string             `json:"kind"`
	Status        string             `json:"status"`
	Title         string             `json:"title"`
	Summary       string             `json:"summary"`
	Data          []byte             `json:"data"`
	SourceUrl     string             `json:"source_url"`
	SourceVintage *string            `json:"source_vintage"`
	RequestHash   *string            `json:"request_hash"`
	ResponseHash  *string            `json:"response_hash"`
	RequestID     *string            `json:"request_id"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
	Caveat        string             `json:"caveat"`
}

func (q *Queries) CreateResponseEvidence(ctx context.Context, arg CreateResponseEvidenceParams) error {
	_, err := q.db.Exec(ctx, createResponseEvidence,
		arg.ID,
		arg.RunID,
		arg.Provider,
		arg.Kind,
		arg.Status,
		arg.Title,
		arg.Summary,
		arg.Data,
		arg.SourceUrl,
		arg.SourceVintage,
		arg.RequestHash,
		arg.ResponseHash,
		arg.RequestID,
		arg.FetchedAt,
		arg.Caveat,
	)
	return err
}

const createResponseRun = `-- name: CreateResponseRun :one
INSERT INTO pfas.response_runs (
    id, workspace_id, decision_id, facility_location_id, tier, status,
    input_hash, policy_source_url, policy_version
)
VALUES ($1, $2, $3, $4, $5, 'QUEUED', $6, $7, $8)
ON CONFLICT (decision_id, input_hash) DO NOTHING
RETURNING id, workspace_id, decision_id, facility_location_id, tier, status, input_hash, policy_source_url, policy_version, started_at, completed_at, failure_code, failure_detail, created_at, updated_at
`

type CreateResponseRunParams struct {
	ID                 uuid.UUID `json:"id"`
	WorkspaceID        uuid.UUID `json:"workspace_id"`
	DecisionID         uuid.UUID `json:"decision_id"`
	FacilityLocationID uuid.UUID `json:"facility_location_id"`
	Tier               string    `json:"tier"`
	InputHash          string    `json:"input_hash"`
	PolicySourceUrl    string    `json:"policy_source_url"`
	PolicyVersion      string    `json:"policy_version"`
}

func (q *Queries) CreateResponseRun(ctx context.Context, arg CreateResponseRunParams) (PfasResponseRun, error) {
	row := q.db.QueryRow(ctx, createResponseRun,
		arg.ID,
		arg.WorkspaceID,
		arg.DecisionID,
		arg.FacilityLocationID,
		arg.Tier,
		arg.InputHash,
		arg.PolicySourceUrl,
		arg.PolicyVersion,
	)
	var i PfasResponseRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionID,
		&i.FacilityLocationID,
		&i.Tier,
		&i.Status,
		&i.InputHash,
		&i.PolicySourceUrl,
		&i.PolicyVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createResponseTask = `-- name: CreateResponseTask :exec
INSERT INTO pfas.response_tasks (run_id, position, code, category, title, detail, timing, state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateResponseTaskParams struct {
	RunID    uuid.UUID `json:"run_id"`
	Position int32     `json:"position"`
	Code     string    `json:"code"`
	Category string    `json:"category"`
	Title    string    `json:"title"`
	Detail   string    `json:"detail"`
	Timing   string    `json:"timing"`
	State    string    `json:"state"`
}

func (q *Queries) CreateResponseTask(ctx context.Context, arg CreateResponseTaskParams) error {
	_, err := q.db.Exec(ctx, createResponseTask,
		arg.RunID,
		arg.Position,
		arg.Code,
		arg.Category,
		arg.Title,
		arg.Detail,
		arg.Timing,
		arg.State,
	)
	return err
}

const failResponseRun = `-- name: FailResponseRun :exec
UPDATE pfas.response_runs
SET status = 'FAILED', failure_code = $2, failure_detail = $3,
    completed_at = now(), updated_at = now()
WHERE id = $1
`

type FailResponseRunParams struct {
	ID            uuid.UUID `json:"id"`
	FailureCode   *string   `json:"failure_code"`
	FailureDetail *string   `json:"failure_detail"`
}

func (q *Queries) FailResponseRun(ctx context.Context, arg FailResponseRunParams) error {
	_, err := q.db.Exec(ctx, failResponseRun, arg.ID, arg.FailureCode, arg.FailureDetail)
	return err
}

const getActiveResponseRun = `-- name: GetActiveResponseRun :one
SELECT id, workspace_id, decision_id, facility_location_id, tier, status, input_hash, policy_source_url, policy_version, started_at, completed_at, failure_code, failure_detail, created_at, updated_at FROM pfas.response_runs
WHERE decision_id = $1 AND workspace_id = $2 AND status IN ('QUEUED', 'RUNNING')
ORDER BY created_at DESC, id DESC LIMIT 1
`

type GetActiveResponseRunParams struct {
	DecisionID  uuid.UUID `json:"decision_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetActiveResponseRun(ctx context.Context, arg GetActiveResponseRunParams) (PfasResponseRun, error) {
	row := q.db.QueryRow(ctx, getActiveResponseRun, arg.DecisionID, arg.WorkspaceID)
	var i PfasResponseRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionID,
		&i.FacilityLocationID,
		&i.Tier,
		&i.Status,
		&i.InputHash,
		&i.PolicySourceUrl,
		&i.PolicyVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFacilityLocationLookup = `-- name: GetFacilityLocationLookup :one
SELECT id, workspace_id, facility_id, input, input_kind, request_hash, response_hash, request_id, source_url, disposition, latitude, longitude, resolved_address, state, county, confidence, match_method, candidates, reason, hint, evidence, fetched_at, confirmed_at, created_at FROM pfas.facility_location_lookups
WHERE id = $1 AND workspace_id = $2
`

type GetFacilityLocationLookupParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetFacilityLocationLookup(ctx context.Context, arg GetFacilityLocationLookupParams) (PfasFacilityLocationLookup, error) {
	row := q.db.QueryRow(ctx, getFacilityLocationLookup, arg.ID, arg.WorkspaceID)
	var i PfasFacilityLocationLookup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FacilityID,
		&i.Input,
		&i.InputKind,
		&i.RequestHash,
		&i.ResponseHash,
		&i.RequestID,
		&i.SourceUrl,
		&i.Disposition,
		&i.Latitude,
		&i.Longitude,
		&i.ResolvedAddress,
		&i.State,
		&i.County,
		&i.Confidence,
		&i.MatchMethod,
		&i.Candidates,
		&i.Reason,
		&i.Hint,
		&i.Evidence,
		&i.FetchedAt,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFacilityLocationLookupByHash = `-- name: GetFacilityLocationLookupByHash :one
SELECT id, workspace_id, facility_id, input, input_kind, request_hash, response_hash, request_id, source_url, disposition, latitude, longitude, resolved_address, state, county, confidence, match_method, candidates, reason, hint, evidence, fetched_at, confirmed_at, created_at FROM pfas.facility_location_lookups
WHERE facility_id = $1 AND workspace_id = $2 AND request_hash = $3
`

type GetFacilityLocationLookupByHashParams struct {
	FacilityID  uuid.UUID `json:"facility_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	RequestHash string    `json:"request_hash"`
}

func (q *Queries) GetFacilityLocationLookupByHash(ctx context.Context, arg GetFacilityLocationLookupByHashParams) (PfasFacilityLocationLookup, error) {
	row := q.db.QueryRow(ctx, getFacilityLocationLookupByHash, arg.FacilityID, arg.WorkspaceID, arg.RequestHash)
	var i PfasFacilityLocationLookup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FacilityID,
		&i.Input,
		&i.InputKind,
		&i.RequestHash,
		&i.ResponseHash,
		&i.RequestID,
		&i.SourceUrl,
		&i.Disposition,
		&i.Latitude,
		&i.Longitude,
		&i.ResolvedAddress,
		&i.State,
		&i.County,
		&i.Confidence,
		&i.MatchMethod,
		&i.Candidates,
		&i.Reason,
		&i.Hint,
		&i.Evidence,
		&i.FetchedAt,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestFacilityLocationLookup = `-- name: GetLatestFacilityLocationLookup :one
SELECT lookup.id, lookup.workspace_id, lookup.facility_id, lookup.input, lookup.input_kind, lookup.request_hash, lookup.response_hash, lookup.request_id, lookup.source_url, lookup.disposition, lookup.latitude, lookup.longitude, lookup.resolved_address, lookup.state, lookup.county, lookup.confidence, lookup.match_method, lookup.candidates, lookup.reason, lookup.hint, lookup.evidence, lookup.fetched_at, lookup.confirmed_at, lookup.created_at
FROM pfas.facility_location_lookups lookup
JOIN pfas.facilities facility
  ON facility.id = lookup.facility_id AND facility.workspace_id = lookup.workspace_id
WHERE lookup.facility_id = $1 AND lookup.workspace_id = $2
ORDER BY lookup.created_at DESC, lookup.id DESC
LIMIT 1
`

type GetLatestFacilityLocationLookupParams struct {
	FacilityID  uuid.UUID `json:"facility_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetLatestFacilityLocationLookup(ctx context.Context, arg GetLatestFacilityLocationLookupParams) (PfasFacilityLocationLookup, error) {
	row := q.db.QueryRow(ctx, getLatestFacilityLocationLookup, arg.FacilityID, arg.WorkspaceID)
	var i PfasFacilityLocationLookup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FacilityID,
		&i.Input,
		&i.InputKind,
		&i.RequestHash,
		&i.ResponseHash,
		&i.RequestID,
		&i.SourceUrl,
		&i.Disposition,
		&i.Latitude,
		&i.Longitude,
		&i.ResolvedAddress,
		&i.State,
		&i.County,
		&i.Confidence,
		&i.MatchMethod,
		&i.Candidates,
		&i.Reason,
		&i.Hint,
		&i.Evidence,
		&i.FetchedAt,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestResponseRun = `-- name: GetLatestResponseRun :one
SELECT run.id, run.workspace_id, run.decision_id, run.facility_location_id, run.tier, run.status, run.input_hash, run.policy_source_url, run.policy_version, run.started_at, run.completed_at, run.failure_code, run.failure_detail, run.created_at, run.updated_at, facility.name AS facility_name, batch.identifier AS batch_identifier,
       location.resolved_address, location.latitude, location.longitude,
       location.confidence AS location_confidence, location.source_url AS location_source_url,
       location.fetched_at AS location_fetched_at
FROM pfas.response_runs run
JOIN pfas.batch_policy_decisions decision
  ON decision.id = run.decision_id AND decision.workspace_id = run.workspace_id
JOIN pfas.lab_reports report
  ON report.id = decision.report_id AND report.workspace_id = decision.workspace_id
JOIN pfas.facilities facility
  ON facility.id = report.facility_id AND facility.workspace_id = report.workspace_id
JOIN pfas.biosolids_batches batch
  ON batch.id = report.batch_id AND batch.workspace_id = report.workspace_id
JOIN pfas.facility_location_lookups location
  ON location.id = run.facility_location_id AND location.workspace_id = run.workspace_id
WHERE run.decision_id = $1 AND run.workspace_id = $2
ORDER BY run.created_at DESC, run.id DESC LIMIT 1
`

type GetLatestResponseRunParams struct {
	DecisionID  uuid.UUID `json:"decision_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetLatestResponseRunRow struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	DecisionID         uuid.UUID          `json:"decision_id"`
	FacilityLocationID uuid.UUID          `json:"facility_location_id"`
	Tier               string             `json:"tier"`
	Status             string             `json:"status"`
	InputHash          string             `json:"input_hash"`
	PolicySourceUrl    string             `json:"policy_source_url"`
	PolicyVersion      string             `json:"policy_version"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	FailureCode        *string            `json:"failure_code"`
	FailureDetail      *string            `json:"failure_detail"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	FacilityName       string             `json:"facility_name"`
	BatchIdentifier    string             `json:"batch_identifier"`
	ResolvedAddress    *string            `json:"resolved_address"`
	Latitude           *float64           `json:"latitude"`
	Longitude          *float64           `json:"longitude"`
	LocationConfidence *float64           `json:"location_confidence"`
	LocationSourceUrl  string             `json:"location_source_url"`
	LocationFetchedAt  pgtype.Timestamptz `json:"location_fetched_at"`
}

func (q *Queries) GetLatestResponseRun(ctx context.Context, arg GetLatestResponseRunParams) (GetLatestResponseRunRow, error) {
	row := q.db.QueryRow(ctx, getLatestResponseRun, arg.DecisionID, arg.WorkspaceID)
	var i GetLatestResponseRunRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionID,
		&i.FacilityLocationID,
		&i.Tier,
		&i.Status,
		&i.InputHash,
		&i.PolicySourceUrl,
		&i.PolicyVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FacilityName,
		&i.BatchIdentifier,
		&i.ResolvedAddress,
		&i.Latitude,
		&i.Longitude,
		&i.LocationConfidence,
		&i.LocationSourceUrl,
		&i.LocationFetchedAt,
	)
	return i, err
}

const getResponseDecisionContext = `-- name: GetResponseDecisionContext :one
SELECT decision.id, decision.workspace_id, decision.tier, decision.input_hash AS decision_input_hash,
       report.facility_id, facility.name AS facility_name, batch.identifier AS batch_identifier,
       pack.version AS policy_version, pack.source_url AS policy_source_url
FROM pfas.batch_policy_decisions decision
JOIN pfas.lab_reports report
  ON report.id = decision.report_id AND report.workspace_id = decision.workspace_id
JOIN pfas.facilities facility
  ON facility.id = report.facility_id AND facility.workspace_id = report.workspace_id
JOIN pfas.biosolids_batches batch
  ON batch.id = report.batch_id AND batch.workspace_id = report.workspace_id
JOIN pfas.policy_rule_packs pack ON pack.id = decision.rule_pack_id
WHERE decision.id = $1 AND decision.workspace_id = $2
`

type GetResponseDecisionContextParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetResponseDecisionContextRow struct {
	ID                uuid.UUID `json:"id"`
	WorkspaceID       uuid.UUID `json:"workspace_id"`
	Tier              string    `json:"tier"`
	DecisionInputHash string    `json:"decision_input_hash"`
	FacilityID        uuid.UUID `json:"facility_id"`
	FacilityName      string    `json:"facility_name"`
	BatchIdentifier   string    `json:"batch_identifier"`
	PolicyVersion     string    `json:"policy_version"`
	PolicySourceUrl   string    `json:"policy_source_url"`
}

func (q *Queries) GetResponseDecisionContext(ctx context.Context, arg GetResponseDecisionContextParams) (GetResponseDecisionContextRow, error) {
	row := q.db.QueryRow(ctx, getResponseDecisionContext, arg.ID, arg.WorkspaceID)
	var i GetResponseDecisionContextRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Tier,
		&i.DecisionInputHash,
		&i.FacilityID,
		&i.FacilityName,
		&i.BatchIdentifier,
		&i.PolicyVersion,
		&i.PolicySourceUrl,
	)
	return i, err
}

const getResponseRun = `-- name: GetResponseRun :one
SELECT run.id, run.workspace_id, run.decision_id, run.facility_location_id, run.tier, run.status, run.input_hash, run.policy_source_url, run.policy_version, run.started_at, run.completed_at, run.failure_code, run.failure_detail, run.created_at, run.updated_at, facility.name AS facility_name, batch.identifier AS batch_identifier,
       location.resolved_address, location.latitude, location.longitude,
       location.confidence AS location_confidence, location.source_url AS location_source_url,
       location.fetched_at AS location_fetched_at
FROM pfas.response_runs run
JOIN pfas.batch_policy_decisions decision
  ON decision.id = run.decision_id AND decision.workspace_id = run.workspace_id
JOIN pfas.lab_reports report
  ON report.id = decision.report_id AND report.workspace_id = decision.workspace_id
JOIN pfas.facilities facility
  ON facility.id = report.facility_id AND facility.workspace_id = report.workspace_id
JOIN pfas.biosolids_batches batch
  ON batch.id = report.batch_id AND batch.workspace_id = report.workspace_id
JOIN pfas.facility_location_lookups location
  ON location.id = run.facility_location_id AND location.workspace_id = run.workspace_id
WHERE run.id = $1 AND run.workspace_id = $2
`

type GetResponseRunParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetResponseRunRow struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	DecisionID         uuid.UUID          `json:"decision_id"`
	FacilityLocationID uuid.UUID          `json:"facility_location_id"`
	Tier               string             `json:"tier"`
	Status             string             `json:"status"`
	InputHash          string             `json:"input_hash"`
	PolicySourceUrl    string             `json:"policy_source_url"`
	PolicyVersion      string             `json:"policy_version"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	FailureCode        *string            `json:"failure_code"`
	FailureDetail      *string            `json:"failure_detail"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	FacilityName       string             `json:"facility_name"`
	BatchIdentifier    string             `json:"batch_identifier"`
	ResolvedAddress    *string            `json:"resolved_address"`
	Latitude           *float64           `json:"latitude"`
	Longitude          *float64           `json:"longitude"`
	LocationConfidence *float64           `json:"location_confidence"`
	LocationSourceUrl  string             `json:"location_source_url"`
	LocationFetchedAt  pgtype.Timestamptz `json:"location_fetched_at"`
}

func (q *Queries) GetResponseRun(ctx context.Context, arg GetResponseRunParams) (GetResponseRunRow, error) {
	row := q.db.QueryRow(ctx, getResponseRun, arg.ID, arg.WorkspaceID)
	var i GetResponseRunRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionID,
		&i.FacilityLocationID,
		&i.Tier,
		&i.Status,
		&i.InputHash,
		&i.PolicySourceUrl,
		&i.PolicyVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FacilityName,
		&i.BatchIdentifier,
		&i.ResolvedAddress,
		&i.Latitude,
		&i.Longitude,
		&i.LocationConfidence,
		&i.LocationSourceUrl,
		&i.LocationFetchedAt,
	)
	return i, err
}

const getResponseRunByInput = `-- name: GetResponseRunByInput :one
SELECT id, workspace_id, decision_id, facility_location_id, tier, status, input_hash, policy_source_url, policy_version, started_at, completed_at, failure_code, failure_detail, created_at, updated_at FROM pfas.response_runs
WHERE decision_id = $1 AND input_hash = $2
`

type GetResponseRunByInputParams struct {
	DecisionID uuid.UUID `json:"decision_id"`
	InputHash  string    `json:"input_hash"`
}

func (q *Queries) GetResponseRunByInput(ctx context.Context, arg GetResponseRunByInputParams) (PfasResponseRun, error) {
	row := q.db.QueryRow(ctx, getResponseRunByInput, arg.DecisionID, arg.InputHash)
	var i PfasResponseRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionID,
		&i.FacilityLocationID,
		&i.Tier,
		&i.Status,
		&i.InputHash,
		&i.PolicySourceUrl,
		&i.PolicyVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResponseRunForWork = `-- name: GetResponseRunForWork :one
SELECT run.id, run.workspace_id, run.decision_id, run.facility_location_id, run.tier, run.status, run.input_hash, run.policy_source_url, run.policy_version, run.started_at, run.completed_at, run.failure_code, run.failure_detail, run.created_at, run.updated_at, location.latitude, location.longitude, location.resolved_address,
       facility.name AS facility_name, batch.identifier AS batch_identifier
FROM pfas.response_runs run
JOIN pfas.facility_location_lookups location
  ON location.id = run.facility_location_id AND location.workspace_id = run.workspace_id
JOIN pfas.batch_policy_decisions decision
  ON decision.id = run.decision_id AND decision.workspace_id = run.workspace_id
JOIN pfas.lab_reports report
  ON report.id = decision.report_id AND report.workspace_id = decision.workspace_id
JOIN pfas.facilities facility
  ON facility.id = report.facility_id AND facility.workspace_id = report.workspace_id
JOIN pfas.biosolids_batches batch
  ON batch.id = report.batch_id AND batch.workspace_id = report.workspace_id
WHERE run.id = $1
`

type GetResponseRunForWorkRow struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	DecisionID         uuid.UUID          `json:"decision_id"`
	FacilityLocationID uuid.UUID          `json:"facility_location_id"`
	Tier               string             `json:"tier"`
	Status             string             `json:"status"`
	InputHash          string             `json:"input_hash"`
	PolicySourceUrl    string             `json:"policy_source_url"`
	PolicyVersion      string             `json:"policy_version"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	FailureCode        *string            `json:"failure_code"`
	FailureDetail      *string            `json:"failure_detail"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Latitude           *float64           `json:"latitude"`
	Longitude          *float64           `json:"longitude"`
	ResolvedAddress    *string            `json:"resolved_address"`
	FacilityName       string             `json:"facility_name"`
	BatchIdentifier    string             `json:"batch_identifier"`
}

func (q *Queries) GetResponseRunForWork(ctx context.Context, id uuid.UUID) (GetResponseRunForWorkRow, error) {
	row := q.db.QueryRow(ctx, getResponseRunForWork, id)
	var i GetResponseRunForWorkRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DecisionID,
		&i.FacilityLocationID,
		&i.Tier,
		&i.Status,
		&i.InputHash,
		&i.PolicySourceUrl,
		&i.PolicyVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
		&i.ResolvedAddress,
		&i.FacilityName,
		&i.BatchIdentifier,
	)
	return i, err
}

const listAlternativeCandidates = `-- name: ListAlternativeCandidates :many
SELECT run_id, position, wds_id, facility_name, facility_type, address, city, county, latitude, longitude, disposal_area_status, straightline_distance_km, route_status, driving_distance_km, duration_minutes, route_note, acceptance_status, executable, source_url FROM pfas.alternative_management_candidates WHERE run_id = $1 ORDER BY position
`

func (q *Queries) ListAlternativeCandidates(ctx context.Context, runID uuid.UUID) ([]PfasAlternativeManagementCandidate, error) {
	rows, err := q.db.Query(ctx, listAlternativeCandidates, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasAlternativeManagementCandidate{}
	for rows.Next() {
		var i PfasAlternativeManagementCandidate
		if err := rows.Scan(
			&i.RunID,
			&i.Position,
			&i.WdsID,
			&i.FacilityName,
			&i.FacilityType,
			&i.Address,
			&i.City,
			&i.County,
			&i.Latitude,
			&i.Longitude,
			&i.DisposalAreaStatus,
			&i.StraightlineDistanceKm,
			&i.RouteStatus,
			&i.DrivingDistanceKm,
			&i.DurationMinutes,
			&i.RouteNote,
			&i.AcceptanceStatus,
			&i.Executable,
			&i.SourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestigationLeads = `-- name: ListInvestigationLeads :many
SELECT run_id, position, registry_id, facility_name, city, state, naics_codes, evidence_tier, evidence_label, rationale, caveat, source_url FROM pfas.investigation_leads WHERE run_id = $1 ORDER BY position
`

func (q *Queries) ListInvestigationLeads(ctx context.Context, runID uuid.UUID) ([]PfasInvestigationLead, error) {
	rows, err := q.db.Query(ctx, listInvestigationLeads, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasInvestigationLead{}
	for rows.Next() {
		var i PfasInvestigationLead
		if err := rows.Scan(
			&i.RunID,
			&i.Position,
			&i.RegistryID,
			&i.FacilityName,
			&i.City,
			&i.State,
			&i.NaicsCodes,
			&i.EvidenceTier,
			&i.EvidenceLabel,
			&i.Rationale,
			&i.Caveat,
			&i.SourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResponseDataGaps = `-- name: ListResponseDataGaps :many
SELECT run_id, code, detail, resolution, critical FROM pfas.response_data_gaps WHERE run_id = $1 ORDER BY critical DESC, code
`

func (q *Queries) ListResponseDataGaps(ctx context.Context, runID uuid.UUID) ([]PfasResponseDataGap, error) {
	rows, err := q.db.Query(ctx, listResponseDataGaps, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasResponseDataGap{}
	for rows.Next() {
		var i PfasResponseDataGap
		if err := rows.Scan(
			&i.RunID,
			&i.Code,
			&i.Detail,
			&i.Resolution,
			&i.Critical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResponseEvidence = `-- name: ListResponseEvidence :many
SELECT id, run_id, provider, kind, status, title, summary, data, source_url, source_vintage, request_hash, response_hash, request_id, fetched_at, caveat FROM pfas.response_evidence WHERE run_id = $1 ORDER BY provider, kind
`

func (q *Queries) ListResponseEvidence(ctx context.Context, runID uuid.UUID) ([]PfasResponseEvidence, error) {
	rows, err := q.db.Query(ctx, listResponseEvidence, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasResponseEvidence{}
	for rows.Next() {
		var i PfasResponseEvidence
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Provider,
			&i.Kind,
			&i.Status,
			&i.Title,
			&i.Summary,
			&i.Data,
			&i.SourceUrl,
			&i.SourceVintage,
			&i.RequestHash,
			&i.ResponseHash,
			&i.RequestID,
			&i.FetchedAt,
			&i.Caveat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResponseTasks = `-- name: ListResponseTasks :many
SELECT run_id, position, code, category, title, detail, timing, state FROM pfas.response_tasks WHERE run_id = $1 ORDER BY position
`

func (q *Queries) ListResponseTasks(ctx context.Context, runID uuid.UUID) ([]PfasResponseTask, error) {
	rows, err := q.db.Query(ctx, listResponseTasks, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasResponseTask{}
	for rows.Next() {
		var i PfasResponseTask
		if err := rows.Scan(
			&i.RunID,
			&i.Position,
			&i.Code,
			&i.Category,
			&i.Title,
			&i.Detail,
			&i.Timing,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markResponseRunRunning = `-- name: MarkResponseRunRunning :exec
UPDATE pfas.response_runs
SET status = 'RUNNING', started_at = COALESCE(started_at, now()), updated_at = now()
WHERE id = $1 AND status = 'QUEUED'
`

func (q *Queries) MarkResponseRunRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markResponseRunRunning, id)
	return err
}
