// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceRun = `-- name: AdvanceRun :exec
UPDATE pfas.agent_runs
SET next_step = $2, updated_at = now()
WHERE id = $1
`

type AdvanceRunParams struct {
	ID       uuid.UUID `json:"id"`
	NextStep int16     `json:"next_step"`
}

func (q *Queries) AdvanceRun(ctx context.Context, arg AdvanceRunParams) error {
	_, err := q.db.Exec(ctx, advanceRun, arg.ID, arg.NextStep)
	return err
}

const completeRun = `-- name: CompleteRun :exec
UPDATE pfas.agent_runs
SET status = 'SUCCEEDED', next_step = 4, completed_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) CompleteRun(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, completeRun, id)
	return err
}

const completeStep = `-- name: CompleteStep :exec
UPDATE pfas.agent_steps
SET status = 'SUCCEEDED', summary = $2, completed_at = now(), updated_at = now()
WHERE id = $1
`

type CompleteStepParams struct {
	ID      uuid.UUID `json:"id"`
	Summary []byte    `json:"summary"`
}

func (q *Queries) CompleteStep(ctx context.Context, arg CompleteStepParams) error {
	_, err := q.db.Exec(ctx, completeStep, arg.ID, arg.Summary)
	return err
}

const createDataGap = `-- name: CreateDataGap :one
INSERT INTO pfas.data_gaps (id, run_id, step_id, code, detail, resolution, status)
VALUES ($1, $2, $3, $4, $5, $6, 'OPEN')
ON CONFLICT (run_id, step_id, code) DO UPDATE
SET detail = EXCLUDED.detail, resolution = EXCLUDED.resolution
RETURNING id, run_id, step_id, code, detail, resolution, status, created_at, resolved_at
`

type CreateDataGapParams struct {
	ID         uuid.UUID     `json:"id"`
	RunID      uuid.UUID     `json:"run_id"`
	StepID     uuid.NullUUID `json:"step_id"`
	Code       string        `json:"code"`
	Detail     string        `json:"detail"`
	Resolution string        `json:"resolution"`
}

func (q *Queries) CreateDataGap(ctx context.Context, arg CreateDataGapParams) (PfasDataGap, error) {
	row := q.db.QueryRow(ctx, createDataGap,
		arg.ID,
		arg.RunID,
		arg.StepID,
		arg.Code,
		arg.Detail,
		arg.Resolution,
	)
	var i PfasDataGap
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepID,
		&i.Code,
		&i.Detail,
		&i.Resolution,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO pfas.agent_runs (id, kind, status, next_step)
VALUES ($1, 'MIREYE_READINESS', 'QUEUED', 1)
RETURNING id, kind, status, next_step, created_at, started_at, completed_at, updated_at
`

func (q *Queries) CreateRun(ctx context.Context, id uuid.UUID) (PfasAgentRun, error) {
	row := q.db.QueryRow(ctx, createRun, id)
	var i PfasAgentRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.NextStep,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStep = `-- name: CreateStep :one
INSERT INTO pfas.agent_steps (id, run_id, position, tool_name, status)
VALUES ($1, $2, $3, $4, 'PENDING')
RETURNING id, run_id, position, tool_name, status, attempt_count, summary, started_at, completed_at, updated_at
`

type CreateStepParams struct {
	ID       uuid.UUID `json:"id"`
	RunID    uuid.UUID `json:"run_id"`
	Position int16     `json:"position"`
	ToolName string    `json:"tool_name"`
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) (PfasAgentStep, error) {
	row := q.db.QueryRow(ctx, createStep,
		arg.ID,
		arg.RunID,
		arg.Position,
		arg.ToolName,
	)
	var i PfasAgentStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Position,
		&i.ToolName,
		&i.Status,
		&i.AttemptCount,
		&i.Summary,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createToolCall = `-- name: CreateToolCall :one
INSERT INTO pfas.tool_calls (
    id, run_id, step_id, attempt, status, request_method, request_path,
    request_hash, response_hash, request_id, source_url, http_status,
    duration_ms, credit_cost, response_body, error_code, fetched_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, 0, $14, $15, $16
)
RETURNING id, run_id, step_id, attempt, status, request_method, request_path, request_hash, response_hash, request_id, source_url, http_status, duration_ms, credit_cost, response_body, error_code, fetched_at, created_at
`

type CreateToolCallParams struct {
	ID            uuid.UUID          `json:"id"`
	RunID         uuid.UUID          `json:"run_id"`
	StepID        uuid.UUID          `json:"step_id"`
	Attempt       int32              `json:"attempt"`
	Status        string             `json:"status"`
	RequestMethod string             `json:"request_method"`
	RequestPath   string             `json:"request_path"`
	RequestHash   string             `json:"request_hash"`
	ResponseHash  *string            `json:"response_hash"`
	RequestID     *string            `json:"request_id"`
	SourceUrl     string             `json:"source_url"`
	HttpStatus    *int32             `json:"http_status"`
	DurationMs    int64              `json:"duration_ms"`
	ResponseBody  []byte             `json:"response_body"`
	ErrorCode     *string            `json:"error_code"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) CreateToolCall(ctx context.Context, arg CreateToolCallParams) (PfasToolCall, error) {
	row := q.db.QueryRow(ctx, createToolCall,
		arg.ID,
		arg.RunID,
		arg.StepID,
		arg.Attempt,
		arg.Status,
		arg.RequestMethod,
		arg.RequestPath,
		arg.RequestHash,
		arg.ResponseHash,
		arg.RequestID,
		arg.SourceUrl,
		arg.HttpStatus,
		arg.DurationMs,
		arg.ResponseBody,
		arg.ErrorCode,
		arg.FetchedAt,
	)
	var i PfasToolCall
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepID,
		&i.Attempt,
		&i.Status,
		&i.RequestMethod,
		&i.RequestPath,
		&i.RequestHash,
		&i.ResponseHash,
		&i.RequestID,
		&i.SourceUrl,
		&i.HttpStatus,
		&i.DurationMs,
		&i.CreditCost,
		&i.ResponseBody,
		&i.ErrorCode,
		&i.FetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const failStep = `-- name: FailStep :exec
UPDATE pfas.agent_steps
SET status = 'FAILED', completed_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) FailStep(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, failStep, id)
	return err
}

const getActiveRun = `-- name: GetActiveRun :one
SELECT id, kind, status, next_step, created_at, started_at, completed_at, updated_at FROM pfas.agent_runs
WHERE kind = 'MIREYE_READINESS' AND status IN ('QUEUED', 'RUNNING')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveRun(ctx context.Context) (PfasAgentRun, error) {
	row := q.db.QueryRow(ctx, getActiveRun)
	var i PfasAgentRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.NextStep,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestRun = `-- name: GetLatestRun :one
SELECT id, kind, status, next_step, created_at, started_at, completed_at, updated_at FROM pfas.agent_runs ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestRun(ctx context.Context) (PfasAgentRun, error) {
	row := q.db.QueryRow(ctx, getLatestRun)
	var i PfasAgentRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.NextStep,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, kind, status, next_step, created_at, started_at, completed_at, updated_at FROM pfas.agent_runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id uuid.UUID) (PfasAgentRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i PfasAgentRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.NextStep,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunForUpdate = `-- name: GetRunForUpdate :one
SELECT id, kind, status, next_step, created_at, started_at, completed_at, updated_at FROM pfas.agent_runs WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRunForUpdate(ctx context.Context, id uuid.UUID) (PfasAgentRun, error) {
	row := q.db.QueryRow(ctx, getRunForUpdate, id)
	var i PfasAgentRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.NextStep,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStepForUpdate = `-- name: GetStepForUpdate :one
SELECT id, run_id, position, tool_name, status, attempt_count, summary, started_at, completed_at, updated_at FROM pfas.agent_steps WHERE run_id = $1 AND position = $2 FOR UPDATE
`

type GetStepForUpdateParams struct {
	RunID    uuid.UUID `json:"run_id"`
	Position int16     `json:"position"`
}

func (q *Queries) GetStepForUpdate(ctx context.Context, arg GetStepForUpdateParams) (PfasAgentStep, error) {
	row := q.db.QueryRow(ctx, getStepForUpdate, arg.RunID, arg.Position)
	var i PfasAgentStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Position,
		&i.ToolName,
		&i.Status,
		&i.AttemptCount,
		&i.Summary,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDataGapsForRun = `-- name: ListDataGapsForRun :many
SELECT id, run_id, step_id, code, detail, resolution, status, created_at, resolved_at FROM pfas.data_gaps WHERE run_id = $1 ORDER BY created_at
`

func (q *Queries) ListDataGapsForRun(ctx context.Context, runID uuid.UUID) ([]PfasDataGap, error) {
	rows, err := q.db.Query(ctx, listDataGapsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasDataGap{}
	for rows.Next() {
		var i PfasDataGap
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepID,
			&i.Code,
			&i.Detail,
			&i.Resolution,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepsForRun = `-- name: ListStepsForRun :many
SELECT id, run_id, position, tool_name, status, attempt_count, summary, started_at, completed_at, updated_at FROM pfas.agent_steps WHERE run_id = $1 ORDER BY position
`

func (q *Queries) ListStepsForRun(ctx context.Context, runID uuid.UUID) ([]PfasAgentStep, error) {
	rows, err := q.db.Query(ctx, listStepsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PfasAgentStep{}
	for rows.Next() {
		var i PfasAgentStep
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Position,
			&i.ToolName,
			&i.Status,
			&i.AttemptCount,
			&i.Summary,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCallsForRun = `-- name: ListToolCallsForRun :many
SELECT id, run_id, step_id, attempt, status, request_method, request_path,
       request_hash, response_hash, request_id, source_url, http_status,
       duration_ms, credit_cost, error_code, fetched_at, created_at
FROM pfas.tool_calls
WHERE run_id = $1
ORDER BY created_at
`

type ListToolCallsForRunRow struct {
	ID            uuid.UUID          `json:"id"`
	RunID         uuid.UUID          `json:"run_id"`
	StepID        uuid.UUID          `json:"step_id"`
	Attempt       int32              `json:"attempt"`
	Status        string             `json:"status"`
	RequestMethod string             `json:"request_method"`
	RequestPath   string             `json:"request_path"`
	RequestHash   string             `json:"request_hash"`
	ResponseHash  *string            `json:"response_hash"`
	RequestID     *string            `json:"request_id"`
	SourceUrl     string             `json:"source_url"`
	HttpStatus    *int32             `json:"http_status"`
	DurationMs    int64              `json:"duration_ms"`
	CreditCost    int32              `json:"credit_cost"`
	ErrorCode     *string            `json:"error_code"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListToolCallsForRun(ctx context.Context, runID uuid.UUID) ([]ListToolCallsForRunRow, error) {
	rows, err := q.db.Query(ctx, listToolCallsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListToolCallsForRunRow{}
	for rows.Next() {
		var i ListToolCallsForRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepID,
			&i.Attempt,
			&i.Status,
			&i.RequestMethod,
			&i.RequestPath,
			&i.RequestHash,
			&i.ResponseHash,
			&i.RequestID,
			&i.SourceUrl,
			&i.HttpStatus,
			&i.DurationMs,
			&i.CreditCost,
			&i.ErrorCode,
			&i.FetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunRunning = `-- name: MarkRunRunning :exec
UPDATE pfas.agent_runs
SET status = 'RUNNING', started_at = COALESCE(started_at, now()), updated_at = now()
WHERE id = $1 AND status = 'QUEUED'
`

func (q *Queries) MarkRunRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRunRunning, id)
	return err
}

const markStepRunning = `-- name: MarkStepRunning :one
UPDATE pfas.agent_steps
SET status = 'RUNNING',
    attempt_count = attempt_count + 1,
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE id = $1
RETURNING id, run_id, position, tool_name, status, attempt_count, summary, started_at, completed_at, updated_at
`

func (q *Queries) MarkStepRunning(ctx context.Context, id uuid.UUID) (PfasAgentStep, error) {
	row := q.db.QueryRow(ctx, markStepRunning, id)
	var i PfasAgentStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Position,
		&i.ToolName,
		&i.Status,
		&i.AttemptCount,
		&i.Summary,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const waitRunForInput = `-- name: WaitRunForInput :exec
UPDATE pfas.agent_runs
SET status = 'WAITING_FOR_INPUT', updated_at = now()
WHERE id = $1
`

func (q *Queries) WaitRunForInput(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, waitRunForInput, id)
	return err
}
