import { useCallback, useEffect, useState } from 'react';
import { RiArrowRightLine, RiCheckLine, RiErrorWarningLine, RiExternalLinkLine, RiFileTextLine, RiLoopRightLine, RiMapPin2Line, RiShieldCheckLine, RiTimeLine } from '@remixicon/react';

import { judgeDemoPackageURL, loadInitialJudgeDemoRun, startJudgeDemoRun, startReviewedJudgeDemoRun, type JudgeDemoCitation, type JudgeDemoRun, type JudgeDemoToolCall } from '@/api';
import { TopNav } from '@/components/top-nav';
import * as Alert from '@/components/ui/alert';
import * as Button from '@/components/ui/button';

export function JudgeDemoPage() {
  const [unresolvedRun, setUnresolvedRun] = useState<JudgeDemoRun | null>(null);
  const [reviewedRun, setReviewedRun] = useState<JudgeDemoRun | null>(null);
  const [activeMode, setActiveMode] = useState<'UNRESOLVED' | 'REVIEWED_EVIDENCE'>('UNRESOLVED');
  const [runningAction, setRunningAction] = useState<'initial' | 'unresolved' | 'reviewed' | null>('initial');
  const [error, setError] = useState<string | null>(null);
  const replay = useCallback(async (signal?: AbortSignal) => {
    setRunningAction('unresolved'); setError(null);
    try { const result = await startJudgeDemoRun(signal); setUnresolvedRun(result); setReviewedRun(null); setActiveMode('UNRESOLVED'); }
    catch (reason) { if (!signal?.aborted) setError(reason instanceof Error ? reason.message : 'The prepared case could not be replayed.'); }
    finally { if (!signal?.aborted) setRunningAction(null); }
  }, []);
  const applyReviewedEvidence = useCallback(async () => {
    if (!unresolvedRun) return;
    setRunningAction('reviewed'); setError(null);
    try { const result = await startReviewedJudgeDemoRun(unresolvedRun.id); setReviewedRun(result); setActiveMode('REVIEWED_EVIDENCE'); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'The reviewed evidence could not be replayed.'); }
    finally { setRunningAction(null); }
  }, [unresolvedRun]);
  useEffect(() => {
    let active = true;
    loadInitialJudgeDemoRun()
      .then((result) => { if (active) setUnresolvedRun(result); })
      .catch((reason: unknown) => { if (active) setError(reason instanceof Error ? reason.message : 'The prepared case could not be replayed.'); })
      .finally(() => { if (active) setRunningAction(null); });
    return () => { active = false; };
  }, []);

  const run = activeMode === 'REVIEWED_EVIDENCE' && reviewedRun ? reviewedRun : unresolvedRun;

  return <div className="app-shell demo-case-shell"><TopNav /><main className="workspace demo-case">
    <Alert.Root className="demo-case__seed" variant="lighter" status="feature" size="large"><Alert.Icon as={RiShieldCheckLine} /><div><strong>Prepared competition case — seeded, not a live customer record</strong><p>Frozen external inputs run through the production service pipeline; the resulting trace and package are stored in PostgreSQL. No live application is affected.</p></div></Alert.Root>
    {error ? <DemoError message={error} onRetry={() => void replay()} /> : !run ? <DemoLoading /> : <DemoResult run={run} unresolvedRun={unresolvedRun!} reviewedRun={reviewedRun} runningAction={runningAction} onReplay={() => void replay()} onApplyReviewed={() => void applyReviewedEvidence()} onSelectMode={setActiveMode} />}
  </main></div>;
}

function DemoLoading() { return <div className="demo-run-state" role="status"><span className="state-spinner" aria-hidden="true" /><div><h1>Running the prepared decision agent</h1><p>Replaying frozen evidence through the placement engine.</p></div></div>; }
function DemoError({ message, onRetry }: { message: string; onRetry: () => void }) { return <Alert.Root className="demo-run-error" variant="lighter" status="error" size="large" role="alert"><Alert.Icon as={RiErrorWarningLine} /><div><strong>Judge demo could not run</strong><p>{message}</p><Button.Root variant="primary" mode="filled" size="small" onClick={onRetry}>Try again</Button.Root></div></Alert.Root>; }

function DemoResult({ run, unresolvedRun, reviewedRun, runningAction, onReplay, onApplyReviewed, onSelectMode }: { run: JudgeDemoRun; unresolvedRun: JudgeDemoRun; reviewedRun: JudgeDemoRun | null; runningAction: 'initial' | 'unresolved' | 'reviewed' | null; onReplay: () => void; onApplyReviewed: () => void; onSelectMode: (mode: 'UNRESOLVED' | 'REVIEWED_EVIDENCE') => void }) {
  const showFieldCalculations = useDesktopFieldCalculations();
  const reviewed = run.mode === 'REVIEWED_EVIDENCE';
  const beforeA = allocation(run.before, 'Riverbend East'); const beforeB = allocation(run.before, 'North Forty');
  const afterA = allocation(run.after, 'Riverbend East'); const afterB = allocation(run.after, 'North Forty');
  const fieldA = field(run, 'Riverbend East'); const fieldB = field(run, 'North Forty');
  const slope = citation(run, 'slope'); const acreage = citation(run, 'acreage'); const rate = citation(run, 'rate'); const prior = citation(run, 'prior-loading'); const policy = citation(run, 'policy'); const resolution = optionalCitation(run, 'resolution'); const revisedScreening = optionalCitation(run, 'revised-screening');
  return <>
    <header className="demo-case__header"><div><span>Case {run.caseId}</span><h1>Great Lakes WRRF · Batch B-240820</h1><p>{run.batchDryTons} dry tons · two candidate fields · Michigan policy 2024.4</p></div><div className="demo-case__run"><div className="demo-case__run-actions"><Button.Root variant="neutral" mode="stroke" onClick={onReplay} disabled={runningAction !== null} aria-busy={runningAction === 'unresolved'}><RiLoopRightLine aria-hidden="true" /> {runningAction === 'unresolved' ? 'Rerunning…' : 'Rerun unresolved'}</Button.Root><Button.Root variant="primary" mode="filled" onClick={onApplyReviewed} disabled={runningAction !== null || reviewedRun !== null} aria-busy={runningAction === 'reviewed'}><RiShieldCheckLine aria-hidden="true" /> {runningAction === 'reviewed' ? 'Verifying evidence…' : reviewedRun ? 'Reviewed evidence applied' : 'Apply reviewed evidence'}</Button.Root></div><small>Run {run.id.slice(0, 8)} · completed {formatTime(run.completedAt)}</small></div></header>
    <div className="demo-status-strip" aria-label="Run, screening, calculation, and authorization status"><span><RiCheckLine aria-hidden="true" /> Run completed</span>{reviewed ? <span><RiCheckLine aria-hidden="true" /> Sampled terrain screen passed</span> : null}<span>{run.calculationStatus === 'READY' ? 'Calculation ready' : 'Calculation review required'}</span><strong>Professional authorization required</strong></div>
    <nav className="demo-progress" aria-label="Judge demo sequence"><a href="#changed-decision"><span>1</span>Decision change</a><a href="#evidence"><span>2</span>Decisive evidence</a><a href="#agent-actions"><span>3</span>Agent actions</a><a href="#authorization"><span>4</span>Authorization</a></nav>

    {reviewedRun ? <section className="run-comparison" aria-label="Frozen run comparison"><Button.Root variant="neutral" mode="stroke" className={run.mode === 'UNRESOLVED' ? 'is-active' : ''} onClick={() => onSelectMode('UNRESOLVED')}><span>Initial frozen run</span><strong>28 allocated · 24 held</strong><small>Calculation review required · authorization required</small></Button.Root><RiArrowRightLine aria-hidden="true" /><Button.Root variant="neutral" mode="stroke" className={run.mode === 'REVIEWED_EVIDENCE' ? 'is-active' : ''} onClick={() => onSelectMode('REVIEWED_EVIDENCE')}><span>Reviewed-evidence run</span><strong>52 allocated · 0 held</strong><small>Calculation ready · authorization required</small></Button.Root></section> : null}

    <section className="changed-decision" id="changed-decision" aria-labelledby="change-title"><div className="changed-decision__copy"><span><RiMapPin2Line aria-hidden="true" /> {reviewed ? 'Reviewed evidence changed the disposition' : 'Physical evidence changed this plan'}</span><h2 id="change-title">{reviewed ? 'Parent-bound geometry and a new sampled slope screen reopened Field A for calculation.' : 'A captured Mireye slope result blocked Field A from this allocation.'}</h2><p>{reviewed ? `The engine matched the revised Riverbend East polygon to its immutable parent boundary, proved the subset stayed on-site, verified configured reviewer authorization, and received slope results from ${run.resolutionEvidence?.verification.revisedScreening.returnedSampleCount} planned Mireye locations. Those sampled values supported recalculation; they do not establish whole-field slope suitability. The engine allocated the remaining ${afterA} dry tons to Field A, while professional authorization remains required.` : `Riverbend East initially appeared able to take all ${beforeA} dry tons. The captured Mireye batch found a sampled slope above the default surface-application limit. The operator's acreage adjustment does not prove that the high-slope sample was excluded, so the engine allocated ${afterB} tons to Field B and held ${run.after.unallocatedDryTons} tons for a later rerun.`}</p></div><div className="allocation-change" id="allocation" aria-label="Allocation before and after physical screening"><div><span>{reviewed ? 'Initial frozen run' : 'Before physical screening'}</span><strong>{reviewed ? 'Field B' : 'Field A'} <b>{reviewed ? unresolvedRun.after.allocatedDryTons : beforeA} t</b></strong><small>{reviewed ? `${unresolvedRun.after.unallocatedDryTons} t held` : `Field B ${beforeB} t`}</small></div><RiArrowRightLine aria-hidden="true" /><div><span>{reviewed ? 'After reviewed evidence · calculation ready' : 'After screening · calculation review required'}</span><strong>{reviewed ? 'Field A' : 'Field B'} <b>{reviewed ? afterA : afterB} t</b></strong><small>{reviewed ? `${run.after.allocatedDryTons} t allocated · authorization required` : `${run.after.unallocatedDryTons} t unallocated · Field A in review`}</small></div></div></section>

    <section className="demo-section" id="evidence" aria-labelledby="evidence-title"><header><div><span>Evidence</span><h2 id="evidence-title">The decisive facts sit beside their effect</h2></div><small>Frozen {formatDate(run.completedAt)}</small></header><div className="effect-table" role="table" aria-label="Findings, sources, and operational effects"><div className="effect-table__head" role="row"><span role="columnheader">Finding</span><span role="columnheader">Source</span><span role="columnheader">Effect</span></div><EvidenceRow citation={slope} href="#mireye-source" /><EvidenceRow citation={acreage} href="#operator-boundary-input" /><EvidenceRow citation={rate} href="#rmp-source" /><EvidenceRow citation={prior} href="#loading-source" />{resolution ? <EvidenceRow citation={resolution} href="#reviewed-evidence" /> : null}{revisedScreening ? <EvidenceRow citation={revisedScreening} href="#revised-screening-source" /> : null}</div>
      <article className="slope-conversion"><strong>{slope.value}</strong><span>Michigan threshold: 6% grade = {run.resolutionEvidence?.verification.slopeConversion.thresholdDegrees ?? '3.43'}°</span><code>gradePercent = tan(degrees × π / 180) × 100</code><a href={run.resolutionEvidence?.verification.slopeConversion.policySourceUrl ?? policy.sourceUrl} target="_blank" rel="noreferrer">Policy source <RiExternalLinkLine aria-hidden="true" /></a></article>
      {run.resolutionEvidence ? <article className="reviewed-evidence-record" id="reviewed-evidence"><RiShieldCheckLine aria-hidden="true" /><div><span>Seeded demonstration evidence · not an EGLE approval</span><h3>{run.resolutionEvidence.label}</h3><p>Revised record {run.resolutionEvidence.recordId} · boundary v{run.resolutionEvidence.verification.boundaryVersion} · {run.resolutionEvidence.verification.derivedUsableAcres} geometry-derived acres · contained by parent boundary v{run.resolutionEvidence.verification.parentBoundaryVersion} ({run.resolutionEvidence.verification.parentBoundaryAcres} acres).</p><code>parent {run.resolutionEvidence.parentBoundaryRecordId} · {run.resolutionEvidence.parentBoundaryArtifactHash}</code><code>revised {run.resolutionEvidence.recordId} · {run.resolutionEvidence.artifactHash}</code><code>approval {run.resolutionEvidence.reviewerAuthorizationRecordId} · {run.resolutionEvidence.reviewerAuthorizationHash}</code><div id="revised-screening-source"><p><strong>Sampled terrain screen passed</strong> · {run.resolutionEvidence.verification.revisedScreening.returnedSampleCount}/{run.resolutionEvidence.verification.revisedScreening.requestedSampleCount} planned locations returned results using {samplingRuleLabel(run.resolutionEvidence.verification.revisedScreening.algorithmVersion)}. Maximum sampled slope {run.resolutionEvidence.verification.revisedScreening.maximumSlopeDegrees}° = {run.resolutionEvidence.verification.revisedScreening.maximumSlopeGradePercent}% grade.</p><p>{run.resolutionEvidence.verification.revisedScreening.limitation}</p><code>screen {run.resolutionEvidence.revisedScreeningRecordId} · {run.resolutionEvidence.revisedScreeningArtifactHash}</code><small>Spacing {run.resolutionEvidence.verification.revisedScreening.minimumSpacingMeters} m · request cap {run.resolutionEvidence.verification.revisedScreening.maxRequestSamples} · {run.resolutionEvidence.verification.revisedScreening.boundaryNearSampleCount} boundary-near + {run.resolutionEvidence.verification.revisedScreening.interiorSampleCount} interior locations</small></div><small>Roles shown in this case are configured demonstration roles and do not represent a universal EGLE requirement.</small><small>Policy {run.resolutionEvidence.verification.programPolicyVersion} · {run.resolutionEvidence.verification.issuingRole} → {run.resolutionEvidence.verification.reviewerRole} · stored authorization {run.resolutionEvidence.reviewerAuthorizationRecordId}</small></div></article> : null}
      <details className="source-records"><summary>Inspect original and supporting inputs</summary><div className="source-cards"><article id="lab-input"><RiFileTextLine aria-hidden="true" /><div><span>Batch input · page 4</span><h3>PFAS laboratory report</h3><dl><div><dt>PFOS</dt><dd>18.6 µg/kg dry</dd></div><div><dt>PFOA</dt><dd>2.1 µg/kg dry</dd></div></dl><p>EPA 1633 · sample B-240820 · PFAS is one readiness input</p></div></article><article id="policy-input"><RiShieldCheckLine aria-hidden="true" /><div><span>Policy input</span><h3>Michigan rule pack 2024.4</h3><p>{policy.effect}</p><a href={policy.sourceUrl} target="_blank" rel="noreferrer">Open EGLE source <RiExternalLinkLine aria-hidden="true" /></a></div></article><article id="mireye-source"><RiMapPin2Line aria-hidden="true" /><div><span>Captured provider response · {run.mireyeCapture.fixtureVersion}</span><h3>Mireye batch field record</h3><p>Ten fields across five sample points. The real response schema preserves each underlying dataset provider; the sampled slope maximum triggered review.</p><code>{run.mireyeCapture.requestId} · response {run.mireyeCapture.responseHash.slice(0, 12)}… · {formatDateTime(run.mireyeCapture.retrievedAt)}</code><a href={run.mireyeCapture.endpoint} target="_blank" rel="noreferrer">Mireye batch endpoint <RiExternalLinkLine aria-hidden="true" /></a></div></article><article id="operator-boundary-input"><RiFileTextLine aria-hidden="true" /><div><span>Seeded operator input · not Mireye</span><h3>Boundary adjustment v{run.acreageAdjustment.boundaryVersion}</h3><p>{run.acreageAdjustment.recordedBoundaryAcres} recorded acres − {run.acreageAdjustment.excludedAcres} operator-excluded acres = {run.acreageAdjustment.effectiveAcres} effective acres.</p><code>input {run.acreageAdjustment.inputHash.slice(0, 12)}… · {formatDateTime(run.acreageAdjustment.recordedAt)}</code></div></article><article id="rmp-source"><RiFileTextLine aria-hidden="true" /><div><span>Operating input</span><h3>Approved RMP record</h3><p>Riverbend East · {run.acreageAdjustment.recordedBoundaryAcres} recorded usable acres · {rate.value} agronomic rate.</p></div></article><article id="loading-source"><RiFileTextLine aria-hidden="true" /><div><span>Operating input</span><h3>Prior-loading ledger</h3><p>{prior.value} recorded against Field A before this placement.</p></div></article></div></details>
    </section>

    <section className="demo-section demo-fields" id="fields" aria-labelledby="fields-title"><header><div><span>Fields</span><h2 id="fields-title">Engine-checked capacity</h2></div><small>{run.after.allocatedDryTons} allocated · {run.after.unallocatedDryTons} unallocated · {run.calculationStatus === 'READY' ? 'calculation ready' : 'calculation review required'} · authorization required</small></header><details className="demo-field-details" open={showFieldCalculations || undefined}><summary>Inspect both field calculations</summary><div className="demo-field-grid"><article className={`demo-field ${reviewed ? 'demo-field--selected' : 'demo-field--review'}`}><div><span>Field A · rank {fieldA.rank}</span><strong>Riverbend East</strong></div><b>{reviewed ? <><RiCheckLine aria-hidden="true" /> Sampled terrain screen passed · eligible for calculation</> : 'Professional boundary and slope review required'}</b><dl><div><dt>{reviewed ? 'Geometry-derived acres' : 'Operator-supplied acres'}</dt><dd>{reviewed ? run.resolutionEvidence?.verification.derivedUsableAcres : run.acreageAdjustment.effectiveAcres}</dd></div><div><dt>Available capacity</dt><dd>{fieldA.availableCapacityDryTons ? `${fieldA.availableCapacityDryTons} t` : 'Not calculated'}</dd></div><div><dt>Engine allocation</dt><dd>{afterA} t</dd></div></dl><p>{reviewed ? `The immutable boundary and Mireye source hashes matched. The parent-bound polygon excluded the captured high-slope sample, and five planned locations returned below-threshold results. That reopened ${fieldA.availableCapacityDryTons} dry tons of calculation capacity; it did not establish whole-field suitability or authorize application.` : 'The acreage adjustment has no geometry tying it to the high-slope sample. This engine accepts only a stored confirmed-boundary artifact that proves each captured high-slope sample lies outside the revised field.'}</p></article><article className="demo-field demo-field--selected"><div><span>Field B · rank {fieldB.rank}</span><strong>North Forty</strong></div><b><RiCheckLine aria-hidden="true" /> Eligible for calculation and allocated first</b><dl><div><dt>Effective acres</dt><dd>25</dd></div><div><dt>Available capacity</dt><dd>{fieldB.availableCapacityDryTons} t</dd></div><div><dt>Engine allocation</dt><dd>{afterB} t</dd></div></dl><p>{reviewed ? 'The engine retained Field B as rank 1 and then allocated the remaining material to Field A after its sampled terrain screen passed. Professional authorization remains separate.' : `The engine used all currently eligible calculation capacity here. The remaining ${run.after.unallocatedDryTons} dry tons stay unallocated until Field A's review evidence is supplied.`}</p></article></div></details></section>

    <section className="demo-section agent-timeline" id="agent-actions" aria-labelledby="timeline-title"><header><div><span>Agent actions</span><h2 id="timeline-title">Backend-recorded decision calls and freeze receipt</h2></div><small>Run {run.id}</small></header><ol>{run.toolCalls.map((call) => <TimelineEvent key={call.position} call={call} />)}<li className="agent-timeline__receipt"><time>{formatTime(run.freezeReceipt.completedAt)}</time><span>Froze the decision payload and issued artifact receipt {run.freezeReceipt.artifactId.slice(0, 8)}.</span><a href="#decision-package">Freeze receipt <RiArrowRightLine aria-hidden="true" /></a></li></ol></section>

    <section className="demo-section demo-package" id="decision-package" aria-labelledby="package-title"><header><div><span>Decision package</span><h2 id="package-title">Frozen record and controlled handoff</h2></div><div className="demo-package__actions"><b>{run.package.status}</b><Button.Root asChild variant="neutral" mode="stroke" size="small"><a href={judgeDemoPackageURL(run)} download>Download verified JSON</a></Button.Root><Button.Root variant="neutral" mode="stroke" size="small" onClick={() => window.print()}>Print</Button.Root></div></header><div className="demo-package__body"><div><RiFileTextLine aria-hidden="true" /><p><strong>{run.calculationStatus === 'READY' ? 'Calculation ready' : 'Calculation review required'} · {run.after.unallocatedDryTons} dry tons held</strong><span>Package {run.package.id.slice(0, 8)} preserves the same field dispositions, ranks, allocation, citations, authorization requirement, and {reviewed ? 'verified lineage and revised-screening artifacts' : 'unresolved review question'} shown above.</span></p></div><div id="handoff"><RiTimeLine aria-hidden="true" /><p><strong>Professional handoff prepared</strong><span>{run.reviewQuestion}</span></p></div></div><Alert.Root id="authorization" variant="lighter" status="warning" size="large"><div><strong>Professional authorization required</strong><p>{reviewed ? 'The verified evidence made the calculation ready for professional authorization; the agent did not schedule or authorize an application.' : "The agent allocated only to the currently eligible field and held the remaining material. A responsible professional must resolve Field A's slope evidence before the agent can recalculate it."}</p></div></Alert.Root><details className="demo-run-record"><summary>Replay integrity record</summary><dl><div><dt>Run status</dt><dd>{run.runStatus}</dd></div><div><dt>Calculation status</dt><dd>{run.calculationStatus}</dd></div><div><dt>Authorization status</dt><dd>{run.authorizationStatus}</dd></div><div><dt>Run ID</dt><dd>{run.id}</dd></div><div><dt>Parent run</dt><dd>{run.parentRunId || 'Initial frozen run'}</dd></div><div><dt>Engine input</dt><dd>{run.package.inputHash}</dd></div><div><dt>Decision payload hash</dt><dd>{run.package.payloadHash}</dd></div><div><dt>Freeze receipt hash</dt><dd>{run.freezeReceipt.artifactHash}</dd></div><div><dt>Package envelope hash</dt><dd>{run.package.decisionHash}</dd></div><div><dt>Unallocated</dt><dd>{run.after.unallocatedDryTons} dry tons</dd></div></dl></details></section>
    <footer className="pilot-request"><strong>Seeking a Michigan land-application contractor or active program utility</strong><p>Reconstruct 20 completed field decisions and compare missing-evidence detection, field qualification, agreement with the responsible professional, and package completeness. Labor, budget ownership, pricing, and willingness to pay remain unvalidated.</p></footer>
  </>;
}

function EvidenceRow({ citation, href }: { citation: JudgeDemoCitation; href: string }) { return <div className="effect-table__row" role="row"><strong role="cell">{citation.finding}: {citation.value}</strong><span role="cell"><a href={href}>{citation.source} <RiArrowRightLine aria-hidden="true" /></a></span><span role="cell">{citation.effect}</span></div>; }
function TimelineEvent({ call }: { call: JudgeDemoToolCall }) { return <li><time>{formatTime(call.completedAt)}</time><span>{call.summary}</span><a href={localSource(call)}>Source record <RiArrowRightLine aria-hidden="true" /></a></li>; }
function allocation(plan: JudgeDemoRun['after'], fieldName: string): string { return plan.allocations?.find((item) => item.fieldName === fieldName)?.dryTons ?? '0'; }
function field(run: JudgeDemoRun, fieldName: string) { const result = run.after.fields?.find((item) => item.fieldName === fieldName); if (!result) throw new Error(`Prepared result is missing ${fieldName}.`); return result; }
function citation(run: JudgeDemoRun, id: string): JudgeDemoCitation { const result = run.citations.find((item) => item.id === id); if (!result) throw new Error(`Prepared result is missing citation ${id}.`); return result; }
function optionalCitation(run: JudgeDemoRun, id: string): JudgeDemoCitation | undefined { return run.citations.find((item) => item.id === id); }
function localSource(call: JudgeDemoToolCall): string { if (call.toolName === 'lab.report.extract') return '#lab-input'; if (call.toolName === 'policy.classify') return '#policy-input'; if (call.toolName === 'mireye.fetch.batch') return '#mireye-source'; if (call.toolName === 'mireye.revised-boundary.screen') return '#revised-screening-source'; if (call.toolName === 'field.boundary.adjust') return '#operator-boundary-input'; if (call.toolName === 'slope-resolution.verify') return '#reviewed-evidence'; if (call.toolName === 'placement.evaluate') return '#allocation'; return '#decision-package'; }
function samplingRuleLabel(value: string): string { return value === 'POLYGON_STRATIFIED_SCREEN_V1' ? 'bounded polygon screen v1' : value; }
function formatTime(value: string): string { return new Intl.DateTimeFormat('en-US', { hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(value)); }
function formatDate(value: string): string { return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)); }
function formatDateTime(value: string): string { return new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }

function useDesktopFieldCalculations(): boolean {
  const [desktop, setDesktop] = useState(() => typeof window !== 'undefined' && window.matchMedia('(min-width: 621px)').matches);
  useEffect(() => {
    const query = window.matchMedia('(min-width: 621px)');
    const update = () => setDesktop(query.matches);
    update();
    query.addEventListener('change', update);
    return () => query.removeEventListener('change', update);
  }, []);
  return desktop;
}
