// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateReadinessRunData, CreateReadinessRunErrors, CreateReadinessRunResponses, GetLatestReadinessRunData, GetLatestReadinessRunErrors, GetLatestReadinessRunResponses, GetReadinessRunData, GetReadinessRunErrors, GetReadinessRunResponses, HealthLiveData, HealthLiveErrors, HealthLiveResponses, HealthReadyData, HealthReadyErrors, HealthReadyResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Start the fixed Mireye readiness agent
 *
 * Creates a run with exactly three read-only, zero-credit Mireye checks. An active run is returned instead of duplicated.
 */
export const createReadinessRun = <ThrowOnError extends boolean = false>(options?: Options<CreateReadinessRunData, ThrowOnError>): RequestResult<CreateReadinessRunResponses, CreateReadinessRunErrors, ThrowOnError> => (options?.client ?? client).post<CreateReadinessRunResponses, CreateReadinessRunErrors, ThrowOnError>({ url: '/api/v1/readiness-runs', ...options });

/**
 * Get the most recent readiness run
 */
export const getLatestReadinessRun = <ThrowOnError extends boolean = false>(options?: Options<GetLatestReadinessRunData, ThrowOnError>): RequestResult<GetLatestReadinessRunResponses, GetLatestReadinessRunErrors, ThrowOnError> => (options?.client ?? client).get<GetLatestReadinessRunResponses, GetLatestReadinessRunErrors, ThrowOnError>({ url: '/api/v1/readiness-runs/latest', ...options });

/**
 * Get a readiness run and its evidence trace
 */
export const getReadinessRun = <ThrowOnError extends boolean = false>(options: Options<GetReadinessRunData, ThrowOnError>): RequestResult<GetReadinessRunResponses, GetReadinessRunErrors, ThrowOnError> => (options.client ?? client).get<GetReadinessRunResponses, GetReadinessRunErrors, ThrowOnError>({ url: '/api/v1/readiness-runs/{id}', ...options });

/**
 * Check process liveness
 */
export const healthLive = <ThrowOnError extends boolean = false>(options?: Options<HealthLiveData, ThrowOnError>): RequestResult<HealthLiveResponses, HealthLiveErrors, ThrowOnError> => (options?.client ?? client).get<HealthLiveResponses, HealthLiveErrors, ThrowOnError>({ url: '/health/live', ...options });

/**
 * Check database readiness
 */
export const healthReady = <ThrowOnError extends boolean = false>(options?: Options<HealthReadyData, ThrowOnError>): RequestResult<HealthReadyResponses, HealthReadyErrors, ThrowOnError> => (options?.client ?? client).get<HealthReadyResponses, HealthReadyErrors, ThrowOnError>({ url: '/health/ready', ...options });
