// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type CreateRunOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    created: boolean;
    run: Run;
};

export type DataGap = {
    code: string;
    createdAt: string;
    detail: string;
    id: string;
    resolution: string;
    resolvedAt?: string;
    status: string;
    stepId?: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HealthOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    status: 'ok';
};

export type Run = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    completedAt?: string;
    createdAt: string;
    dataGaps: Array<DataGap> | null;
    id: string;
    kind: string;
    nextStep: number;
    startedAt?: string;
    status: string;
    steps: Array<Step> | null;
    toolCalls: Array<ToolCall> | null;
    updatedAt: string;
};

export type Step = {
    attemptCount: number;
    completedAt?: string;
    id: string;
    position: number;
    startedAt?: string;
    status: string;
    summary?: unknown;
    toolName: string;
};

export type ToolCall = {
    attempt: number;
    creditCost: number;
    durationMs: number;
    errorCode?: string;
    fetchedAt: string;
    httpStatus?: number;
    id: string;
    method: string;
    path: string;
    requestHash: string;
    requestId?: string;
    responseHash?: string;
    sourceUrl: string;
    status: string;
    stepId: string;
};

export type CreateRunOutputBodyWritable = {
    created: boolean;
    run: RunWritable;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HealthOutputBodyWritable = {
    status: 'ok';
};

export type RunWritable = {
    completedAt?: string;
    createdAt: string;
    dataGaps: Array<DataGap> | null;
    id: string;
    kind: string;
    nextStep: number;
    startedAt?: string;
    status: string;
    steps: Array<Step> | null;
    toolCalls: Array<ToolCall> | null;
    updatedAt: string;
};

export type CreateReadinessRunData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/readiness-runs';
};

export type CreateReadinessRunErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateReadinessRunError = CreateReadinessRunErrors[keyof CreateReadinessRunErrors];

export type CreateReadinessRunResponses = {
    /**
     * Created
     */
    201: CreateRunOutputBody;
};

export type CreateReadinessRunResponse = CreateReadinessRunResponses[keyof CreateReadinessRunResponses];

export type GetLatestReadinessRunData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/readiness-runs/latest';
};

export type GetLatestReadinessRunErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestReadinessRunError = GetLatestReadinessRunErrors[keyof GetLatestReadinessRunErrors];

export type GetLatestReadinessRunResponses = {
    /**
     * OK
     */
    200: Run;
};

export type GetLatestReadinessRunResponse = GetLatestReadinessRunResponses[keyof GetLatestReadinessRunResponses];

export type GetReadinessRunData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/readiness-runs/{id}';
};

export type GetReadinessRunErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetReadinessRunError = GetReadinessRunErrors[keyof GetReadinessRunErrors];

export type GetReadinessRunResponses = {
    /**
     * OK
     */
    200: Run;
};

export type GetReadinessRunResponse = GetReadinessRunResponses[keyof GetReadinessRunResponses];

export type HealthLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type HealthLiveErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type HealthLiveError = HealthLiveErrors[keyof HealthLiveErrors];

export type HealthLiveResponses = {
    /**
     * OK
     */
    200: HealthOutputBody;
};

export type HealthLiveResponse = HealthLiveResponses[keyof HealthLiveResponses];

export type HealthReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type HealthReadyErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type HealthReadyError = HealthReadyErrors[keyof HealthReadyErrors];

export type HealthReadyResponses = {
    /**
     * OK
     */
    200: HealthOutputBody;
};

export type HealthReadyResponse = HealthReadyResponses[keyof HealthReadyResponses];
