// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:18080' | (string & {});
};

export type AlternativeCandidate = {
    acceptanceStatus: string;
    address: string;
    city: string;
    county: string;
    disposalAreaStatus: string;
    drivingDistanceKm?: number;
    durationMinutes?: number;
    executable: boolean;
    facilityName: string;
    facilityType: string;
    latitude: number;
    longitude: number;
    position: number;
    routeNote?: string;
    routeStatus: string;
    sourceUrl: string;
    straightlineDistanceKm: number;
    wdsId: string;
};

export type Analyte = {
    basis?: string;
    canonicalAnalyte: string;
    detectionLimit?: string;
    id?: string;
    isNonDetect: boolean;
    normalizedDetectionLimitUgKgDry?: string;
    normalizedReportingLimitUgKgDry?: string;
    normalizedValueUgKgDry?: string;
    qualifier?: string;
    reportedAnalyte: string;
    reportingLimit?: string;
    resultText: string;
    sourceBounds?: SourceBounds;
    sourceExcerpt: string;
    sourcePage: number;
    unit?: string;
    value?: string;
};

export type AnalyteEvidence = {
    canonicalAnalyte: string;
    isNonDetect: boolean;
    normalizedValueUgKgDry?: string;
    resultText: string;
    sourcePage: number;
    upperBoundUgKgDry?: string;
};

export type Artifact = {
    format: string;
    mediaType: string;
    sha256: string;
    sizeBytes: number;
    url: string;
};

export type Batch = {
    facilityId: string;
    facilityName: string;
    id: string;
    identifier: string;
    jurisdiction: string;
    percentSolids?: string;
    wetMassKg?: string;
};

export type CsvResult = {
    field?: Field;
    problem?: string;
    row: number;
};

export type Candidate = {
    confidence?: number;
    label?: string;
    latitude?: number;
    longitude?: number;
    matchMethod?: string;
    resolvedAddress?: string;
};

export type Context = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    batches: Array<Batch> | null;
    facilities: Array<Facility> | null;
};

export type Correction = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    analytes: [
        Analyte,
        Analyte
    ] | null;
    basis?: string;
    collectionDate?: string;
    laboratory?: string;
    matrix?: string;
    method?: string;
    sampleIdentifier?: string;
};

export type CreateDecisionPackageOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    created: boolean;
    package: DecisionPackage;
};

export type CreateEvaluationOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    created: boolean;
    evaluation: Evaluation;
};

export type CreateInput = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    county?: string;
    geojson?: string;
    locator?: string;
    locatorKind: 'ADDRESS' | 'COORDINATE' | 'APN' | 'GEOJSON';
    name: string;
};

export type CreatePlacementOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    created: boolean;
    evaluation: PlacementPlan;
};

export type CreatePolicyDecisionOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    created: boolean;
    decision: Decision;
};

export type CreateRunOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    created: boolean;
    run: Run;
};

export type DataGap = {
    code: string;
    createdAt: string;
    detail: string;
    id: string;
    resolution: string;
    resolvedAt?: string;
    status: string;
    stepId?: string;
};

export type Decision = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    analytes: Array<AnalyteEvidence> | null;
    batchId: string;
    batchIdentifier: string;
    blockingReason?: string;
    createdAt: string;
    explanation: string;
    facilityName: string;
    id: string;
    inputHash: string;
    jurisdiction: string;
    matchedRuleId?: string;
    maximumApplicationRateDryTonsPerAcre?: string;
    percentSolids?: string;
    prohibitedActions: Array<string> | null;
    reportId: string;
    reportVersion: number;
    requirements: Array<Requirement> | null;
    rulePack: RulePack;
    tier: string;
    wetMassKg?: string;
};

export type DecisionPackage = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    artifacts: Array<Artifact> | null;
    createdAt: string;
    decisionId: string;
    evidence: Array<EvidenceEntry> | null;
    id: string;
    inputHash: string;
    proposedActions: Array<ProposedAction> | null;
    schemaVersion: string;
    snapshot: Snapshot;
    status: string;
};

export type Details = {
    accessConstraints?: string;
    agronomicRateDryTonsPerAcre?: string;
    cropOrUse?: string;
    knownConstraints?: string;
    miEnviroSiteId?: string;
    priorLoadingDryTons?: string;
    rmpApproved?: boolean;
    rmpDocumentReference?: string;
    usableAcres?: string;
};

export type DetailsInput = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    accessConstraints?: string;
    agronomicRateDryTonsPerAcre?: string;
    cropOrUse?: string;
    knownConstraints?: string;
    miEnviroSiteId?: string;
    priorLoadingDryTons?: string;
    rmpApproved?: boolean;
    rmpDocumentReference?: string;
    usableAcres?: string;
};

export type Draft = {
    analytes: Array<Analyte> | null;
    basis?: string;
    collectionDate?: string;
    confirmedAt?: string;
    createdAt?: string;
    id?: string;
    laboratory?: string;
    matrix?: string;
    method?: string;
    sampleIdentifier?: string;
    source: string;
    status: string;
    version: number;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type Evaluation = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    aggregationVersion: string;
    catalogVersion?: string;
    completedAt?: string;
    createdAt: string;
    facts: Array<FieldFact> | null;
    failureCode?: string;
    failureDetail?: string;
    fieldId: string;
    fieldSetVersion: string;
    gaps: Array<PhysicalDataGap> | null;
    geometryVersion: number;
    id: string;
    projectedCredits: number;
    sampleCount: number;
    samples: Array<SamplePoint> | null;
    startedAt?: string;
    status: string;
    supplemental: Array<SupplementalEvidence> | null;
    updatedAt: string;
};

export type EvidenceEntry = {
    caveat?: string;
    data?: unknown;
    detail: string;
    kind: string;
    position: number;
    provider: string;
    recordId?: string;
    retrievedAt?: string;
    sourceHash?: string;
    sourceUrl?: string;
    sourceVersion?: string;
    status: string;
    title: string;
};

export type Facility = {
    id: string;
    jurisdiction: string;
    name: string;
};

export type FacilityLocation = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    candidates: Array<LocationCandidate> | null;
    confidence?: number;
    confirmed: boolean;
    county?: string;
    disposition: string;
    facilityId: string;
    fetchedAt: string;
    hint?: string;
    id: string;
    input: string;
    kind: string;
    latitude?: number;
    longitude?: number;
    reason?: string;
    resolvedAddress?: string;
    sourceUrl: string;
    state?: string;
};

export type Field = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    createdAt: string;
    details: Details;
    facility: FieldFacility;
    gaps: Array<FieldGap> | null;
    geometry?: Geometry;
    id: string;
    location?: Location;
    locatorInput: string;
    locatorKind: string;
    name: string;
    status: string;
    updatedAt: string;
};

export type FieldContext = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    facilities: Array<FieldFacility> | null;
    fields: Array<Field> | null;
};

export type FieldFacility = {
    id: string;
    jurisdiction: string;
    name: string;
};

export type FieldFact = {
    absentCount: number;
    aggregateMethod: string;
    category: string;
    critical: boolean;
    failedCount: number;
    fetchedAt?: string;
    label: string;
    name: string;
    okCount: number;
    samples: Array<SampleFact> | null;
    source?: string;
    sourceUrl?: string;
    state: string;
    unit?: string;
    value?: unknown;
};

export type FieldGap = {
    code: string;
    createdAt: string;
    detail: string;
    id: string;
    resolution: string;
};

export type FieldGeometryInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    geojson: string;
};

export type Gap = {
    code: string;
    createdAt?: string;
    detail: string;
    fieldName: string;
    id?: string;
    resolution: string;
    resolvedAt?: string;
    status: string;
};

export type Geometry = {
    areaAcres: string;
    confirmed: boolean;
    confirmedAt?: string;
    geojson: unknown;
    hash: string;
    source: string;
    version: number;
};

export type HealthOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    status: 'ok';
};

export type Import = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    results: Array<CsvResult> | null;
};

export type InvestigationLead = {
    caveat: string;
    city?: string;
    evidenceLabel: string;
    evidenceTier: number;
    facilityName: string;
    naicsCodes: Array<string> | null;
    position: number;
    rationale: string;
    registryId: string;
    sourceUrl: string;
    state?: string;
};

export type LabAnalyte = {
    isNonDetect: boolean;
    name: string;
    resultText: string;
    sourceExcerpt: string;
    sourcePage: number;
    upperBoundUgKgDry?: string;
    valueUgKgDry?: string;
};

export type LabSnapshot = {
    analytes: Array<LabAnalyte> | null;
    basis?: string;
    collectionDate?: string;
    confirmedAt?: string;
    gaps: Array<PackageGap> | null;
    laboratory?: string;
    matrix?: string;
    mediaType: string;
    method?: string;
    originalFilename: string;
    reportId: string;
    reportVersion: number;
    sampleIdentifier?: string;
    sha256: string;
};

export type LabUploadOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    created: boolean;
    report: Report;
};

export type Location = {
    candidates: Array<Candidate> | null;
    confidence?: string;
    county?: string;
    disposition: string;
    fetchedAt: string;
    fips?: string;
    hint?: string;
    id: string;
    latitude?: string;
    longitude?: string;
    matchMethod?: string;
    parcel?: Parcel;
    parcelUnavailable: boolean;
    reason?: string;
    requestId?: string;
    resolvedAddress?: string;
    responseHash: string;
    sourceUrl: string;
    state?: string;
};

export type LocationCandidate = {
    confidence?: number;
    label?: string;
    latitude?: number;
    longitude?: number;
    resolvedAddress?: string;
};

export type LocationInput = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    input: string;
    kind: 'address' | 'coord';
};

export type LocationSelection = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    candidateIndex: number;
};

export type PackageGap = {
    code: string;
    critical: boolean;
    detail: string;
    resolution: string;
    source: string;
};

export type Page = {
    extractionMethod: string;
    height?: string;
    number: number;
    text: string;
    width?: string;
};

export type Parcel = {
    apn?: string;
    geometry?: unknown;
    id?: string;
    matchDistanceM?: string;
    matchType?: string;
    source?: string;
};

export type PhysicalDataGap = {
    code: string;
    critical: boolean;
    detail: string;
    source: string;
};

export type PlacementAllocation = {
    acres: string;
    dryTons: string;
    fieldId: string;
    fieldName: string;
    position: number;
    rateDryTonsPerAcre: string;
};

export type PlacementComponent = {
    factName: string;
    label: string;
    source?: string;
    sourceUrl?: string;
    state: string;
    unit?: string;
    value?: unknown;
};

export type PlacementField = {
    allowedRateDryTonsPerAcre?: string;
    availableCapacityDryTons?: string;
    categories: Array<VulnerabilityCategory> | null;
    counterfactual?: string;
    dataGapCount: number;
    disposition: string;
    explanation: string;
    fieldId: string;
    fieldName: string;
    highConcernCount: number;
    moderateConcernCount: number;
    physicalEvaluationId?: string;
    rank?: number;
    reasons: Array<string> | null;
    roadAccessDistanceM?: number;
};

export type PlacementGap = {
    code: string;
    detail: string;
    resolution: string;
};

export type PlacementPlan = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    allocatedDryTons?: string;
    allocations: Array<PlacementAllocation> | null;
    batchDryTons?: string;
    configChecksum: string;
    configVersion: string;
    createdAt: string;
    decisionId: string;
    fields: Array<PlacementField> | null;
    gaps: Array<PlacementGap> | null;
    id: string;
    inputHash: string;
    percentSolids?: string;
    status: string;
    tier: string;
    unallocatedDryTons?: string;
    wetMassKg?: string;
};

export type PlanInput = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    percentSolids?: string;
    wetMassKg?: string;
};

export type ProposedAction = {
    category: string;
    code: string;
    detail: string;
    executable: boolean;
    position: number;
    sourceId: string;
    state: string;
    timing: string;
    title: string;
};

export type Report = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    batch: Batch;
    confirmedAt?: string;
    createdAt: string;
    draft?: Draft;
    facility: Facility;
    failureCode?: string;
    gaps: Array<Gap> | null;
    id: string;
    mediaType: string;
    originalFilename: string;
    pages: Array<Page> | null;
    sha256: string;
    sizeBytes: number;
    status: string;
    updatedAt: string;
};

export type Requirement = {
    authorityType: string;
    detail: string;
    id: string;
    ruleId: string;
    sourceTitle: string;
    sourceUrl: string;
    timing: string;
    title: string;
};

export type RequirementDefinition = {
    detail: string;
    id: string;
    tiers: Array<string> | null;
    timing: string;
    title: string;
};

export type ResponseDataGap = {
    code: string;
    critical: boolean;
    detail: string;
    resolution: string;
};

export type ResponseEvidence = {
    caveat: string;
    data: unknown;
    fetchedAt: string;
    kind: string;
    provider: string;
    sourceUrl: string;
    sourceVintage?: string;
    status: string;
    summary: string;
    title: string;
};

export type ResponseRun = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    alternatives: Array<AlternativeCandidate> | null;
    batchIdentifier: string;
    createdAt: string;
    dataGaps: Array<ResponseDataGap> | null;
    decisionId: string;
    evidence: Array<ResponseEvidence> | null;
    facilityLocationId: string;
    facilityName: string;
    failureCode?: string;
    failureDetail?: string;
    id: string;
    investigationLeads: Array<InvestigationLead> | null;
    location: FacilityLocation;
    policySourceUrl: string;
    policyVersion: string;
    status: string;
    tasks: Array<ResponseTask> | null;
    tier: string;
    updatedAt: string;
};

export type ResponseTask = {
    category: string;
    code: string;
    detail: string;
    position: number;
    state: string;
    timing: string;
    title: string;
};

export type Rule = {
    explanation: string;
    id: string;
    maximumApplicationRateDryTonsPerAcre?: string;
    operator: string;
    prohibitedActions?: Array<string> | null;
    thresholdUgKgDry: string;
    tier: string;
};

export type RulePack = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    acceptedAnalyticalMethodTokens: Array<string> | null;
    authorityType: string;
    checksum: string;
    code: string;
    effectiveFrom: string;
    elevatedThresholdUgKgDry: string;
    explanation: string;
    jurisdiction: string;
    prohibitedThresholdUgKgDry: string;
    requirements: Array<RequirementDefinition> | null;
    retrievedAt: string;
    reviewStatus: string;
    reviewedAt: string;
    reviewedBy: string;
    rules: Array<Rule> | null;
    schemaVersion: number;
    sourceTitle: string;
    sourceUrl: string;
    version: string;
};

export type Run = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    completedAt?: string;
    createdAt: string;
    dataGaps: Array<DataGap> | null;
    id: string;
    kind: string;
    nextStep: number;
    startedAt?: string;
    status: string;
    steps: Array<Step> | null;
    toolCalls: Array<ToolCall> | null;
    updatedAt: string;
};

export type SampleFact = {
    confidence?: string;
    datasetVintage?: string;
    error?: string;
    fetchedAt?: string;
    index: number;
    label: string;
    latitude: number;
    longitude: number;
    notes?: string;
    source?: string;
    sourceUrl?: string;
    status: string;
    unit?: string;
    value?: unknown;
};

export type SamplePoint = {
    index: number;
    label: string;
    latitude: number;
    longitude: number;
};

export type Snapshot = {
    decision: Decision;
    gaps: Array<PackageGap> | null;
    lab: LabSnapshot;
    physicalEvidence: Array<Evaluation> | null;
    placement?: PlacementPlan;
    response?: ResponseRun;
};

export type SourceBounds = {
    end: number;
    start: number;
};

export type StartInput = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    facilityLocationId: string;
};

export type StartResponseOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    created: boolean;
    run: ResponseRun;
};

export type Step = {
    attemptCount: number;
    completedAt?: string;
    id: string;
    position: number;
    startedAt?: string;
    status: string;
    summary?: unknown;
    toolName: string;
};

export type SupplementalEvidence = {
    caveat?: string;
    fetchedAt: string;
    kind: string;
    provider: string;
    sourceUrl: string;
    sourceVintage?: string;
    status: string;
    summary: string;
    title: string;
    value?: unknown;
};

export type ToolCall = {
    attempt: number;
    creditCost: number;
    durationMs: number;
    errorCode?: string;
    fetchedAt: string;
    httpStatus?: number;
    id: string;
    method: string;
    path: string;
    requestHash: string;
    requestId?: string;
    responseHash?: string;
    sourceUrl: string;
    status: string;
    stepId: string;
};

export type VulnerabilityCategory = {
    authorityType: string;
    band: string;
    components: Array<PlacementComponent> | null;
    configVersion: string;
    explanation: string;
    key: string;
    label: string;
    sourceTitle: string;
    sourceUrl: string;
};

export type CsvResultWritable = {
    field?: FieldWritable;
    problem?: string;
    row: number;
};

export type ContextWritable = {
    batches: Array<Batch> | null;
    facilities: Array<Facility> | null;
};

export type CorrectionWritable = {
    analytes: [
        Analyte,
        Analyte
    ] | null;
    basis?: string;
    collectionDate?: string;
    laboratory?: string;
    matrix?: string;
    method?: string;
    sampleIdentifier?: string;
};

export type CreateDecisionPackageOutputBodyWritable = {
    created: boolean;
    package: DecisionPackageWritable;
};

export type CreateEvaluationOutputBodyWritable = {
    created: boolean;
    evaluation: EvaluationWritable;
};

export type CreateInputWritable = {
    county?: string;
    geojson?: string;
    locator?: string;
    locatorKind: 'ADDRESS' | 'COORDINATE' | 'APN' | 'GEOJSON';
    name: string;
};

export type CreatePlacementOutputBodyWritable = {
    created: boolean;
    evaluation: PlacementPlanWritable;
};

export type CreatePolicyDecisionOutputBodyWritable = {
    created: boolean;
    decision: DecisionWritable;
};

export type CreateRunOutputBodyWritable = {
    created: boolean;
    run: RunWritable;
};

export type DecisionWritable = {
    analytes: Array<AnalyteEvidence> | null;
    batchId: string;
    batchIdentifier: string;
    blockingReason?: string;
    createdAt: string;
    explanation: string;
    facilityName: string;
    id: string;
    inputHash: string;
    jurisdiction: string;
    matchedRuleId?: string;
    maximumApplicationRateDryTonsPerAcre?: string;
    percentSolids?: string;
    prohibitedActions: Array<string> | null;
    reportId: string;
    reportVersion: number;
    requirements: Array<Requirement> | null;
    rulePack: RulePackWritable;
    tier: string;
    wetMassKg?: string;
};

export type DecisionPackageWritable = {
    artifacts: Array<Artifact> | null;
    createdAt: string;
    decisionId: string;
    evidence: Array<EvidenceEntry> | null;
    id: string;
    inputHash: string;
    proposedActions: Array<ProposedAction> | null;
    schemaVersion: string;
    snapshot: SnapshotWritable;
    status: string;
};

export type DetailsInputWritable = {
    accessConstraints?: string;
    agronomicRateDryTonsPerAcre?: string;
    cropOrUse?: string;
    knownConstraints?: string;
    miEnviroSiteId?: string;
    priorLoadingDryTons?: string;
    rmpApproved?: boolean;
    rmpDocumentReference?: string;
    usableAcres?: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type EvaluationWritable = {
    aggregationVersion: string;
    catalogVersion?: string;
    completedAt?: string;
    createdAt: string;
    facts: Array<FieldFact> | null;
    failureCode?: string;
    failureDetail?: string;
    fieldId: string;
    fieldSetVersion: string;
    gaps: Array<PhysicalDataGap> | null;
    geometryVersion: number;
    id: string;
    projectedCredits: number;
    sampleCount: number;
    samples: Array<SamplePoint> | null;
    startedAt?: string;
    status: string;
    supplemental: Array<SupplementalEvidence> | null;
    updatedAt: string;
};

export type FacilityLocationWritable = {
    candidates: Array<LocationCandidate> | null;
    confidence?: number;
    confirmed: boolean;
    county?: string;
    disposition: string;
    facilityId: string;
    fetchedAt: string;
    hint?: string;
    id: string;
    input: string;
    kind: string;
    latitude?: number;
    longitude?: number;
    reason?: string;
    resolvedAddress?: string;
    sourceUrl: string;
    state?: string;
};

export type FieldWritable = {
    createdAt: string;
    details: Details;
    facility: FieldFacility;
    gaps: Array<FieldGap> | null;
    geometry?: Geometry;
    id: string;
    location?: Location;
    locatorInput: string;
    locatorKind: string;
    name: string;
    status: string;
    updatedAt: string;
};

export type FieldContextWritable = {
    facilities: Array<FieldFacility> | null;
    fields: Array<FieldWritable> | null;
};

export type FieldGeometryInputBodyWritable = {
    geojson: string;
};

export type HealthOutputBodyWritable = {
    status: 'ok';
};

export type ImportWritable = {
    results: Array<CsvResultWritable> | null;
};

export type LabUploadOutputBodyWritable = {
    created: boolean;
    report: ReportWritable;
};

export type LocationInputWritable = {
    input: string;
    kind: 'address' | 'coord';
};

export type LocationSelectionWritable = {
    candidateIndex: number;
};

export type PlacementPlanWritable = {
    allocatedDryTons?: string;
    allocations: Array<PlacementAllocation> | null;
    batchDryTons?: string;
    configChecksum: string;
    configVersion: string;
    createdAt: string;
    decisionId: string;
    fields: Array<PlacementField> | null;
    gaps: Array<PlacementGap> | null;
    id: string;
    inputHash: string;
    percentSolids?: string;
    status: string;
    tier: string;
    unallocatedDryTons?: string;
    wetMassKg?: string;
};

export type PlanInputWritable = {
    percentSolids?: string;
    wetMassKg?: string;
};

export type ReportWritable = {
    batch: Batch;
    confirmedAt?: string;
    createdAt: string;
    draft?: Draft;
    facility: Facility;
    failureCode?: string;
    gaps: Array<Gap> | null;
    id: string;
    mediaType: string;
    originalFilename: string;
    pages: Array<Page> | null;
    sha256: string;
    sizeBytes: number;
    status: string;
    updatedAt: string;
};

export type ResponseRunWritable = {
    alternatives: Array<AlternativeCandidate> | null;
    batchIdentifier: string;
    createdAt: string;
    dataGaps: Array<ResponseDataGap> | null;
    decisionId: string;
    evidence: Array<ResponseEvidence> | null;
    facilityLocationId: string;
    facilityName: string;
    failureCode?: string;
    failureDetail?: string;
    id: string;
    investigationLeads: Array<InvestigationLead> | null;
    location: FacilityLocationWritable;
    policySourceUrl: string;
    policyVersion: string;
    status: string;
    tasks: Array<ResponseTask> | null;
    tier: string;
    updatedAt: string;
};

export type RulePackWritable = {
    acceptedAnalyticalMethodTokens: Array<string> | null;
    authorityType: string;
    checksum: string;
    code: string;
    effectiveFrom: string;
    elevatedThresholdUgKgDry: string;
    explanation: string;
    jurisdiction: string;
    prohibitedThresholdUgKgDry: string;
    requirements: Array<RequirementDefinition> | null;
    retrievedAt: string;
    reviewStatus: string;
    reviewedAt: string;
    reviewedBy: string;
    rules: Array<Rule> | null;
    schemaVersion: number;
    sourceTitle: string;
    sourceUrl: string;
    version: string;
};

export type RunWritable = {
    completedAt?: string;
    createdAt: string;
    dataGaps: Array<DataGap> | null;
    id: string;
    kind: string;
    nextStep: number;
    startedAt?: string;
    status: string;
    steps: Array<Step> | null;
    toolCalls: Array<ToolCall> | null;
    updatedAt: string;
};

export type SnapshotWritable = {
    decision: DecisionWritable;
    gaps: Array<PackageGap> | null;
    lab: LabSnapshot;
    physicalEvidence: Array<EvaluationWritable> | null;
    placement?: PlacementPlanWritable;
    response?: ResponseRunWritable;
};

export type StartInputWritable = {
    facilityLocationId: string;
};

export type StartResponseOutputBodyWritable = {
    created: boolean;
    run: ResponseRunWritable;
};

export type GetCandidateFieldData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/candidate-fields/{id}';
};

export type GetCandidateFieldErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetCandidateFieldError = GetCandidateFieldErrors[keyof GetCandidateFieldErrors];

export type GetCandidateFieldResponses = {
    /**
     * OK
     */
    200: Field;
};

export type GetCandidateFieldResponse = GetCandidateFieldResponses[keyof GetCandidateFieldResponses];

export type ConfirmFieldBoundaryData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/candidate-fields/{id}/boundary-confirmation';
};

export type ConfirmFieldBoundaryErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ConfirmFieldBoundaryError = ConfirmFieldBoundaryErrors[keyof ConfirmFieldBoundaryErrors];

export type ConfirmFieldBoundaryResponses = {
    /**
     * OK
     */
    200: Field;
};

export type ConfirmFieldBoundaryResponse = ConfirmFieldBoundaryResponses[keyof ConfirmFieldBoundaryResponses];

export type UpdateFieldDetailsData = {
    body: DetailsInputWritable;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/candidate-fields/{id}/details';
};

export type UpdateFieldDetailsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateFieldDetailsError = UpdateFieldDetailsErrors[keyof UpdateFieldDetailsErrors];

export type UpdateFieldDetailsResponses = {
    /**
     * OK
     */
    200: Field;
};

export type UpdateFieldDetailsResponse = UpdateFieldDetailsResponses[keyof UpdateFieldDetailsResponses];

export type SetFieldGeometryData = {
    body: FieldGeometryInputBodyWritable;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/candidate-fields/{id}/geometry';
};

export type SetFieldGeometryErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SetFieldGeometryError = SetFieldGeometryErrors[keyof SetFieldGeometryErrors];

export type SetFieldGeometryResponses = {
    /**
     * OK
     */
    200: Field;
};

export type SetFieldGeometryResponse = SetFieldGeometryResponses[keyof SetFieldGeometryResponses];

export type SelectFieldLocationData = {
    body: LocationSelectionWritable;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/candidate-fields/{id}/location-selection';
};

export type SelectFieldLocationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SelectFieldLocationError = SelectFieldLocationErrors[keyof SelectFieldLocationErrors];

export type SelectFieldLocationResponses = {
    /**
     * OK
     */
    200: Field;
};

export type SelectFieldLocationResponse = SelectFieldLocationResponses[keyof SelectFieldLocationResponses];

export type ConfirmFieldParcelData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/candidate-fields/{id}/parcel-confirmation';
};

export type ConfirmFieldParcelErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ConfirmFieldParcelError = ConfirmFieldParcelErrors[keyof ConfirmFieldParcelErrors];

export type ConfirmFieldParcelResponses = {
    /**
     * OK
     */
    200: Field;
};

export type ConfirmFieldParcelResponse = ConfirmFieldParcelResponses[keyof ConfirmFieldParcelResponses];

export type StartPhysicalEvaluationData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/candidate-fields/{id}/physical-evaluations';
};

export type StartPhysicalEvaluationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type StartPhysicalEvaluationError = StartPhysicalEvaluationErrors[keyof StartPhysicalEvaluationErrors];

export type StartPhysicalEvaluationResponses = {
    /**
     * Accepted
     */
    202: CreateEvaluationOutputBody;
};

export type StartPhysicalEvaluationResponse = StartPhysicalEvaluationResponses[keyof StartPhysicalEvaluationResponses];

export type GetLatestPhysicalEvaluationData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/candidate-fields/{id}/physical-evaluations/latest';
};

export type GetLatestPhysicalEvaluationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestPhysicalEvaluationError = GetLatestPhysicalEvaluationErrors[keyof GetLatestPhysicalEvaluationErrors];

export type GetLatestPhysicalEvaluationResponses = {
    /**
     * OK
     */
    200: Evaluation;
};

export type GetLatestPhysicalEvaluationResponse = GetLatestPhysicalEvaluationResponses[keyof GetLatestPhysicalEvaluationResponses];

export type ResolveCandidateFieldData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/candidate-fields/{id}/resolution';
};

export type ResolveCandidateFieldErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ResolveCandidateFieldError = ResolveCandidateFieldErrors[keyof ResolveCandidateFieldErrors];

export type ResolveCandidateFieldResponses = {
    /**
     * OK
     */
    200: Field;
};

export type ResolveCandidateFieldResponse = ResolveCandidateFieldResponses[keyof ResolveCandidateFieldResponses];

export type GetDecisionPackageData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/decision-packages/{id}';
};

export type GetDecisionPackageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetDecisionPackageError = GetDecisionPackageErrors[keyof GetDecisionPackageErrors];

export type GetDecisionPackageResponses = {
    /**
     * OK
     */
    200: DecisionPackage;
};

export type GetDecisionPackageResponse = GetDecisionPackageResponses[keyof GetDecisionPackageResponses];

export type ExportDecisionPackageData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
        format: 'html' | 'pdf' | 'json';
    };
    query?: never;
    url: '/api/v1/decision-packages/{id}/exports/{format}';
};

export type ExportDecisionPackageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ExportDecisionPackageError = ExportDecisionPackageErrors[keyof ExportDecisionPackageErrors];

export type ExportDecisionPackageResponses = {
    /**
     * OK
     */
    200: string;
};

export type ExportDecisionPackageResponse = ExportDecisionPackageResponses[keyof ExportDecisionPackageResponses];

export type CreateCandidateFieldData = {
    body: CreateInputWritable;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        facilityId: string;
    };
    query?: never;
    url: '/api/v1/facilities/{facilityId}/candidate-fields';
};

export type CreateCandidateFieldErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateCandidateFieldError = CreateCandidateFieldErrors[keyof CreateCandidateFieldErrors];

export type CreateCandidateFieldResponses = {
    /**
     * Created
     */
    201: Field;
};

export type CreateCandidateFieldResponse = CreateCandidateFieldResponses[keyof CreateCandidateFieldResponses];

export type ImportCandidateFieldsData = {
    body?: {
        csv: Blob | File;
    };
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        facilityId: string;
    };
    query?: never;
    url: '/api/v1/facilities/{facilityId}/candidate-fields/import';
};

export type ImportCandidateFieldsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ImportCandidateFieldsError = ImportCandidateFieldsErrors[keyof ImportCandidateFieldsErrors];

export type ImportCandidateFieldsResponses = {
    /**
     * Created
     */
    201: Import;
};

export type ImportCandidateFieldsResponse = ImportCandidateFieldsResponses[keyof ImportCandidateFieldsResponses];

export type ConfirmResponseFacilityLocationData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/facility-locations/{id}/confirmation';
};

export type ConfirmResponseFacilityLocationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ConfirmResponseFacilityLocationError = ConfirmResponseFacilityLocationErrors[keyof ConfirmResponseFacilityLocationErrors];

export type ConfirmResponseFacilityLocationResponses = {
    /**
     * OK
     */
    200: FacilityLocation;
};

export type ConfirmResponseFacilityLocationResponse = ConfirmResponseFacilityLocationResponses[keyof ConfirmResponseFacilityLocationResponses];

export type GetFieldContextData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path?: never;
    query?: {
        facilityId?: string;
    };
    url: '/api/v1/field-context';
};

export type GetFieldContextErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetFieldContextError = GetFieldContextErrors[keyof GetFieldContextErrors];

export type GetFieldContextResponses = {
    /**
     * OK
     */
    200: FieldContext;
};

export type GetFieldContextResponse = GetFieldContextResponses[keyof GetFieldContextResponses];

export type GetLabIntakeContextData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/lab-context';
};

export type GetLabIntakeContextErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLabIntakeContextError = GetLabIntakeContextErrors[keyof GetLabIntakeContextErrors];

export type GetLabIntakeContextResponses = {
    /**
     * OK
     */
    200: Context;
};

export type GetLabIntakeContextResponse = GetLabIntakeContextResponses[keyof GetLabIntakeContextResponses];

export type UploadLabReportData = {
    body?: {
        batchId: string;
        facilityName: string;
        percentSolids?: string;
        report: Blob | File;
        wetMassKg?: string;
    };
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/lab-reports';
};

export type UploadLabReportErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UploadLabReportError = UploadLabReportErrors[keyof UploadLabReportErrors];

export type UploadLabReportResponses = {
    /**
     * Created
     */
    201: LabUploadOutputBody;
};

export type UploadLabReportResponse = UploadLabReportResponses[keyof UploadLabReportResponses];

export type GetLabReportData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/lab-reports/{id}';
};

export type GetLabReportErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLabReportError = GetLabReportErrors[keyof GetLabReportErrors];

export type GetLabReportResponses = {
    /**
     * OK
     */
    200: Report;
};

export type GetLabReportResponse = GetLabReportResponses[keyof GetLabReportResponses];

export type GetPolicyClassificationData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/lab-reports/{id}/classification';
};

export type GetPolicyClassificationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetPolicyClassificationError = GetPolicyClassificationErrors[keyof GetPolicyClassificationErrors];

export type GetPolicyClassificationResponses = {
    /**
     * OK
     */
    200: Decision;
};

export type GetPolicyClassificationResponse = GetPolicyClassificationResponses[keyof GetPolicyClassificationResponses];

export type ClassifyLabReportData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/lab-reports/{id}/classification';
};

export type ClassifyLabReportErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ClassifyLabReportError = ClassifyLabReportErrors[keyof ClassifyLabReportErrors];

export type ClassifyLabReportResponses = {
    /**
     * Created
     */
    201: CreatePolicyDecisionOutputBody;
};

export type ClassifyLabReportResponse = ClassifyLabReportResponses[keyof ClassifyLabReportResponses];

export type ConfirmLabReportData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/lab-reports/{id}/confirmation';
};

export type ConfirmLabReportErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ConfirmLabReportError = ConfirmLabReportErrors[keyof ConfirmLabReportErrors];

export type ConfirmLabReportResponses = {
    /**
     * OK
     */
    200: Report;
};

export type ConfirmLabReportResponse = ConfirmLabReportResponses[keyof ConfirmLabReportResponses];

export type GetLabReportContentData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/lab-reports/{id}/content';
};

export type GetLabReportContentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLabReportContentError = GetLabReportContentErrors[keyof GetLabReportContentErrors];

export type GetLabReportContentResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetLabReportContentResponse = GetLabReportContentResponses[keyof GetLabReportContentResponses];

export type CorrectLabReportData = {
    body: CorrectionWritable;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/lab-reports/{id}/evidence';
};

export type CorrectLabReportErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CorrectLabReportError = CorrectLabReportErrors[keyof CorrectLabReportErrors];

export type CorrectLabReportResponses = {
    /**
     * OK
     */
    200: Report;
};

export type CorrectLabReportResponse = CorrectLabReportResponses[keyof CorrectLabReportResponses];

export type GetPhysicalEvaluationData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/physical-evaluations/{id}';
};

export type GetPhysicalEvaluationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetPhysicalEvaluationError = GetPhysicalEvaluationErrors[keyof GetPhysicalEvaluationErrors];

export type GetPhysicalEvaluationResponses = {
    /**
     * OK
     */
    200: Evaluation;
};

export type GetPhysicalEvaluationResponse = GetPhysicalEvaluationResponses[keyof GetPhysicalEvaluationResponses];

export type CreateDecisionPackageData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/policy-decisions/{id}/decision-packages';
};

export type CreateDecisionPackageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateDecisionPackageError = CreateDecisionPackageErrors[keyof CreateDecisionPackageErrors];

export type CreateDecisionPackageResponses = {
    /**
     * Created
     */
    201: CreateDecisionPackageOutputBody;
};

export type CreateDecisionPackageResponse = CreateDecisionPackageResponses[keyof CreateDecisionPackageResponses];

export type GetLatestDecisionPackageData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/policy-decisions/{id}/decision-packages/latest';
};

export type GetLatestDecisionPackageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestDecisionPackageError = GetLatestDecisionPackageErrors[keyof GetLatestDecisionPackageErrors];

export type GetLatestDecisionPackageResponses = {
    /**
     * OK
     */
    200: DecisionPackage;
};

export type GetLatestDecisionPackageResponse = GetLatestDecisionPackageResponses[keyof GetLatestDecisionPackageResponses];

export type ResolveResponseFacilityLocationData = {
    body: LocationInputWritable;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/policy-decisions/{id}/facility-location';
};

export type ResolveResponseFacilityLocationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ResolveResponseFacilityLocationError = ResolveResponseFacilityLocationErrors[keyof ResolveResponseFacilityLocationErrors];

export type ResolveResponseFacilityLocationResponses = {
    /**
     * Created
     */
    201: FacilityLocation;
};

export type ResolveResponseFacilityLocationResponse = ResolveResponseFacilityLocationResponses[keyof ResolveResponseFacilityLocationResponses];

export type GetLatestResponseFacilityLocationData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/policy-decisions/{id}/facility-location/latest';
};

export type GetLatestResponseFacilityLocationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestResponseFacilityLocationError = GetLatestResponseFacilityLocationErrors[keyof GetLatestResponseFacilityLocationErrors];

export type GetLatestResponseFacilityLocationResponses = {
    /**
     * OK
     */
    200: FacilityLocation;
};

export type GetLatestResponseFacilityLocationResponse = GetLatestResponseFacilityLocationResponses[keyof GetLatestResponseFacilityLocationResponses];

export type CreatePlacementEvaluationData = {
    body: PlanInputWritable;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/policy-decisions/{id}/placement';
};

export type CreatePlacementEvaluationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreatePlacementEvaluationError = CreatePlacementEvaluationErrors[keyof CreatePlacementEvaluationErrors];

export type CreatePlacementEvaluationResponses = {
    /**
     * Created
     */
    201: CreatePlacementOutputBody;
};

export type CreatePlacementEvaluationResponse = CreatePlacementEvaluationResponses[keyof CreatePlacementEvaluationResponses];

export type GetLatestPlacementEvaluationData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/policy-decisions/{id}/placement/latest';
};

export type GetLatestPlacementEvaluationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestPlacementEvaluationError = GetLatestPlacementEvaluationErrors[keyof GetLatestPlacementEvaluationErrors];

export type GetLatestPlacementEvaluationResponses = {
    /**
     * OK
     */
    200: PlacementPlan;
};

export type GetLatestPlacementEvaluationResponse = GetLatestPlacementEvaluationResponses[keyof GetLatestPlacementEvaluationResponses];

export type CreatePfasResponseData = {
    body: StartInputWritable;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/policy-decisions/{id}/response';
};

export type CreatePfasResponseErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreatePfasResponseError = CreatePfasResponseErrors[keyof CreatePfasResponseErrors];

export type CreatePfasResponseResponses = {
    /**
     * Created
     */
    201: StartResponseOutputBody;
};

export type CreatePfasResponseResponse = CreatePfasResponseResponses[keyof CreatePfasResponseResponses];

export type GetLatestPfasResponseData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/policy-decisions/{id}/response/latest';
};

export type GetLatestPfasResponseErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestPfasResponseError = GetLatestPfasResponseErrors[keyof GetLatestPfasResponseErrors];

export type GetLatestPfasResponseResponses = {
    /**
     * OK
     */
    200: ResponseRun;
};

export type GetLatestPfasResponseResponse = GetLatestPfasResponseResponses[keyof GetLatestPfasResponseResponses];

export type GetActiveMichiganRulePackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/policy/rule-packs/mi/active';
};

export type GetActiveMichiganRulePackErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetActiveMichiganRulePackError = GetActiveMichiganRulePackErrors[keyof GetActiveMichiganRulePackErrors];

export type GetActiveMichiganRulePackResponses = {
    /**
     * OK
     */
    200: RulePack;
};

export type GetActiveMichiganRulePackResponse = GetActiveMichiganRulePackResponses[keyof GetActiveMichiganRulePackResponses];

export type CreateReadinessRunData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/readiness-runs';
};

export type CreateReadinessRunErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateReadinessRunError = CreateReadinessRunErrors[keyof CreateReadinessRunErrors];

export type CreateReadinessRunResponses = {
    /**
     * Created
     */
    201: CreateRunOutputBody;
};

export type CreateReadinessRunResponse = CreateReadinessRunResponses[keyof CreateReadinessRunResponses];

export type GetLatestReadinessRunData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/readiness-runs/latest';
};

export type GetLatestReadinessRunErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestReadinessRunError = GetLatestReadinessRunErrors[keyof GetLatestReadinessRunErrors];

export type GetLatestReadinessRunResponses = {
    /**
     * OK
     */
    200: Run;
};

export type GetLatestReadinessRunResponse = GetLatestReadinessRunResponses[keyof GetLatestReadinessRunResponses];

export type GetReadinessRunData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/readiness-runs/{id}';
};

export type GetReadinessRunErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetReadinessRunError = GetReadinessRunErrors[keyof GetReadinessRunErrors];

export type GetReadinessRunResponses = {
    /**
     * OK
     */
    200: Run;
};

export type GetReadinessRunResponse = GetReadinessRunResponses[keyof GetReadinessRunResponses];

export type GetPfasResponseData = {
    body?: never;
    headers?: {
        'X-Workspace-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/response-runs/{id}';
};

export type GetPfasResponseErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetPfasResponseError = GetPfasResponseErrors[keyof GetPfasResponseErrors];

export type GetPfasResponseResponses = {
    /**
     * OK
     */
    200: ResponseRun;
};

export type GetPfasResponseResponse = GetPfasResponseResponses[keyof GetPfasResponseResponses];

export type HealthLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type HealthLiveErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type HealthLiveError = HealthLiveErrors[keyof HealthLiveErrors];

export type HealthLiveResponses = {
    /**
     * OK
     */
    200: HealthOutputBody;
};

export type HealthLiveResponse = HealthLiveResponses[keyof HealthLiveResponses];

export type HealthReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type HealthReadyErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type HealthReadyError = HealthReadyErrors[keyof HealthReadyErrors];

export type HealthReadyResponses = {
    /**
     * OK
     */
    200: HealthOutputBody;
};

export type HealthReadyResponse = HealthReadyResponses[keyof HealthReadyResponses];
